name: Initialize Python Environment

inputs:
  python-version:
    description: Version of Python to use in the environment and install dependencies with
    default: "3.12.10"
  working-directory:
    description: Directory where the requirements can be found; used when multiple repos are checked out
    default: ""

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: setup.py

    - name: Install Setuptools
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: pip install setuptools==68.1.2

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: pip install requirements.txt
