FROM python:3.5

RUN pip3 install unittest-xml-reporting

COPY requirements.txt /workspace/requirements.txt
COPY server_requirements.txt /workspace/server_requirements.txt

RUN pip install -r /workspace/requirements.txt
RUN pip install -r /workspace/server_requirements.txt

ENV PYTHONPATH /workspace
WORKDIR /workspace

VOLUME /workspace

CMD cd ./dataactcore; sleep 10s; alembic upgrade head; top -b
