from random import randint

from tests.unit.dataactcore.factories.staging import AwardFinancialFactory
from tests.unit.dataactcore.factories.staging import ObjectClassProgramActivityFactory
from tests.unit.dataactvalidator.utils import number_of_errors, query_columns


_FILE = 'c20_award_financial'
_TAS = 'c20_award_financial_tas'

af_dict = dict(
    submission_id=randint(1000, 10000),
    tas='some-tas',
    object_class='some-class',
    ussgl480100_undelivered_or_fyb=randint(-10000, -1000),
    ussgl480100_undelivered_or_cpe=randint(-10000, -1000),
    ussgl483100_undelivered_or_cpe=randint(-10000, -1000),
    ussgl488100_upward_adjustm_cpe=randint(-10000, -1000),
    obligations_undelivered_or_fyb=randint(-10000, -1000),
    obligations_undelivered_or_cpe=randint(-10000, -1000),
    ussgl490100_delivered_orde_fyb=randint(-10000, -1000),
    ussgl490100_delivered_orde_cpe=randint(-10000, -1000),
    ussgl493100_delivered_orde_cpe=randint(-10000, -1000),
    ussgl498100_upward_adjustm_cpe=randint(-10000, -1000),
    obligations_delivered_orde_fyb=randint(-10000, -1000),
    obligations_delivered_orde_cpe=randint(-10000, -1000),
    ussgl480200_undelivered_or_fyb=randint(-10000, -1000),
    ussgl480200_undelivered_or_cpe=randint(-10000, -1000),
    ussgl483200_undelivered_or_cpe=randint(-10000, -1000),
    ussgl488200_upward_adjustm_cpe=randint(-10000, -1000),
    gross_outlays_undelivered_fyb=randint(-10000, -1000),
    gross_outlays_undelivered_cpe=randint(-10000, -1000),
    ussgl490200_delivered_orde_cpe=randint(-10000, -1000),
    ussgl490800_authority_outl_fyb=randint(-10000, -1000),
    ussgl490800_authority_outl_cpe=randint(-10000, -1000),
    ussgl498200_upward_adjustm_cpe=randint(-10000, -1000),
    gross_outlays_delivered_or_fyb=randint(-10000, -1000),
    gross_outlays_delivered_or_cpe=randint(-10000, -1000),
    gross_outlay_amount_by_awa_fyb=randint(-10000, -1000),
    gross_outlay_amount_by_awa_cpe=randint(-10000, -1000),
    obligations_incurred_byawa_cpe=randint(-10000, -1000),
    ussgl487100_downward_adjus_cpe=randint(-10000, -1000),
    ussgl497100_downward_adjus_cpe=randint(-10000, -1000),
    ussgl487200_downward_adjus_cpe=randint(-10000, -1000),
    ussgl497200_downward_adjus_cpe=randint(-10000, -1000),
    deobligations_recov_by_awa_cpe=randint(-10000, -1000)
)


def test_column_headers(database):
    expected_subset = {'row_number', 'tas', 'object_class', 'ussgl480100_undelivered_or_fyb_sum_c',
                       'ussgl480100_undelivered_or_cpe_sum_c', 'ussgl483100_undelivered_or_cpe_sum_c',
                       'ussgl488100_upward_adjustm_cpe_sum_c', 'obligations_undelivered_or_fyb_sum_c',
                       'obligations_undelivered_or_cpe_sum_c', 'ussgl490100_delivered_orde_fyb_sum_c',
                       'ussgl490100_delivered_orde_cpe_sum_c', 'ussgl493100_delivered_orde_cpe_sum_c',
                       'ussgl498100_upward_adjustm_cpe_sum_c', 'obligations_delivered_orde_fyb_sum_c',
                       'obligations_delivered_orde_cpe_sum_c', 'ussgl480200_undelivered_or_fyb_sum_c',
                       'ussgl480200_undelivered_or_cpe_sum_c', 'ussgl483200_undelivered_or_cpe_sum_c',
                       'ussgl488200_upward_adjustm_cpe_sum_c', 'gross_outlays_undelivered_fyb_sum_c',
                       'gross_outlays_undelivered_cpe_sum_c', 'ussgl490200_delivered_orde_cpe_sum_c',
                       'ussgl490800_authority_outl_fyb_sum_c', 'ussgl490800_authority_outl_cpe_sum_c',
                       'ussgl498200_upward_adjustm_cpe_sum_c', 'gross_outlays_delivered_or_fyb_sum_c',
                       'gross_outlays_delivered_or_cpe_sum_c', 'gross_outlay_amount_by_awa_fyb_sum_c',
                       'gross_outlay_amount_by_awa_cpe_sum_c', 'obligations_incurred_byawa_cpe_sum_c',
                       'ussgl487100_downward_adjus_cpe_sum_c', 'ussgl497100_downward_adjus_cpe_sum_c',
                       'ussgl487200_downward_adjus_cpe_sum_c', 'ussgl497200_downward_adjus_cpe_sum_c',
                       'deobligations_recov_by_awa_cpe_sum_c', 'ussgl480100_undelivered_or_fyb_sum_b',
                       'ussgl480100_undelivered_or_cpe_sum_b', 'ussgl483100_undelivered_or_cpe_sum_b',
                       'ussgl488100_upward_adjustm_cpe_sum_b', 'obligations_undelivered_or_fyb_sum_b',
                       'obligations_undelivered_or_cpe_sum_b', 'ussgl490100_delivered_orde_fyb_sum_b',
                       'ussgl490100_delivered_orde_cpe_sum_b', 'ussgl493100_delivered_orde_cpe_sum_b',
                       'ussgl498100_upward_adjustm_cpe_sum_b', 'obligations_delivered_orde_fyb_sum_b',
                       'obligations_delivered_orde_cpe_sum_b', 'ussgl480200_undelivered_or_fyb_sum_b',
                       'ussgl480200_undelivered_or_cpe_sum_b', 'ussgl483200_undelivered_or_cpe_sum_b',
                       'ussgl488200_upward_adjustm_cpe_sum_b', 'gross_outlays_undelivered_fyb_sum_b',
                       'gross_outlays_undelivered_cpe_sum_b', 'ussgl490200_delivered_orde_cpe_sum_b',
                       'ussgl490800_authority_outl_fyb_sum_b', 'ussgl490800_authority_outl_cpe_sum_b',
                       'ussgl498200_upward_adjustm_cpe_sum_b', 'gross_outlays_delivered_or_fyb_sum_b',
                       'gross_outlays_delivered_or_cpe_sum_b', 'gross_outlay_amount_by_pro_fyb_sum_b',
                       'gross_outlay_amount_by_pro_cpe_sum_b', 'obligations_incurred_by_pr_cpe_sum_b',
                       'ussgl487100_downward_adjus_cpe_sum_b', 'ussgl497100_downward_adjus_cpe_sum_b',
                       'ussgl487200_downward_adjus_cpe_sum_b', 'ussgl497200_downward_adjus_cpe_sum_b',
                       'deobligations_recov_by_pro_cpe_sum_b'}
    actual = set(query_columns(_FILE, database))
    assert (actual & expected_subset) == expected_subset


def test_success(database):
    """ Tests that the sum of financial elements in File C is less than or equal
     to the corresponding element in File B for the same TAS and Object Class combination"""
    af1 = AwardFinancialFactory(**af_dict)
    af2 = AwardFinancialFactory(**af_dict)

    op1 = ObjectClassProgramActivityFactory(
        ussgl480100_undelivered_or_fyb=af_dict['ussgl480100_undelivered_or_fyb'] * 2,
        ussgl480100_undelivered_or_cpe=af_dict['ussgl480100_undelivered_or_cpe'] * 2,
        ussgl483100_undelivered_or_cpe=af_dict['ussgl483100_undelivered_or_cpe'] * 2,
        ussgl488100_upward_adjustm_cpe=af_dict['ussgl488100_upward_adjustm_cpe'] * 2,
        obligations_undelivered_or_fyb=af_dict['obligations_undelivered_or_fyb'] * 2,
        obligations_undelivered_or_cpe=af_dict['obligations_undelivered_or_cpe'] * 2,
        ussgl490100_delivered_orde_fyb=af_dict['ussgl490100_delivered_orde_fyb'] * 2,
        ussgl490100_delivered_orde_cpe=af_dict['ussgl490100_delivered_orde_cpe'] * 2,
        ussgl493100_delivered_orde_cpe=af_dict['ussgl493100_delivered_orde_cpe'] * 2,
        ussgl498100_upward_adjustm_cpe=af_dict['ussgl498100_upward_adjustm_cpe'] * 2,
        obligations_delivered_orde_fyb=af_dict['obligations_delivered_orde_fyb'] * 2,
        obligations_delivered_orde_cpe=af_dict['obligations_delivered_orde_cpe'] * 2,
        ussgl480200_undelivered_or_fyb=af_dict['ussgl480200_undelivered_or_fyb'] * 2,
        ussgl480200_undelivered_or_cpe=af_dict['ussgl480200_undelivered_or_cpe'] * 2,
        ussgl483200_undelivered_or_cpe=af_dict['ussgl483200_undelivered_or_cpe'] * 2,
        ussgl488200_upward_adjustm_cpe=af_dict['ussgl488200_upward_adjustm_cpe'] * 2,
        gross_outlays_undelivered_fyb=af_dict['gross_outlays_undelivered_fyb'] * 2,
        gross_outlays_undelivered_cpe=af_dict['gross_outlays_undelivered_cpe'] * 2,
        ussgl490200_delivered_orde_cpe=af_dict['ussgl490200_delivered_orde_cpe'] * 2,
        ussgl490800_authority_outl_fyb=af_dict['ussgl490800_authority_outl_fyb'] * 2,
        ussgl490800_authority_outl_cpe=af_dict['ussgl490800_authority_outl_cpe'] * 2,
        ussgl498200_upward_adjustm_cpe=af_dict['ussgl498200_upward_adjustm_cpe'] * 2,
        gross_outlays_delivered_or_fyb=af_dict['gross_outlays_delivered_or_fyb'] * 2,
        gross_outlays_delivered_or_cpe=af_dict['gross_outlays_delivered_or_cpe'] * 2,
        gross_outlay_amount_by_pro_fyb=af_dict['gross_outlay_amount_by_awa_fyb'] * 2,
        gross_outlay_amount_by_pro_cpe=af_dict['gross_outlay_amount_by_awa_cpe'] * 2,
        obligations_incurred_by_pr_cpe=af_dict['obligations_incurred_byawa_cpe'] * 2,
        ussgl487100_downward_adjus_cpe=af_dict['ussgl487100_downward_adjus_cpe'] * 2,
        ussgl497100_downward_adjus_cpe=af_dict['ussgl497100_downward_adjus_cpe'] * 2,
        ussgl487200_downward_adjus_cpe=af_dict['ussgl487200_downward_adjus_cpe'] * 2,
        ussgl497200_downward_adjus_cpe=af_dict['ussgl497200_downward_adjus_cpe'] * 2,
        deobligations_recov_by_pro_cpe=af_dict['deobligations_recov_by_awa_cpe'] * 2,
        tas=af_dict['tas'],
        object_class=af_dict['object_class'],
        submission_id=af_dict['submission_id']
    )

    op2 = ObjectClassProgramActivityFactory(
        ussgl480100_undelivered_or_fyb=af_dict['ussgl480100_undelivered_or_fyb'] * 2,
        ussgl480100_undelivered_or_cpe=af_dict['ussgl480100_undelivered_or_cpe'] * 2,
        ussgl483100_undelivered_or_cpe=af_dict['ussgl483100_undelivered_or_cpe'] * 2,
        ussgl488100_upward_adjustm_cpe=af_dict['ussgl488100_upward_adjustm_cpe'] * 2,
        obligations_undelivered_or_fyb=af_dict['obligations_undelivered_or_fyb'] * 2,
        obligations_undelivered_or_cpe=af_dict['obligations_undelivered_or_cpe'] * 2,
        ussgl490100_delivered_orde_fyb=af_dict['ussgl490100_delivered_orde_fyb'] * 2,
        ussgl490100_delivered_orde_cpe=af_dict['ussgl490100_delivered_orde_cpe'] * 2,
        ussgl493100_delivered_orde_cpe=af_dict['ussgl493100_delivered_orde_cpe'] * 2,
        ussgl498100_upward_adjustm_cpe=af_dict['ussgl498100_upward_adjustm_cpe'] * 2,
        obligations_delivered_orde_fyb=af_dict['obligations_delivered_orde_fyb'] * 2,
        obligations_delivered_orde_cpe=af_dict['obligations_delivered_orde_cpe'] * 2,
        ussgl480200_undelivered_or_fyb=af_dict['ussgl480200_undelivered_or_fyb'] * 2,
        ussgl480200_undelivered_or_cpe=af_dict['ussgl480200_undelivered_or_cpe'] * 2,
        ussgl483200_undelivered_or_cpe=af_dict['ussgl483200_undelivered_or_cpe'] * 2,
        ussgl488200_upward_adjustm_cpe=af_dict['ussgl488200_upward_adjustm_cpe'] * 2,
        gross_outlays_undelivered_fyb=af_dict['gross_outlays_undelivered_fyb'] * 2,
        gross_outlays_undelivered_cpe=af_dict['gross_outlays_undelivered_cpe'] * 2,
        ussgl490200_delivered_orde_cpe=af_dict['ussgl490200_delivered_orde_cpe'] * 2,
        ussgl490800_authority_outl_fyb=af_dict['ussgl490800_authority_outl_fyb'] * 2,
        ussgl490800_authority_outl_cpe=af_dict['ussgl490800_authority_outl_cpe'] * 2,
        ussgl498200_upward_adjustm_cpe=af_dict['ussgl498200_upward_adjustm_cpe'] * 2,
        gross_outlays_delivered_or_fyb=af_dict['gross_outlays_delivered_or_fyb'] * 2,
        gross_outlays_delivered_or_cpe=af_dict['gross_outlays_delivered_or_cpe'] * 2,
        gross_outlay_amount_by_pro_fyb=af_dict['gross_outlay_amount_by_awa_fyb'] * 2,
        gross_outlay_amount_by_pro_cpe=af_dict['gross_outlay_amount_by_awa_cpe'] * 2,
        obligations_incurred_by_pr_cpe=af_dict['obligations_incurred_byawa_cpe'] * 2,
        ussgl487100_downward_adjus_cpe=af_dict['ussgl487100_downward_adjus_cpe'] * 2,
        ussgl497100_downward_adjus_cpe=af_dict['ussgl497100_downward_adjus_cpe'] * 2,
        ussgl487200_downward_adjus_cpe=af_dict['ussgl487200_downward_adjus_cpe'] * 2,
        ussgl497200_downward_adjus_cpe=af_dict['ussgl497200_downward_adjus_cpe'] * 2,
        deobligations_recov_by_pro_cpe=af_dict['deobligations_recov_by_awa_cpe'] * 2,
        tas='some-other-tas',
        object_class=af_dict['object_class'],
        submission_id=af_dict['submission_id']
    )

    op3 = ObjectClassProgramActivityFactory(
        ussgl480100_undelivered_or_fyb=af_dict['ussgl480100_undelivered_or_fyb'] * 2,
        ussgl480100_undelivered_or_cpe=af_dict['ussgl480100_undelivered_or_cpe'] * 2,
        ussgl483100_undelivered_or_cpe=af_dict['ussgl483100_undelivered_or_cpe'] * 2,
        ussgl488100_upward_adjustm_cpe=af_dict['ussgl488100_upward_adjustm_cpe'] * 2,
        obligations_undelivered_or_fyb=af_dict['obligations_undelivered_or_fyb'] * 2,
        obligations_undelivered_or_cpe=af_dict['obligations_undelivered_or_cpe'] * 2,
        ussgl490100_delivered_orde_fyb=af_dict['ussgl490100_delivered_orde_fyb'] * 2,
        ussgl490100_delivered_orde_cpe=af_dict['ussgl490100_delivered_orde_cpe'] * 2,
        ussgl493100_delivered_orde_cpe=af_dict['ussgl493100_delivered_orde_cpe'] * 2,
        ussgl498100_upward_adjustm_cpe=af_dict['ussgl498100_upward_adjustm_cpe'] * 2,
        obligations_delivered_orde_fyb=af_dict['obligations_delivered_orde_fyb'] * 2,
        obligations_delivered_orde_cpe=af_dict['obligations_delivered_orde_cpe'] * 2,
        ussgl480200_undelivered_or_fyb=af_dict['ussgl480200_undelivered_or_fyb'] * 2,
        ussgl480200_undelivered_or_cpe=af_dict['ussgl480200_undelivered_or_cpe'] * 2,
        ussgl483200_undelivered_or_cpe=af_dict['ussgl483200_undelivered_or_cpe'] * 2,
        ussgl488200_upward_adjustm_cpe=af_dict['ussgl488200_upward_adjustm_cpe'] * 2,
        gross_outlays_undelivered_fyb=af_dict['gross_outlays_undelivered_fyb'] * 2,
        gross_outlays_undelivered_cpe=af_dict['gross_outlays_undelivered_cpe'] * 2,
        ussgl490200_delivered_orde_cpe=af_dict['ussgl490200_delivered_orde_cpe'] * 2,
        ussgl490800_authority_outl_fyb=af_dict['ussgl490800_authority_outl_fyb'] * 2,
        ussgl490800_authority_outl_cpe=af_dict['ussgl490800_authority_outl_cpe'] * 2,
        ussgl498200_upward_adjustm_cpe=af_dict['ussgl498200_upward_adjustm_cpe'] * 2,
        gross_outlays_delivered_or_fyb=af_dict['gross_outlays_delivered_or_fyb'] * 2,
        gross_outlays_delivered_or_cpe=af_dict['gross_outlays_delivered_or_cpe'] * 2,
        gross_outlay_amount_by_pro_fyb=af_dict['gross_outlay_amount_by_awa_fyb'] * 2,
        gross_outlay_amount_by_pro_cpe=af_dict['gross_outlay_amount_by_awa_cpe'] * 2,
        obligations_incurred_by_pr_cpe=af_dict['obligations_incurred_byawa_cpe'] * 2,
        ussgl487100_downward_adjus_cpe=af_dict['ussgl487100_downward_adjus_cpe'] * 2,
        ussgl497100_downward_adjus_cpe=af_dict['ussgl497100_downward_adjus_cpe'] * 2,
        ussgl487200_downward_adjus_cpe=af_dict['ussgl487200_downward_adjus_cpe'] * 2,
        ussgl497200_downward_adjus_cpe=af_dict['ussgl497200_downward_adjus_cpe'] * 2,
        deobligations_recov_by_pro_cpe=af_dict['deobligations_recov_by_awa_cpe'] * 2,
        tas=af_dict['tas'],
        object_class='some-other-class',
        submission_id=af_dict['submission_id']
    )

    errors = number_of_errors(_FILE, database, models=[af1, af2, op1, op2, op3])
    assert errors == 0


def test_failure(database):
    """ Tests that the sum of financial elements in File C is not less than or equal
         to the corresponding element in File B for the same TAS and Object Class combination"""
    af1 = AwardFinancialFactory(**af_dict)

    op1 = ObjectClassProgramActivityFactory(
        ussgl480100_undelivered_or_fyb=af_dict['ussgl480100_undelivered_or_fyb']+1,
        ussgl480100_undelivered_or_cpe=af_dict['ussgl480100_undelivered_or_cpe']+1,
        ussgl483100_undelivered_or_cpe=af_dict['ussgl483100_undelivered_or_cpe']+1,
        ussgl488100_upward_adjustm_cpe=af_dict['ussgl488100_upward_adjustm_cpe']+1,
        obligations_undelivered_or_fyb=af_dict['obligations_undelivered_or_fyb']+1,
        obligations_undelivered_or_cpe=af_dict['obligations_undelivered_or_cpe']+1,
        ussgl490100_delivered_orde_fyb=af_dict['ussgl490100_delivered_orde_fyb']+1,
        ussgl490100_delivered_orde_cpe=af_dict['ussgl490100_delivered_orde_cpe']+1,
        ussgl493100_delivered_orde_cpe=af_dict['ussgl493100_delivered_orde_cpe']+1,
        ussgl498100_upward_adjustm_cpe=af_dict['ussgl498100_upward_adjustm_cpe']+1,
        obligations_delivered_orde_fyb=af_dict['obligations_delivered_orde_fyb']+1,
        obligations_delivered_orde_cpe=af_dict['obligations_delivered_orde_cpe']+1,
        ussgl480200_undelivered_or_fyb=af_dict['ussgl480200_undelivered_or_fyb']+1,
        ussgl480200_undelivered_or_cpe=af_dict['ussgl480200_undelivered_or_cpe']+1,
        ussgl483200_undelivered_or_cpe=af_dict['ussgl483200_undelivered_or_cpe']+1,
        ussgl488200_upward_adjustm_cpe=af_dict['ussgl488200_upward_adjustm_cpe']+1,
        gross_outlays_undelivered_fyb=af_dict['gross_outlays_undelivered_fyb']+1,
        gross_outlays_undelivered_cpe=af_dict['gross_outlays_undelivered_cpe']+1,
        ussgl490200_delivered_orde_cpe=af_dict['ussgl490200_delivered_orde_cpe']+1,
        ussgl490800_authority_outl_fyb=af_dict['ussgl490800_authority_outl_fyb']+1,
        ussgl490800_authority_outl_cpe=af_dict['ussgl490800_authority_outl_cpe']+1,
        ussgl498200_upward_adjustm_cpe=af_dict['ussgl498200_upward_adjustm_cpe']+1,
        gross_outlays_delivered_or_fyb=af_dict['gross_outlays_delivered_or_fyb']+1,
        gross_outlays_delivered_or_cpe=af_dict['gross_outlays_delivered_or_cpe']+1,
        gross_outlay_amount_by_pro_fyb=af_dict['gross_outlay_amount_by_awa_fyb']+1,
        gross_outlay_amount_by_pro_cpe=af_dict['gross_outlay_amount_by_awa_cpe']+1,
        obligations_incurred_by_pr_cpe=af_dict['obligations_incurred_byawa_cpe']+1,
        ussgl487100_downward_adjus_cpe=af_dict['ussgl487100_downward_adjus_cpe']+1,
        ussgl497100_downward_adjus_cpe=af_dict['ussgl497100_downward_adjus_cpe']+1,
        ussgl487200_downward_adjus_cpe=af_dict['ussgl487200_downward_adjus_cpe']+1,
        ussgl497200_downward_adjus_cpe=af_dict['ussgl497200_downward_adjus_cpe']+1,
        deobligations_recov_by_pro_cpe=af_dict['deobligations_recov_by_awa_cpe']+1,
        tas=af_dict['tas'],
        object_class=af_dict['object_class'],
        submission_id=af_dict['submission_id']
    )

    op2 = ObjectClassProgramActivityFactory(
        ussgl480100_undelivered_or_fyb=af_dict['ussgl480100_undelivered_or_fyb']+1,
        ussgl480100_undelivered_or_cpe=af_dict['ussgl480100_undelivered_or_cpe']+1,
        ussgl483100_undelivered_or_cpe=af_dict['ussgl483100_undelivered_or_cpe']+1,
        ussgl488100_upward_adjustm_cpe=af_dict['ussgl488100_upward_adjustm_cpe']+1,
        obligations_undelivered_or_fyb=af_dict['obligations_undelivered_or_fyb']+1,
        obligations_undelivered_or_cpe=af_dict['obligations_undelivered_or_cpe']+1,
        ussgl490100_delivered_orde_fyb=af_dict['ussgl490100_delivered_orde_fyb']+1,
        ussgl490100_delivered_orde_cpe=af_dict['ussgl490100_delivered_orde_cpe']+1,
        ussgl493100_delivered_orde_cpe=af_dict['ussgl493100_delivered_orde_cpe']+1,
        ussgl498100_upward_adjustm_cpe=af_dict['ussgl498100_upward_adjustm_cpe']+1,
        obligations_delivered_orde_fyb=af_dict['obligations_delivered_orde_fyb']+1,
        obligations_delivered_orde_cpe=af_dict['obligations_delivered_orde_cpe']+1,
        ussgl480200_undelivered_or_fyb=af_dict['ussgl480200_undelivered_or_fyb']+1,
        ussgl480200_undelivered_or_cpe=af_dict['ussgl480200_undelivered_or_cpe']+1,
        ussgl483200_undelivered_or_cpe=af_dict['ussgl483200_undelivered_or_cpe']+1,
        ussgl488200_upward_adjustm_cpe=af_dict['ussgl488200_upward_adjustm_cpe']+1,
        gross_outlays_undelivered_fyb=af_dict['gross_outlays_undelivered_fyb']+1,
        gross_outlays_undelivered_cpe=af_dict['gross_outlays_undelivered_cpe']+1,
        ussgl490200_delivered_orde_cpe=af_dict['ussgl490200_delivered_orde_cpe']+1,
        ussgl490800_authority_outl_fyb=af_dict['ussgl490800_authority_outl_fyb']+1,
        ussgl490800_authority_outl_cpe=af_dict['ussgl490800_authority_outl_cpe']+1,
        ussgl498200_upward_adjustm_cpe=af_dict['ussgl498200_upward_adjustm_cpe']+1,
        gross_outlays_delivered_or_fyb=af_dict['gross_outlays_delivered_or_fyb']+1,
        gross_outlays_delivered_or_cpe=af_dict['gross_outlays_delivered_or_cpe']+1,
        gross_outlay_amount_by_pro_fyb=af_dict['gross_outlay_amount_by_awa_fyb']+1,
        gross_outlay_amount_by_pro_cpe=af_dict['gross_outlay_amount_by_awa_cpe']+1,
        obligations_incurred_by_pr_cpe=af_dict['obligations_incurred_byawa_cpe']+1,
        ussgl487100_downward_adjus_cpe=af_dict['ussgl487100_downward_adjus_cpe']+1,
        ussgl497100_downward_adjus_cpe=af_dict['ussgl497100_downward_adjus_cpe']+1,
        ussgl487200_downward_adjus_cpe=af_dict['ussgl487200_downward_adjus_cpe']+1,
        ussgl497200_downward_adjus_cpe=af_dict['ussgl497200_downward_adjus_cpe']+1,
        deobligations_recov_by_pro_cpe=af_dict['deobligations_recov_by_awa_cpe']+1,
        tas='some-other-tas',
        object_class=af_dict['object_class'],
        submission_id=af_dict['submission_id']
    )

    op3 = ObjectClassProgramActivityFactory(
        ussgl480100_undelivered_or_fyb=af_dict['ussgl480100_undelivered_or_fyb']+1,
        ussgl480100_undelivered_or_cpe=af_dict['ussgl480100_undelivered_or_cpe']+1,
        ussgl483100_undelivered_or_cpe=af_dict['ussgl483100_undelivered_or_cpe']+1,
        ussgl488100_upward_adjustm_cpe=af_dict['ussgl488100_upward_adjustm_cpe']+1,
        obligations_undelivered_or_fyb=af_dict['obligations_undelivered_or_fyb']+1,
        obligations_undelivered_or_cpe=af_dict['obligations_undelivered_or_cpe']+1,
        ussgl490100_delivered_orde_fyb=af_dict['ussgl490100_delivered_orde_fyb']+1,
        ussgl490100_delivered_orde_cpe=af_dict['ussgl490100_delivered_orde_cpe']+1,
        ussgl493100_delivered_orde_cpe=af_dict['ussgl493100_delivered_orde_cpe']+1,
        ussgl498100_upward_adjustm_cpe=af_dict['ussgl498100_upward_adjustm_cpe']+1,
        obligations_delivered_orde_fyb=af_dict['obligations_delivered_orde_fyb']+1,
        obligations_delivered_orde_cpe=af_dict['obligations_delivered_orde_cpe']+1,
        ussgl480200_undelivered_or_fyb=af_dict['ussgl480200_undelivered_or_fyb']+1,
        ussgl480200_undelivered_or_cpe=af_dict['ussgl480200_undelivered_or_cpe']+1,
        ussgl483200_undelivered_or_cpe=af_dict['ussgl483200_undelivered_or_cpe']+1,
        ussgl488200_upward_adjustm_cpe=af_dict['ussgl488200_upward_adjustm_cpe']+1,
        gross_outlays_undelivered_fyb=af_dict['gross_outlays_undelivered_fyb']+1,
        gross_outlays_undelivered_cpe=af_dict['gross_outlays_undelivered_cpe']+1,
        ussgl490200_delivered_orde_cpe=af_dict['ussgl490200_delivered_orde_cpe']+1,
        ussgl490800_authority_outl_fyb=af_dict['ussgl490800_authority_outl_fyb']+1,
        ussgl490800_authority_outl_cpe=af_dict['ussgl490800_authority_outl_cpe']+1,
        ussgl498200_upward_adjustm_cpe=af_dict['ussgl498200_upward_adjustm_cpe']+1,
        gross_outlays_delivered_or_fyb=af_dict['gross_outlays_delivered_or_fyb']+1,
        gross_outlays_delivered_or_cpe=af_dict['gross_outlays_delivered_or_cpe']+1,
        gross_outlay_amount_by_pro_fyb=af_dict['gross_outlay_amount_by_awa_fyb']+1,
        gross_outlay_amount_by_pro_cpe=af_dict['gross_outlay_amount_by_awa_cpe']+1,
        obligations_incurred_by_pr_cpe=af_dict['obligations_incurred_byawa_cpe']+1,
        ussgl487100_downward_adjus_cpe=af_dict['ussgl487100_downward_adjus_cpe']+1,
        ussgl497100_downward_adjus_cpe=af_dict['ussgl497100_downward_adjus_cpe']+1,
        ussgl487200_downward_adjus_cpe=af_dict['ussgl487200_downward_adjus_cpe']+1,
        ussgl497200_downward_adjus_cpe=af_dict['ussgl497200_downward_adjus_cpe']+1,
        deobligations_recov_by_pro_cpe=af_dict['deobligations_recov_by_awa_cpe']+1,
        tas=af_dict['tas'],
        object_class='some-other-class',
        submission_id=af_dict['submission_id']
    )

    errors = number_of_errors(_FILE, database, models=[af1, op1, op2, op3])
    assert errors == 1
