from tests.unit.dataactcore.factories.staging import AwardFinancialFactory
from tests.unit.dataactvalidator.utils import number_of_errors, query_columns

_FILE = 'c17_award_financial'


def test_column_headers(database):
    expected_subset = {'row_number', 'transaction_obligated_amou', 'uniqueid_TAS', 'uniqueid_PIID', 'uniqueid_FAIN',
                       'uniqueid_URI', 'uniqueid_DisasterEmergencyFundCode'}
    actual = set(query_columns(_FILE, database))
    assert (actual & expected_subset) == expected_subset


def test_success(database):
    """ Test success TransactionObligatedAmount and USSGL related balances and subtotals can't be both provided """
    # Test with none present
    award_fin_empty = AwardFinancialFactory(transaction_obligated_amou=None,
                                            ussgl480100_undelivered_or_cpe=None,
                                            ussgl480100_undelivered_or_fyb=None,
                                            ussgl480200_undelivered_or_cpe=None,
                                            ussgl480200_undelivered_or_fyb=None,
                                            ussgl483100_undelivered_or_cpe=None,
                                            ussgl483200_undelivered_or_cpe=None,
                                            ussgl487100_downward_adjus_cpe=None,
                                            ussgl487200_downward_adjus_cpe=None,
                                            ussgl488100_upward_adjustm_cpe=None,
                                            ussgl488200_upward_adjustm_cpe=None,
                                            ussgl490100_delivered_orde_cpe=None,
                                            ussgl490100_delivered_orde_fyb=None,
                                            ussgl490200_delivered_orde_cpe=None,
                                            ussgl490800_authority_outl_cpe=None,
                                            ussgl490800_authority_outl_fyb=None,
                                            ussgl493100_delivered_orde_cpe=None,
                                            ussgl497100_downward_adjus_cpe=None,
                                            ussgl497200_downward_adjus_cpe=None,
                                            ussgl498100_upward_adjustm_cpe=None,
                                            ussgl498200_upward_adjustm_cpe=None,
                                            gross_outlay_amount_by_awa_cpe=None,
                                            gross_outlay_amount_by_awa_fyb=None,
                                            gross_outlays_delivered_or_cpe=None,
                                            gross_outlays_delivered_or_fyb=None,
                                            gross_outlays_undelivered_cpe=None,
                                            gross_outlays_undelivered_fyb=None,
                                            obligations_delivered_orde_cpe=None,
                                            obligations_delivered_orde_fyb=None,
                                            obligations_incurred_byawa_cpe=None,
                                            obligations_undelivered_or_cpe=None,
                                            obligations_undelivered_or_fyb=None,
                                            deobligations_recov_by_awa_cpe=None
                                            )
    # Test with only one present
    award_fin_amount = AwardFinancialFactory(transaction_obligated_amou=123,
                                             ussgl480100_undelivered_or_cpe=None,
                                             ussgl480100_undelivered_or_fyb=None,
                                             ussgl480200_undelivered_or_cpe=None,
                                             ussgl480200_undelivered_or_fyb=None,
                                             ussgl483100_undelivered_or_cpe=None,
                                             ussgl483200_undelivered_or_cpe=None,
                                             ussgl487100_downward_adjus_cpe=None,
                                             ussgl487200_downward_adjus_cpe=None,
                                             ussgl488100_upward_adjustm_cpe=None,
                                             ussgl488200_upward_adjustm_cpe=None,
                                             ussgl490100_delivered_orde_cpe=None,
                                             ussgl490100_delivered_orde_fyb=None,
                                             ussgl490200_delivered_orde_cpe=None,
                                             ussgl490800_authority_outl_cpe=None,
                                             ussgl490800_authority_outl_fyb=None,
                                             ussgl493100_delivered_orde_cpe=None,
                                             ussgl497100_downward_adjus_cpe=None,
                                             ussgl497200_downward_adjus_cpe=None,
                                             ussgl498100_upward_adjustm_cpe=None,
                                             ussgl498200_upward_adjustm_cpe=None,
                                             gross_outlay_amount_by_awa_cpe=None,
                                             gross_outlay_amount_by_awa_fyb=None,
                                             gross_outlays_delivered_or_cpe=None,
                                             gross_outlays_delivered_or_fyb=None,
                                             gross_outlays_undelivered_cpe=None,
                                             gross_outlays_undelivered_fyb=None,
                                             obligations_delivered_orde_cpe=None,
                                             obligations_delivered_orde_fyb=None,
                                             obligations_incurred_byawa_cpe=None,
                                             obligations_undelivered_or_cpe=None,
                                             obligations_undelivered_or_fyb=None,
                                             deobligations_recov_by_awa_cpe=None
                                             )
    award_fin_ussgl = AwardFinancialFactory(transaction_obligated_amou=None,
                                            ussgl480100_undelivered_or_cpe=None,
                                            ussgl480100_undelivered_or_fyb=None,
                                            ussgl480200_undelivered_or_cpe=None,
                                            ussgl480200_undelivered_or_fyb=None,
                                            ussgl483100_undelivered_or_cpe=None,
                                            ussgl483200_undelivered_or_cpe=123,
                                            ussgl487100_downward_adjus_cpe=None,
                                            ussgl487200_downward_adjus_cpe=None,
                                            ussgl488100_upward_adjustm_cpe=None,
                                            ussgl488200_upward_adjustm_cpe=None,
                                            ussgl490100_delivered_orde_cpe=123,
                                            ussgl490100_delivered_orde_fyb=None,
                                            ussgl490200_delivered_orde_cpe=None,
                                            ussgl490800_authority_outl_cpe=None,
                                            ussgl490800_authority_outl_fyb=None,
                                            ussgl493100_delivered_orde_cpe=None,
                                            ussgl497100_downward_adjus_cpe=None,
                                            ussgl497200_downward_adjus_cpe=None,
                                            ussgl498100_upward_adjustm_cpe=None,
                                            ussgl498200_upward_adjustm_cpe=None,
                                            gross_outlay_amount_by_awa_cpe=None,
                                            gross_outlay_amount_by_awa_fyb=None,
                                            gross_outlays_delivered_or_cpe=123,
                                            gross_outlays_delivered_or_fyb=None,
                                            gross_outlays_undelivered_cpe=None,
                                            gross_outlays_undelivered_fyb=None,
                                            obligations_delivered_orde_cpe=None,
                                            obligations_delivered_orde_fyb=None,
                                            obligations_incurred_byawa_cpe=None,
                                            obligations_undelivered_or_cpe=None,
                                            obligations_undelivered_or_fyb=None,
                                            deobligations_recov_by_awa_cpe=None
                                            )
    award_fin_sub = AwardFinancialFactory(transaction_obligated_amou=None,
                                          ussgl480100_undelivered_or_cpe=None,
                                          ussgl480100_undelivered_or_fyb=None,
                                          ussgl480200_undelivered_or_cpe=None,
                                          ussgl480200_undelivered_or_fyb=None,
                                          ussgl483100_undelivered_or_cpe=None,
                                          ussgl483200_undelivered_or_cpe=None,
                                          ussgl487100_downward_adjus_cpe=None,
                                          ussgl487200_downward_adjus_cpe=None,
                                          ussgl488100_upward_adjustm_cpe=None,
                                          ussgl488200_upward_adjustm_cpe=None,
                                          ussgl490100_delivered_orde_cpe=None,
                                          ussgl490100_delivered_orde_fyb=None,
                                          ussgl490200_delivered_orde_cpe=None,
                                          ussgl490800_authority_outl_cpe=None,
                                          ussgl490800_authority_outl_fyb=None,
                                          ussgl493100_delivered_orde_cpe=None,
                                          ussgl497100_downward_adjus_cpe=None,
                                          ussgl497200_downward_adjus_cpe=None,
                                          ussgl498100_upward_adjustm_cpe=None,
                                          ussgl498200_upward_adjustm_cpe=None,
                                          gross_outlay_amount_by_awa_cpe=None,
                                          gross_outlay_amount_by_awa_fyb=None,
                                          gross_outlays_delivered_or_cpe=None,
                                          gross_outlays_delivered_or_fyb=123,
                                          gross_outlays_undelivered_cpe=None,
                                          gross_outlays_undelivered_fyb=None,
                                          obligations_delivered_orde_cpe=None,
                                          obligations_delivered_orde_fyb=None,
                                          obligations_incurred_byawa_cpe=123,
                                          obligations_undelivered_or_cpe=None,
                                          obligations_undelivered_or_fyb=None,
                                          deobligations_recov_by_awa_cpe=None
                                          )
    assert number_of_errors(_FILE, database, models=[award_fin_empty, award_fin_amount, award_fin_ussgl,
                                                     award_fin_sub]) == 0


def test_failure(database):
    """ Test failure TransactionObligatedAmount and USSGL related balances and subtotals can't be both provided """
    # Test with zeroes
    award_fin_zeros = AwardFinancialFactory(transaction_obligated_amou=0,
                                            ussgl480100_undelivered_or_cpe=None,
                                            ussgl480100_undelivered_or_fyb=None,
                                            ussgl480200_undelivered_or_cpe=0,
                                            ussgl480200_undelivered_or_fyb=None,
                                            ussgl483100_undelivered_or_cpe=None,
                                            ussgl483200_undelivered_or_cpe=None,
                                            ussgl487100_downward_adjus_cpe=None,
                                            ussgl487200_downward_adjus_cpe=None,
                                            ussgl488100_upward_adjustm_cpe=None,
                                            ussgl488200_upward_adjustm_cpe=None,
                                            ussgl490100_delivered_orde_cpe=None,
                                            ussgl490100_delivered_orde_fyb=None,
                                            ussgl490200_delivered_orde_cpe=None,
                                            ussgl490800_authority_outl_cpe=None,
                                            ussgl490800_authority_outl_fyb=0,
                                            ussgl493100_delivered_orde_cpe=None,
                                            ussgl497100_downward_adjus_cpe=None,
                                            ussgl497200_downward_adjus_cpe=None,
                                            ussgl498100_upward_adjustm_cpe=None,
                                            ussgl498200_upward_adjustm_cpe=0,
                                            gross_outlay_amount_by_awa_cpe=None,
                                            gross_outlay_amount_by_awa_fyb=None,
                                            gross_outlays_delivered_or_cpe=None,
                                            gross_outlays_delivered_or_fyb=0,
                                            gross_outlays_undelivered_cpe=None,
                                            gross_outlays_undelivered_fyb=None,
                                            obligations_delivered_orde_cpe=None,
                                            obligations_delivered_orde_fyb=0,
                                            obligations_incurred_byawa_cpe=None,
                                            obligations_undelivered_or_cpe=0,
                                            obligations_undelivered_or_fyb=None,
                                            deobligations_recov_by_awa_cpe=None)
    award_fin_ussgl = AwardFinancialFactory(transaction_obligated_amou=10,
                                            ussgl480100_undelivered_or_cpe=None,
                                            ussgl480100_undelivered_or_fyb=None,
                                            ussgl480200_undelivered_or_cpe=None,
                                            ussgl480200_undelivered_or_fyb=None,
                                            ussgl483100_undelivered_or_cpe=None,
                                            ussgl483200_undelivered_or_cpe=123,
                                            ussgl487100_downward_adjus_cpe=None,
                                            ussgl487200_downward_adjus_cpe=None,
                                            ussgl488100_upward_adjustm_cpe=None,
                                            ussgl488200_upward_adjustm_cpe=None,
                                            ussgl490100_delivered_orde_cpe=123,
                                            ussgl490100_delivered_orde_fyb=None,
                                            ussgl490200_delivered_orde_cpe=None,
                                            ussgl490800_authority_outl_cpe=None,
                                            ussgl490800_authority_outl_fyb=None,
                                            ussgl493100_delivered_orde_cpe=None,
                                            ussgl497100_downward_adjus_cpe=None,
                                            ussgl497200_downward_adjus_cpe=None,
                                            ussgl498100_upward_adjustm_cpe=123,
                                            ussgl498200_upward_adjustm_cpe=None,
                                            gross_outlay_amount_by_awa_cpe=None,
                                            gross_outlay_amount_by_awa_fyb=None,
                                            gross_outlays_delivered_or_cpe=None,
                                            gross_outlays_delivered_or_fyb=None,
                                            gross_outlays_undelivered_cpe=None,
                                            gross_outlays_undelivered_fyb=None,
                                            obligations_delivered_orde_cpe=None,
                                            obligations_delivered_orde_fyb=None,
                                            obligations_incurred_byawa_cpe=None,
                                            obligations_undelivered_or_cpe=None,
                                            obligations_undelivered_or_fyb=None,
                                            deobligations_recov_by_awa_cpe=None
                                            )
    award_fin_sub = AwardFinancialFactory(transaction_obligated_amou=100,
                                          ussgl480100_undelivered_or_cpe=None,
                                          ussgl480100_undelivered_or_fyb=None,
                                          ussgl480200_undelivered_or_cpe=None,
                                          ussgl480200_undelivered_or_fyb=None,
                                          ussgl483100_undelivered_or_cpe=None,
                                          ussgl483200_undelivered_or_cpe=None,
                                          ussgl487100_downward_adjus_cpe=None,
                                          ussgl487200_downward_adjus_cpe=None,
                                          ussgl488100_upward_adjustm_cpe=None,
                                          ussgl488200_upward_adjustm_cpe=None,
                                          ussgl490100_delivered_orde_cpe=None,
                                          ussgl490100_delivered_orde_fyb=None,
                                          ussgl490200_delivered_orde_cpe=None,
                                          ussgl490800_authority_outl_cpe=None,
                                          ussgl490800_authority_outl_fyb=None,
                                          ussgl493100_delivered_orde_cpe=None,
                                          ussgl497100_downward_adjus_cpe=None,
                                          ussgl497200_downward_adjus_cpe=None,
                                          ussgl498100_upward_adjustm_cpe=None,
                                          ussgl498200_upward_adjustm_cpe=None,
                                          gross_outlay_amount_by_awa_cpe=None,
                                          gross_outlay_amount_by_awa_fyb=None,
                                          gross_outlays_delivered_or_cpe=123,
                                          gross_outlays_delivered_or_fyb=None,
                                          gross_outlays_undelivered_cpe=None,
                                          gross_outlays_undelivered_fyb=None,
                                          obligations_delivered_orde_cpe=123,
                                          obligations_delivered_orde_fyb=None,
                                          obligations_incurred_byawa_cpe=None,
                                          obligations_undelivered_or_cpe=None,
                                          obligations_undelivered_or_fyb=None,
                                          deobligations_recov_by_awa_cpe=None
                                          )
    award_fin_both = AwardFinancialFactory(transaction_obligated_amou=10,
                                           ussgl480100_undelivered_or_cpe=None,
                                           ussgl480100_undelivered_or_fyb=None,
                                           ussgl480200_undelivered_or_cpe=None,
                                           ussgl480200_undelivered_or_fyb=None,
                                           ussgl483100_undelivered_or_cpe=None,
                                           ussgl483200_undelivered_or_cpe=123,
                                           ussgl487100_downward_adjus_cpe=None,
                                           ussgl487200_downward_adjus_cpe=None,
                                           ussgl488100_upward_adjustm_cpe=None,
                                           ussgl488200_upward_adjustm_cpe=None,
                                           ussgl490100_delivered_orde_cpe=123,
                                           ussgl490100_delivered_orde_fyb=None,
                                           ussgl490200_delivered_orde_cpe=None,
                                           ussgl490800_authority_outl_cpe=None,
                                           ussgl490800_authority_outl_fyb=None,
                                           ussgl493100_delivered_orde_cpe=None,
                                           ussgl497100_downward_adjus_cpe=None,
                                           ussgl497200_downward_adjus_cpe=None,
                                           ussgl498100_upward_adjustm_cpe=123,
                                           ussgl498200_upward_adjustm_cpe=None,
                                           gross_outlay_amount_by_awa_cpe=None,
                                           gross_outlay_amount_by_awa_fyb=None,
                                           gross_outlays_delivered_or_cpe=None,
                                           gross_outlays_delivered_or_fyb=None,
                                           gross_outlays_undelivered_cpe=123,
                                           gross_outlays_undelivered_fyb=None,
                                           obligations_delivered_orde_cpe=None,
                                           obligations_delivered_orde_fyb=None,
                                           obligations_incurred_byawa_cpe=None,
                                           obligations_undelivered_or_cpe=None,
                                           obligations_undelivered_or_fyb=123,
                                           deobligations_recov_by_awa_cpe=123
                                           )
    assert number_of_errors(_FILE, database,
                            models=[award_fin_ussgl, award_fin_zeros, award_fin_sub, award_fin_both]) == 4
