from sqlalchemy import Column, Date, func, Integer, BigInteger, Text, Index, ARRAY

from dataactcore.models.baseModel import Base


class SAMSubcontract(Base):
    """ Model for SAM subcontract data """
    __tablename__ = 'sam_subcontract'
    sam_subcontract_id = Column(Integer, primary_key=True)
    subaward_report_id = Column(Integer, index=True, unique=True)
    subaward_report_number = Column(Text, index=True, unique=True)
    unique_award_key = Column(Text)
    date_submitted = Column(Date)
    contract_agency_code = Column(Text)
    contract_idv_agency_code = Column(Text)
    award_number = Column(Text)
    award_amount = Column(Text)
    action_date = Column(Date)
    uei = Column(Text)
    legal_business_name = Column(Text)
    parent_uei = Column(Text)
    parent_legal_business_name = Column(Text)
    dba_name = Column(Text)
    legal_entity_country_code = Column(Text)
    legal_entity_country_name = Column(Text)
    legal_entity_state_code = Column(Text)
    legal_entity_state_name = Column(Text)
    legal_entity_address_line1 = Column(Text)
    legal_entity_address_line2 = Column(Text)
    legal_entity_city_name = Column(Text)
    legal_entity_zip_code = Column(Text, index=True)
    legal_entity_congressional = Column(Text)
    ppop_country_code = Column(Text)
    ppop_country_name = Column(Text)
    ppop_state_code = Column(Text)
    ppop_state_name = Column(Text)
    ppop_address_line1 = Column(Text)
    ppop_city_name = Column(Text)
    ppop_zip_code = Column(Text, index=True)
    ppop_congressional_district = Column(Text)
    business_types_codes = Column(ARRAY(Text))
    business_types_names = Column(ARRAY(Text))
    description = Column(Text)
    high_comp_officer1_full_na = Column(Text)
    high_comp_officer1_amount = Column(Text)
    high_comp_officer2_full_na = Column(Text)
    high_comp_officer2_amount = Column(Text)
    high_comp_officer3_full_na = Column(Text)
    high_comp_officer3_amount = Column(Text)
    high_comp_officer4_full_na = Column(Text)
    high_comp_officer4_amount = Column(Text)
    high_comp_officer5_full_na = Column(Text)
    high_comp_officer5_amount = Column(Text)


Index("ix_sam_subcontract_updated_at", SAMSubcontract.updated_at)
Index("ix_sam_subcontract_uak_upper", func.upper(SAMSubcontract.unique_award_key))
Index("ix_sam_subcontract_uei_upper", func.upper(SAMSubcontract.uei))
Index("ix_sam_subcontract_puei_upper", func.upper(SAMSubcontract.parent_uei))
Index("ix_sam_subcontract_le_country_upper", func.upper(SAMSubcontract.legal_entity_country_code))
Index("ix_sam_subcontract_le_state_upper", func.upper(SAMSubcontract.legal_entity_state_code))
Index("ix_sam_subcontract_ppop_country_upper", func.upper(SAMSubcontract.ppop_country_code))
Index("ix_sam_subcontract_ppop_state_upper", func.upper(SAMSubcontract.ppop_state_code))


class SAMSubgrant(Base):
    """ Model for SAM subgrant data """
    __tablename__ = 'sam_subgrant'
    sam_subgrant_id = Column(Integer, primary_key=True)
    subaward_report_id = Column(Integer, index=True, unique=True)
    subaward_report_number = Column(Text, index=True, unique=True)
    unique_award_key = Column(Text)
    date_submitted = Column(Date)
    award_number = Column(Text)
    award_amount = Column(Text)
    action_date = Column(Date)
    uei = Column(Text)
    legal_business_name = Column(Text)
    parent_uei = Column(Text)
    parent_legal_business_name = Column(Text)
    dba_name = Column(Text)
    legal_entity_country_code = Column(Text)
    legal_entity_country_name = Column(Text)
    legal_entity_state_code = Column(Text)
    legal_entity_state_name = Column(Text)
    legal_entity_address_line1 = Column(Text)
    legal_entity_address_line2 = Column(Text)
    legal_entity_city_name = Column(Text)
    legal_entity_zip_code = Column(Text, index=True)
    legal_entity_congressional = Column(Text)
    ppop_country_code = Column(Text)
    ppop_country_name = Column(Text)
    ppop_state_code = Column(Text)
    ppop_state_name = Column(Text)
    ppop_address_line1 = Column(Text)
    ppop_city_name = Column(Text)
    ppop_zip_code = Column(Text, index=True)
    ppop_congressional_district = Column(Text)
    business_types_codes = Column(ARRAY(Text))
    business_types_names = Column(ARRAY(Text))
    description = Column(Text)
    high_comp_officer1_full_na = Column(Text)
    high_comp_officer1_amount = Column(Text)
    high_comp_officer2_full_na = Column(Text)
    high_comp_officer2_amount = Column(Text)
    high_comp_officer3_full_na = Column(Text)
    high_comp_officer3_amount = Column(Text)
    high_comp_officer4_full_na = Column(Text)
    high_comp_officer4_amount = Column(Text)
    high_comp_officer5_full_na = Column(Text)
    high_comp_officer5_amount = Column(Text)


Index("ix_sam_subgrant_updated_at", SAMSubgrant.updated_at)
Index("ix_sam_subgrant_uak_upper", func.upper(SAMSubgrant.ppop_country_code))
Index("ix_sam_subgrant_uei_upper", func.upper(SAMSubgrant.uei))
Index("ix_sam_subgrant_puei_upper", func.upper(SAMSubgrant.parent_uei))
Index("ix_sam_subgrant_le_country_upper", func.upper(SAMSubgrant.legal_entity_country_code))
Index("ix_sam_subgrant_le_state_upper", func.upper(SAMSubgrant.legal_entity_state_code))
Index("ix_sam_subgrant_ppop_country_upper", func.upper(SAMSubgrant.ppop_country_code))
Index("ix_sam_subgrant_ppop_state_upper", func.upper(SAMSubgrant.ppop_state_code))


class Subaward(Base):
    """ Model for all subaward data """
    __tablename__ = "subaward"
    id = Column(BigInteger, primary_key=True)

    # File F - Prime Award Data
    unique_award_key = Column(Text, index=True)
    award_id = Column(Text, index=True)
    parent_award_id = Column(Text, index=True)
    award_amount = Column(Text)
    action_date = Column(Text, index=True)
    fy = Column(Text)
    awarding_agency_code = Column(Text, index=True)
    awarding_agency_name = Column(Text)
    awarding_sub_tier_agency_c = Column(Text, index=True)
    awarding_sub_tier_agency_n = Column(Text)
    awarding_office_code = Column(Text)
    awarding_office_name = Column(Text)
    funding_agency_code = Column(Text, index=True)
    funding_agency_name = Column(Text)
    funding_sub_tier_agency_co = Column(Text, index=True)
    funding_sub_tier_agency_na = Column(Text)
    funding_office_code = Column(Text)
    funding_office_name = Column(Text)
    awardee_or_recipient_uniqu = Column(Text, index=True)
    awardee_or_recipient_uei = Column(Text, index=True)
    awardee_or_recipient_legal = Column(Text)
    dba_name = Column(Text)
    ultimate_parent_unique_ide = Column(Text)
    ultimate_parent_uei = Column(Text)
    ultimate_parent_legal_enti = Column(Text)
    legal_entity_country_code = Column(Text)
    legal_entity_country_name = Column(Text)
    legal_entity_address_line1 = Column(Text)
    legal_entity_city_name = Column(Text)
    legal_entity_state_code = Column(Text)
    legal_entity_state_name = Column(Text)
    legal_entity_zip = Column(Text)
    legal_entity_county_code = Column(Text)
    legal_entity_county_name = Column(Text)
    legal_entity_congressional = Column(Text)
    legal_entity_foreign_posta = Column(Text)
    business_types = Column(Text)
    place_of_perform_city_name = Column(Text)
    place_of_perform_state_code = Column(Text)
    place_of_perform_state_name = Column(Text)
    place_of_performance_zip = Column(Text)
    place_of_performance_county_code = Column(Text)
    place_of_performance_county_name = Column(Text)
    place_of_perform_congressio = Column(Text)
    place_of_perform_country_co = Column(Text)
    place_of_perform_country_na = Column(Text)
    award_description = Column(Text)
    naics = Column(Text)
    naics_description = Column(Text)
    assistance_listing_numbers = Column(Text)
    assistance_listing_titles = Column(Text)
    # File F - Subaward Data
    subaward_type = Column(Text, index=True)
    subaward_report_year = Column(Text)
    subaward_report_month = Column(Text)
    subaward_number = Column(Text, index=True)
    subaward_amount = Column(Text)
    sub_action_date = Column(Text, index=True)
    sub_awardee_or_recipient_uniqu = Column(Text, index=True)
    sub_awardee_or_recipient_uei = Column(Text, index=True)
    sub_awardee_or_recipient_legal = Column(Text)
    sub_dba_name = Column(Text)
    sub_ultimate_parent_unique_ide = Column(Text)
    sub_ultimate_parent_uei = Column(Text)
    sub_ultimate_parent_legal_enti = Column(Text)
    sub_legal_entity_country_code = Column(Text)
    sub_legal_entity_country_name = Column(Text)
    sub_legal_entity_address_line1 = Column(Text)
    sub_legal_entity_city_name = Column(Text)
    sub_legal_entity_state_code = Column(Text)
    sub_legal_entity_state_name = Column(Text)
    sub_legal_entity_zip = Column(Text)
    sub_legal_entity_county_code = Column(Text)
    sub_legal_entity_county_name = Column(Text)
    sub_legal_entity_congressional = Column(Text)
    sub_legal_entity_foreign_posta = Column(Text)
    sub_business_types = Column(Text)
    sub_place_of_perform_city_name = Column(Text)
    sub_place_of_perform_state_code = Column(Text)
    sub_place_of_perform_state_name = Column(Text)
    sub_place_of_performance_zip = Column(Text)
    sub_place_of_performance_county_code = Column(Text)
    sub_place_of_performance_county_name = Column(Text)
    sub_place_of_perform_congressio = Column(Text)
    sub_place_of_perform_country_co = Column(Text)
    sub_place_of_perform_country_na = Column(Text)
    subaward_description = Column(Text)
    sub_high_comp_officer1_full_na = Column(Text, nullable=True)
    sub_high_comp_officer1_amount = Column(Text, nullable=True)
    sub_high_comp_officer2_full_na = Column(Text, nullable=True)
    sub_high_comp_officer2_amount = Column(Text, nullable=True)
    sub_high_comp_officer3_full_na = Column(Text, nullable=True)
    sub_high_comp_officer3_amount = Column(Text, nullable=True)
    sub_high_comp_officer4_full_na = Column(Text, nullable=True)
    sub_high_comp_officer4_amount = Column(Text, nullable=True)
    sub_high_comp_officer5_full_na = Column(Text, nullable=True)
    sub_high_comp_officer5_amount = Column(Text, nullable=True)
    # Additional Subaward - Prime Award Data
    prime_id = Column(Integer, index=True)
    internal_id = Column(Text, index=True, unique=True)
    date_submitted = Column(Text)
    report_type = Column(Text)
    transaction_type = Column(Text)
    program_title = Column(Text)
    contract_agency_code = Column(Text)
    contract_idv_agency_code = Column(Text)
    grant_funding_agency_id = Column(Text)
    grant_funding_agency_name = Column(Text)
    federal_agency_name = Column(Text)
    treasury_symbol = Column(Text)
    dunsplus4 = Column(Text)
    recovery_model_q1 = Column(Text)
    recovery_model_q2 = Column(Text)
    compensation_q1 = Column(Text)
    compensation_q2 = Column(Text)
    high_comp_officer1_full_na = Column(Text, nullable=True)
    high_comp_officer1_amount = Column(Text, nullable=True)
    high_comp_officer2_full_na = Column(Text, nullable=True)
    high_comp_officer2_amount = Column(Text, nullable=True)
    high_comp_officer3_full_na = Column(Text, nullable=True)
    high_comp_officer3_amount = Column(Text, nullable=True)
    high_comp_officer4_full_na = Column(Text, nullable=True)
    high_comp_officer4_amount = Column(Text, nullable=True)
    high_comp_officer5_full_na = Column(Text, nullable=True)
    high_comp_officer5_amount = Column(Text, nullable=True)
    place_of_perform_street = Column(Text)

    # Additional Subaward - Subaward Data
    sub_id = Column(Integer, index=True, unique=True)
    sub_parent_id = Column(Integer, index=True)
    sub_federal_agency_id = Column(Text)
    sub_federal_agency_name = Column(Text)
    sub_funding_agency_id = Column(Text)
    sub_funding_agency_name = Column(Text)
    sub_funding_office_id = Column(Text)
    sub_funding_office_name = Column(Text)
    sub_naics = Column(Text)
    sub_assistance_listing_numbers = Column(Text)
    sub_dunsplus4 = Column(Text)
    sub_recovery_subcontract_amt = Column(Text)
    sub_recovery_model_q1 = Column(Text)
    sub_recovery_model_q2 = Column(Text)
    sub_compensation_q1 = Column(Text)
    sub_compensation_q2 = Column(Text)
    sub_place_of_perform_street = Column(Text)


Index("ix_subaward_award_id_upper", func.upper(Subaward.award_id))
Index("ix_subaward_parent_award_id_upper", func.upper(Subaward.parent_award_id))
Index("ix_subaward_awarding_sub_tier_agency_c_upper", func.upper(Subaward.awarding_sub_tier_agency_c))
