"""Remove fpds_contracting_offices table

Revision ID: 0225d53e520a
Revises: 4c4dd19af4ac
Create Date: 2020-03-27 12:29:45.162563

"""

# revision identifiers, used by Alembic.
revision = '0225d53e520a'
down_revision = '4c4dd19af4ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fpds_contracting_offices')
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpds_contracting_offices',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('FPDS_contracting_office_id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agency_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contracting_office_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contracting_office_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('FPDS_contracting_office_id', name='fpds_contracting_offices_pkey')
    )
    # ### end Alembic commands ###

