"""distinguish territories and freely associated states in country codes

Revision ID: 02c7c16ddfc6
Revises: 186c77a3662e
Create Date: 2026-07-28 23:25:29.327593

"""

# revision identifiers, used by Alembic.
revision = '02c7c16ddfc6'
down_revision = '186c77a3662e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_code', sa.Column('territory', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('country_code', sa.Column('free_state', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('country_code', 'territory_free_state')
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_code', sa.Column('territory_free_state', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('country_code', 'free_state')
    op.drop_column('country_code', 'territory')
    # ### end Alembic commands ###

