"""adding tas columns

Revision ID: 089e94d3dc03
Revises: b35d25a57731
Create Date: 2018-08-07 16:23:36.485535

"""

# revision identifiers, used by Alembic.
revision = '089e94d3dc03'
down_revision = 'b35d25a57731'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tas_lookup', sa.Column('account_title', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('budget_bureau_code', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('budget_bureau_name', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('budget_function_code', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('budget_function_title', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('budget_subfunction_code', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('budget_subfunction_title', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('reporting_agency_aid', sa.Text(), nullable=True))
    op.add_column('tas_lookup', sa.Column('reporting_agency_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tas_lookup', 'reporting_agency_name')
    op.drop_column('tas_lookup', 'reporting_agency_aid')
    op.drop_column('tas_lookup', 'budget_subfunction_title')
    op.drop_column('tas_lookup', 'budget_subfunction_code')
    op.drop_column('tas_lookup', 'budget_function_title')
    op.drop_column('tas_lookup', 'budget_function_code')
    op.drop_column('tas_lookup', 'budget_bureau_name')
    op.drop_column('tas_lookup', 'budget_bureau_code')
    op.drop_column('tas_lookup', 'account_title')
    # ### end Alembic commands ###

