"""adding federal_agency_id, federal_agency_name

Revision ID: 08c4db2f3007
Revises: 8d66e1b5702d
Create Date: 2019-02-28 20:50:02.184053

"""

# revision identifiers, used by Alembic.
revision = '08c4db2f3007'
down_revision = '8d66e1b5702d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fsrs_grant', sa.Column('federal_agency_id', sa.String(), nullable=True))
    op.add_column('fsrs_grant', sa.Column('federal_agency_name', sa.String(), nullable=True))
    op.add_column('fsrs_subgrant', sa.Column('federal_agency_id', sa.String(), nullable=True))
    op.add_column('fsrs_subgrant', sa.Column('federal_agency_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fsrs_subgrant', 'federal_agency_name')
    op.drop_column('fsrs_subgrant', 'federal_agency_id')
    op.drop_column('fsrs_grant', 'federal_agency_name')
    op.drop_column('fsrs_grant', 'federal_agency_id')
    # ### end Alembic commands ###

