"""Adding unique transaction keys to staging models

Revision ID: 0cf297fa927c
Revises: 94efce2e7882
Create Date: 2019-03-21 17:14:34.938006

"""

# revision identifiers, used by Alembic.
revision = '0cf297fa927c'
down_revision = '94efce2e7882'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial_assistance', sa.Column('afa_generated_unique', sa.Text(), nullable=True))
    op.add_column('award_procurement', sa.Column('detached_award_proc_unique', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('award_procurement', 'detached_award_proc_unique')
    op.drop_column('award_financial_assistance', 'afa_generated_unique')
    # ### end Alembic commands ###

