"""Adding a lookup to provide specific pages for the messages to show up

Revision ID: 159dab0cb368
Revises: 18d9b114c1dc
Create Date: 2017-07-27 10:32:54.029745

"""

# revision identifiers, used by Alembic.
revision = '159dab0cb368'
down_revision = '18d9b114c1dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_type',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.add_column('submission_window', sa.Column('application_type', sa.Integer(), nullable=True))
    op.create_foreign_key('application', 'submission_window', 'application_type', ['application_type'], ['application_id'])
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application', 'submission_window', type_='foreignkey')
    op.drop_column('submission_window', 'application_type')
    op.drop_table('application_type')
    ### end Alembic commands ###

