"""addLabelToMulti

Revision ID: 17a20023b474
Revises: b9e9c047042d
Create Date: 2016-04-24 18:36:24.287000

"""

# revision identifiers, used by Alembic.
revision = '17a20023b474'
down_revision = 'b9e9c047042d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()

def upgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multi_field_rule', sa.Column('rule_label', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multi_field_rule', 'rule_label')
    ### end Alembic commands ###

def upgrade_error_data():
    pass

def downgrade_error_data():
    pass

def upgrade_job_tracker():
    pass

def downgrade_job_tracker():
    pass

def upgrade_user_manager():
    pass

def downgrade_user_manager():
    pass