""" Adding uniqueness to subaward id indexes

Revision ID: 199230f4bcdb
Revises: dfc0fb029b42
Create Date: 2025-04-03 18:26:12.232970

"""

# revision identifiers, used by Alembic.
revision = '199230f4bcdb'
down_revision = 'dfc0fb029b42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sam_subcontract_subaward_report_id', table_name='sam_subcontract')
    op.create_index(op.f('ix_sam_subcontract_subaward_report_id'), 'sam_subcontract', ['subaward_report_id'], unique=True)
    op.drop_index('ix_sam_subcontract_subaward_report_number', table_name='sam_subcontract')
    op.create_index(op.f('ix_sam_subcontract_subaward_report_number'), 'sam_subcontract', ['subaward_report_number'], unique=True)
    op.drop_index('ix_sam_subgrant_subaward_report_id', table_name='sam_subgrant')
    op.create_index(op.f('ix_sam_subgrant_subaward_report_id'), 'sam_subgrant', ['subaward_report_id'], unique=True)
    op.drop_index('ix_sam_subgrant_subaward_report_number', table_name='sam_subgrant')
    op.create_index(op.f('ix_sam_subgrant_subaward_report_number'), 'sam_subgrant', ['subaward_report_number'], unique=True)
    op.drop_index('ix_subaward_internal_id', table_name='subaward')
    op.create_index(op.f('ix_subaward_internal_id'), 'subaward', ['internal_id'], unique=True)
    op.drop_index('ix_subaward_sub_id', table_name='subaward')
    op.create_index(op.f('ix_subaward_sub_id'), 'subaward', ['sub_id'], unique=True)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subaward_sub_id'), table_name='subaward')
    op.create_index('ix_subaward_sub_id', 'subaward', ['sub_id'], unique=False)
    op.drop_index(op.f('ix_subaward_internal_id'), table_name='subaward')
    op.create_index('ix_subaward_internal_id', 'subaward', ['internal_id'], unique=False)
    op.drop_index(op.f('ix_sam_subgrant_subaward_report_number'), table_name='sam_subgrant')
    op.create_index('ix_sam_subgrant_subaward_report_number', 'sam_subgrant', ['subaward_report_number'], unique=False)
    op.drop_index(op.f('ix_sam_subgrant_subaward_report_id'), table_name='sam_subgrant')
    op.create_index('ix_sam_subgrant_subaward_report_id', 'sam_subgrant', ['subaward_report_id'], unique=False)
    op.drop_index(op.f('ix_sam_subcontract_subaward_report_number'), table_name='sam_subcontract')
    op.create_index('ix_sam_subcontract_subaward_report_number', 'sam_subcontract', ['subaward_report_number'], unique=False)
    op.drop_index(op.f('ix_sam_subcontract_subaward_report_id'), table_name='sam_subcontract')
    op.create_index('ix_sam_subcontract_subaward_report_id', 'sam_subcontract', ['subaward_report_id'], unique=False)
    # ### end Alembic commands ###

