"""file_job_unique

Revision ID: 19c18c1545c3
Revises: 6ab05a4cee27
Create Date: 2016-04-12 12:16:16.037000

"""

# revision identifiers, used by Alembic.
revision = '19c18c1545c3'
down_revision = '6ab05a4cee27'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['job_id'])
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'file', type_='unique')
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

def upgrade_validation():
    pass

def downgrade_validation():
    pass

def upgrade_staging():
    pass

def downgrade_staging():
    pass
