"""add_quarter_flag

Revision ID: 1d0ef8e21ddd
Revises: 61dbcecb7ca1
Create Date: 2016-07-11 11:02:23.420000

"""

# revision identifiers, used by Alembic.
revision = '1d0ef8e21ddd'
down_revision = '61dbcecb7ca1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appropriation', sa.Column('is_first_quarter', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('award_financial', sa.Column('is_first_quarter', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('award_financial_assistance', sa.Column('is_first_quarter', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('object_class_program_activity', sa.Column('is_first_quarter', sa.Boolean(), server_default='False', nullable=False))
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_class_program_activity', 'is_first_quarter')
    op.drop_column('award_financial_assistance', 'is_first_quarter')
    op.drop_column('award_financial', 'is_first_quarter')
    op.drop_column('appropriation', 'is_first_quarter')
    ### end Alembic commands ###

