"""Adding parent duns number and name to FABS

Revision ID: 1fabe0bdd48c
Revises: ee7bff1d660c
Create Date: 2018-03-27 15:07:45.721751

"""

# revision identifiers, used by Alembic.
revision = '1fabe0bdd48c'
down_revision = 'ee7bff1d660c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial_assistance', sa.Column('ultimate_parent_legal_enti', sa.Text(), nullable=True))
    op.add_column('award_financial_assistance', sa.Column('ultimate_parent_unique_ide', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('ultimate_parent_legal_enti', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('ultimate_parent_unique_ide', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_award_financial_assistance', 'ultimate_parent_unique_ide')
    op.drop_column('published_award_financial_assistance', 'ultimate_parent_legal_enti')
    op.drop_column('award_financial_assistance', 'ultimate_parent_unique_ide')
    op.drop_column('award_financial_assistance', 'ultimate_parent_legal_enti')
    ### end Alembic commands ###

