"""Remove uniq tas idx

Revision ID: 2ce6d5fd51ce
Revises: 4dc597500734
Create Date: 2016-10-31 21:34:49.058171

"""

# revision identifiers, used by Alembic.
revision = '2ce6d5fd51ce'
down_revision = '4dc597500734'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tas', table_name='tas_lookup')
    op.create_index('ix_tas', 'tas_lookup', ['allocation_transfer_agency', 'agency_identifier', 'beginning_period_of_availability', 'ending_period_of_availability', 'availability_type_code', 'main_account_code', 'sub_account_code'], unique=False)
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tas', table_name='tas_lookup')
    op.create_index('ix_tas', 'tas_lookup', ['allocation_transfer_agency', 'agency_identifier', 'beginning_period_of_availability', 'ending_period_of_availability', 'availability_type_code', 'main_account_code', 'sub_account_code'], unique=True)
    ### end Alembic commands ###

