"""Rename USSGL and PARK columns in (published_)award_financial and (published_)object_class_program_activity tables

Revision ID: 2eebdba5bed7
Revises: de5da602a767
Create Date: 2025-01-08 16:17:14.641298

"""

# revision identifiers, used by Alembic.
revision = '2eebdba5bed7'
down_revision = 'de5da602a767'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE award_financial RENAME COLUMN pa_reporting_key TO program_activity_reporting_key")
    op.execute("ALTER TABLE award_financial RENAME COLUMN ussgl480110_reinstated_del_cpe TO ussgl480110_rein_undel_ord_cpe")
    op.execute("ALTER TABLE award_financial RENAME COLUMN ussgl490110_reinstated_del_cpe TO ussgl490110_rein_deliv_ord_cpe")
    op.execute("ALTER TABLE object_class_program_activity RENAME COLUMN pa_reporting_key TO program_activity_reporting_key")
    op.execute("ALTER TABLE object_class_program_activity RENAME COLUMN ussgl480110_reinstated_del_cpe TO ussgl480110_rein_undel_ord_cpe")
    op.execute("ALTER TABLE object_class_program_activity RENAME COLUMN ussgl490110_reinstated_del_cpe TO ussgl490110_rein_deliv_ord_cpe")
    op.execute("ALTER TABLE published_award_financial RENAME COLUMN pa_reporting_key TO program_activity_reporting_key")
    op.execute("ALTER TABLE published_award_financial RENAME COLUMN ussgl480110_reinstated_del_cpe TO ussgl480110_rein_undel_ord_cpe")
    op.execute("ALTER TABLE published_award_financial RENAME COLUMN ussgl490110_reinstated_del_cpe TO ussgl490110_rein_deliv_ord_cpe")
    op.execute("ALTER TABLE published_object_class_program_activity RENAME COLUMN pa_reporting_key TO program_activity_reporting_key")
    op.execute("ALTER TABLE published_object_class_program_activity RENAME COLUMN ussgl480110_reinstated_del_cpe TO ussgl480110_rein_undel_ord_cpe")
    op.execute("ALTER TABLE published_object_class_program_activity RENAME COLUMN ussgl490110_reinstated_del_cpe TO ussgl490110_rein_deliv_ord_cpe")
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE award_financial RENAME COLUMN program_activity_reporting_key TO pa_reporting_key")
    op.execute("ALTER TABLE award_financial RENAME COLUMN ussgl480110_rein_undel_ord_cpe TO ussgl480110_reinstated_del_cpe")
    op.execute("ALTER TABLE award_financial RENAME COLUMN ussgl490110_rein_deliv_ord_cpe TO ussgl490110_reinstated_del_cpe")
    op.execute("ALTER TABLE object_class_program_activity RENAME COLUMN program_activity_reporting_key TO pa_reporting_key")
    op.execute("ALTER TABLE object_class_program_activity RENAME COLUMN ussgl480110_rein_undel_ord_cpe TO ussgl480110_reinstated_del_cpe")
    op.execute("ALTER TABLE object_class_program_activity RENAME COLUMN ussgl490110_rein_deliv_ord_cpe TO ussgl490110_reinstated_del_cpe")
    op.execute("ALTER TABLE published_award_financial RENAME COLUMN program_activity_reporting_key TO pa_reporting_key")
    op.execute("ALTER TABLE published_award_financial RENAME COLUMN ussgl480110_rein_undel_ord_cpe TO ussgl480110_reinstated_del_cpe")
    op.execute("ALTER TABLE published_award_financial RENAME COLUMN ussgl490110_rein_deliv_ord_cpe TO ussgl490110_reinstated_del_cpe")
    op.execute("ALTER TABLE published_object_class_program_activity RENAME COLUMN program_activity_reporting_key TO pa_reporting_key")
    op.execute("ALTER TABLE published_object_class_program_activity RENAME COLUMN ussgl480110_rein_undel_ord_cpe TO ussgl480110_reinstated_del_cpe")
    op.execute("ALTER TABLE published_object_class_program_activity RENAME COLUMN ussgl490110_rein_deliv_ord_cpe TO ussgl490110_reinstated_del_cpe")
    # ### end Alembic commands ###

