"""upgrading PublishedAwardFinancialAssistance to include is_historical

Revision ID: 32c6c095ebd6
Revises: 5664b0e3e179
Create Date: 2017-05-23 15:49:25.936778

"""

# revision identifiers, used by Alembic.
revision = '32c6c095ebd6'
down_revision = '5664b0e3e179'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_award_financial_assistance', sa.Column('is_historical', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_award_financial_assistance', 'is_historical')
    ### end Alembic commands ###

