""" Adding sam_recipient_unregistered

Revision ID: 39c82fc41ad1
Revises: ee5feab1e6bc
Create Date: 2024-09-03 19:00:46.616556

"""

# revision identifiers, used by Alembic.
revision = '39c82fc41ad1'
down_revision = 'ee5feab1e6bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sam_recipient_unregistered',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sam_recipient_unreg_id', sa.Integer(), nullable=False),
    sa.Column('uei', sa.Text(), nullable=True),
    sa.Column('legal_business_name', sa.Text(), nullable=True),
    sa.Column('address_line_1', sa.Text(), nullable=True),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('zip4', sa.Text(), nullable=True),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('congressional_district', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sam_recipient_unreg_id')
    )
    op.create_index(op.f('ix_sam_recipient_unregistered_uei'), 'sam_recipient_unregistered', ['uei'], unique=False)
    op.create_index(op.f('ix_sam_recipient_unregistered_uei_upper'), 'sam_recipient_unregistered', [text('UPPER(uei)')], unique=False)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sam_recipient_unregistered_uei_upper'), table_name='sam_recipient_unregistered')
    op.drop_index(op.f('ix_sam_recipient_unregistered_uei'), table_name='sam_recipient_unregistered')
    op.drop_table('sam_recipient_unregistered')
    # ### end Alembic commands ###

