"""Added SQS table

Revision ID: 4c25c6cb647b
Revises: 465c323b7bf2
Create Date: 2017-01-22 22:24:55.993561

"""

# revision identifiers, used by Alembic.
revision = '4c25c6cb647b'
down_revision = '465c323b7bf2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqs',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sqs_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sqs_id'),
    sa.UniqueConstraint('job_id', name='uniq_job_id')
    )
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqs')
    ### end Alembic commands ###

