"""add_padded_flags

Revision ID: 4c47eb1e4a5b
Revises: 500f4c889acc
Create Date: 2016-07-01 12:21:18.643000

"""

# revision identifiers, used by Alembic.
revision = '4c47eb1e4a5b'
down_revision = '1d0ef8e21ddd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appropriation', sa.Column('agency_identifier_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('appropriation', sa.Column('allocation_transfer_agency_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('appropriation', sa.Column('main_account_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('appropriation', sa.Column('sub_account_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('award_financial', sa.Column('agency_identifier_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('award_financial', sa.Column('allocation_transfer_agency_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('award_financial', sa.Column('main_account_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('award_financial', sa.Column('program_activity_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('award_financial', sa.Column('sub_account_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('object_class_program_activity', sa.Column('agency_identifier_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('object_class_program_activity', sa.Column('allocation_transfer_agency_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('object_class_program_activity', sa.Column('main_account_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('object_class_program_activity', sa.Column('program_activity_code_padded', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('object_class_program_activity', sa.Column('sub_account_code_padded', sa.Boolean(), server_default='False', nullable=True))
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_class_program_activity', 'sub_account_code_padded')
    op.drop_column('object_class_program_activity', 'program_activity_code_padded')
    op.drop_column('object_class_program_activity', 'main_account_code_padded')
    op.drop_column('object_class_program_activity', 'allocation_transfer_agency_padded')
    op.drop_column('object_class_program_activity', 'agency_identifier_padded')
    op.drop_column('award_financial', 'sub_account_code_padded')
    op.drop_column('award_financial', 'program_activity_code_padded')
    op.drop_column('award_financial', 'main_account_code_padded')
    op.drop_column('award_financial', 'allocation_transfer_agency_padded')
    op.drop_column('award_financial', 'agency_identifier_padded')
    op.drop_column('appropriation', 'sub_account_code_padded')
    op.drop_column('appropriation', 'main_account_code_padded')
    op.drop_column('appropriation', 'allocation_transfer_agency_padded')
    op.drop_column('appropriation', 'agency_identifier_padded')
    ### end Alembic commands ###

