"""Create fpds_update table

Revision ID: 4d0c120e2de4
Revises: 1d0ee4fef616
Create Date: 2017-05-10 12:19:19.292109

"""

# revision identifiers, used by Alembic.
revision = '4d0c120e2de4'
down_revision = '1d0ee4fef616'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpds_update',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('update_date')
    )
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fpds_update')
    ### end Alembic commands ###

