"""add FREC to user model

Revision ID: 4e3949db5b34
Revises: da2e50d423ff
Create Date: 2017-07-06 10:29:51.576140

"""

# revision identifiers, used by Alembic.
revision = '4e3949db5b34'
down_revision = 'da2e50d423ff'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_affiliation', sa.Column('frec_id', sa.Integer(), nullable=False))
    op.create_foreign_key('user_affiliation_frec_fk', 'user_affiliation', 'frec', ['frec_id'], ['frec_id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_affiliation_frec_fk', 'user_affiliation', type_='foreignkey')
    op.drop_column('user_affiliation', 'frec_id')
    ### end Alembic commands ###

