"""Add county columns to DetachedAwardProcurement table

Revision ID: 508055d972f1
Revises: 0974293b64c3
Create Date: 2017-12-07 10:51:09.340079

"""

# revision identifiers, used by Alembic.
revision = '508055d972f1'
down_revision = '0974293b64c3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_procurement', sa.Column('legal_entity_county_code', sa.Text(), nullable=True))
    op.add_column('detached_award_procurement', sa.Column('legal_entity_county_name', sa.Text(), nullable=True))
    op.add_column('detached_award_procurement', sa.Column('place_of_perform_county_co', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detached_award_procurement', 'place_of_perform_county_co')
    op.drop_column('detached_award_procurement', 'legal_entity_county_name')
    op.drop_column('detached_award_procurement', 'legal_entity_county_code')
    ### end Alembic commands ###

