"""Create latest_certify_date view

Revision ID: 52d660551213
Revises: 03257ae6000f
Create Date: 2017-11-07 12:02:56.753149

"""

# revision identifiers, used by Alembic.
revision = '52d660551213'
down_revision = '03257ae6000f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
                CREATE OR REPLACE VIEW latest_certify_date_view (submission_id, certified_on) AS
                SELECT submission_id, max(created_at) as certified_on
                FROM certify_history
                GROUP BY submission_id
            """)
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW latest_certify_date_view")
    ### end Alembic commands ###

