"""Add ussgl480210 and ussgl497210 to Files B and C

Revision ID: 53d94d9d27ca
Revises: ac14a84e80a3
Create Date: 2025-08-26 15:50:59.796667

"""

# revision identifiers, used by Alembic.
revision = '53d94d9d27ca'
down_revision = 'ac14a84e80a3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial', sa.Column('ussgl480210_rein_undel_obs_cpe', sa.Numeric(), nullable=True))
    op.add_column('award_financial', sa.Column('ussgl497210_down_adj_refun_cpe', sa.Numeric(), nullable=True))
    op.add_column('object_class_program_activity', sa.Column('ussgl480210_rein_undel_obs_cpe', sa.Numeric(), nullable=True))
    op.add_column('object_class_program_activity', sa.Column('ussgl497210_down_adj_refun_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_award_financial', sa.Column('ussgl480210_rein_undel_obs_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_award_financial', sa.Column('ussgl497210_down_adj_refun_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_object_class_program_activity', sa.Column('ussgl480210_rein_undel_obs_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_object_class_program_activity', sa.Column('ussgl497210_down_adj_refun_cpe', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_object_class_program_activity', 'ussgl497210_down_adj_refun_cpe')
    op.drop_column('published_object_class_program_activity', 'ussgl480210_rein_undel_obs_cpe')
    op.drop_column('published_award_financial', 'ussgl497210_down_adj_refun_cpe')
    op.drop_column('published_award_financial', 'ussgl480210_rein_undel_obs_cpe')
    op.drop_column('object_class_program_activity', 'ussgl497210_down_adj_refun_cpe')
    op.drop_column('object_class_program_activity', 'ussgl480210_rein_undel_obs_cpe')
    op.drop_column('award_financial', 'ussgl497210_down_adj_refun_cpe')
    op.drop_column('award_financial', 'ussgl480210_rein_undel_obs_cpe')
    # ### end Alembic commands ###

