"""duns_address_business_types

Revision ID: 5d4f4bb0d979
Revises: 7ffc95637ee4
Create Date: 2018-07-09 19:31:41.829153

"""

# revision identifiers, used by Alembic.
revision = '5d4f4bb0d979'
down_revision = '7ffc95637ee4' #  UPDATE ME WHEN INTEGRATED
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duns', sa.Column('address_line_1', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('address_line_2', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('business_types_raw', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('congressional_district', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('country_code', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('zip', sa.Text(), nullable=True))
    op.add_column('duns', sa.Column('zip4', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duns', 'zip4')
    op.drop_column('duns', 'zip')
    op.drop_column('duns', 'state')
    op.drop_column('duns', 'country_code')
    op.drop_column('duns', 'congressional_district')
    op.drop_column('duns', 'city')
    op.drop_column('duns', 'business_types_raw')
    op.drop_column('duns', 'address_line_2')
    op.drop_column('duns', 'address_line_1')
    ### end Alembic commands ###

