"""Adding display_tas to SF133

Revision ID: 5e6d944e37be
Revises: de5e3fa1d2d2
Create Date: 2019-10-29 20:01:54.839082

"""

# revision identifiers, used by Alembic.
revision = '5e6d944e37be'
down_revision = 'de5e3fa1d2d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_133', sa.Column('display_tas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sf_133', 'display_tas')
    # ### end Alembic commands ###

