"""Adding indexing to created_at for published_award_financial_assistance and updated_at for detached_award_procurement

Revision ID: 6017df2a5790
Revises: bcdf1134f0df
Create Date: 2017-10-03 15:53:21.032478

"""

# revision identifiers, used by Alembic.
revision = '6017df2a5790'
down_revision = 'bcdf1134f0df'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_published_award_financial_assistance_created_at'), 'published_award_financial_assistance', ['created_at'], unique=False)
    op.create_index(op.f('ix_detached_award_procurement_updated_at'), 'detached_award_procurement', ['updated_at'], unique=False)
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###op.drop_index(op.f('ix_published_award_financial_assistance_place_of_performance_congr'), table_name='published_award_financial_assistance')
    op.drop_index(op.f('ix_detached_award_procurement_updated_at'), table_name='detached_award_procurement')
    op.drop_index(op.f('ix_published_award_financial_assistance_created_at'), table_name='published_award_financial_assistance')
    ### end Alembic commands ###

