"""Adding expanded columns to sf_133 table

Revision ID: 61ffc5e0f2af
Revises: 90e58540d4da
Create Date: 2026-02-09 17:28:34.569129

"""

# revision identifiers, used by Alembic.
revision = '61ffc5e0f2af'
down_revision = '90e58540d4da'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_133', sa.Column('bea_category', sa.Text(), nullable=True))
    op.add_column('sf_133', sa.Column('budget_object_class', sa.Text(), nullable=True))
    op.add_column('sf_133', sa.Column('by_direct_reimbursable_fun', sa.Text(), nullable=True))
    op.add_column('sf_133', sa.Column('prior_year_adjustment', sa.Text(), nullable=True))
    op.add_column('sf_133', sa.Column('program_activity_reporting_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sf_133', 'program_activity_reporting_key')
    op.drop_column('sf_133', 'prior_year_adjustment')
    op.drop_column('sf_133', 'by_direct_reimbursable_fun')
    op.drop_column('sf_133', 'budget_object_class')
    op.drop_column('sf_133', 'bea_category')
    # ### end Alembic commands ###

