"""change_row_to_row_number

Revision ID: 652047b81988
Revises: c084b5b1a178
Create Date: 2016-06-17 10:18:19.384867

"""

# revision identifiers, used by Alembic.
revision = '652047b81988'
down_revision = 'c084b5b1a178'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appropriation', sa.Column('row_number', sa.Integer(), nullable=False))
    op.drop_column('appropriation', 'row')
    op.add_column('award_financial', sa.Column('row_number', sa.Integer(), nullable=False))
    op.drop_column('award_financial', 'row')
    op.add_column('award_financial_assistance', sa.Column('row_number', sa.Integer(), nullable=False))
    op.drop_column('award_financial_assistance', 'row')
    op.add_column('object_class_program_activity', sa.Column('row_number', sa.Integer(), nullable=False))
    op.drop_column('object_class_program_activity', 'row')
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_class_program_activity', sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('object_class_program_activity', 'row_number')
    op.add_column('award_financial_assistance', sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('award_financial_assistance', 'row_number')
    op.add_column('award_financial', sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('award_financial', 'row_number')
    op.add_column('appropriation', sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('appropriation', 'row_number')
    ### end Alembic commands ###

