"""Adding state_code column to zip_city table

Revision ID: 7464131caaa8
Revises: 3f0b57c92b41
Create Date: 2023-04-06 11:23:28.830415

"""

# revision identifiers, used by Alembic.
revision = '7464131caaa8'
down_revision = '3f0b57c92b41'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zip_city', sa.Column('state_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zip_city', 'state_code')
    # ### end Alembic commands ###

