"""Change grant_office to financial_assistance_office in Office table

Revision ID: 7dd3f4b007e5
Revises: 1fb19acc7d64
Create Date: 2019-04-18 11:49:04.015664

"""

# revision identifiers, used by Alembic.
revision = '7dd3f4b007e5'
down_revision = '1fb19acc7d64'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE office RENAME COLUMN grant_office TO financial_assistance_office")
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE office RENAME COLUMN financial_assistance_office TO grant_office")
    # ### end Alembic commands ###

