"""addFileData

Revision ID: 7ee5e2cfb9cd
Revises: b8cf7fa342bb
Create Date: 2016-04-06 09:30:37.743000

"""

# revision identifiers, used by Alembic.
revision = '7ee5e2cfb9cd'
down_revision = 'b8cf7fa342bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_status', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('job_status', sa.Column('number_of_rows', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_status', 'number_of_rows')
    op.drop_column('job_status', 'file_size')
    ### end Alembic commands ###

def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

