"""Creating program_activity_park table

Revision ID: 80826794d8c5
Revises: ee5feab1e6bc
Create Date: 2024-09-03 12:56:51.320874

"""

# revision identifiers, used by Alembic.
revision = '80826794d8c5'
down_revision = 'ee5feab1e6bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_activity_park',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('program_activity_park_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Text(), nullable=False),
    sa.Column('allocation_transfer_id', sa.Text(), nullable=True),
    sa.Column('main_account_number', sa.Text(), nullable=False),
    sa.Column('sub_account_number', sa.Text(), nullable=True),
    sa.Column('park_code', sa.Text(), nullable=False),
    sa.Column('park_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('program_activity_park_id')
    )
    op.create_index('ix_pap_tas_park', 'program_activity_park', ['fiscal_year', 'period', 'agency_id', 'allocation_transfer_id', 'main_account_number', 'sub_account_number', 'park_code'], unique=True)
    op.create_index(op.f('ix_program_activity_park_agency_id'), 'program_activity_park', ['agency_id'], unique=False)
    op.create_index(op.f('ix_program_activity_park_allocation_transfer_id'), 'program_activity_park', ['allocation_transfer_id'], unique=False)
    op.create_index(op.f('ix_program_activity_park_fiscal_year'), 'program_activity_park', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_program_activity_park_main_account_number'), 'program_activity_park', ['main_account_number'], unique=False)
    op.create_index(op.f('ix_program_activity_park_park_code'), 'program_activity_park', ['park_code'], unique=False)
    op.create_index(op.f('ix_program_activity_park_period'), 'program_activity_park', ['period'], unique=False)
    op.create_index(op.f('ix_program_activity_park_sub_account_number'), 'program_activity_park', ['sub_account_number'], unique=False)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_activity_park_sub_account_number'), table_name='program_activity_park')
    op.drop_index(op.f('ix_program_activity_park_period'), table_name='program_activity_park')
    op.drop_index(op.f('ix_program_activity_park_park_code'), table_name='program_activity_park')
    op.drop_index(op.f('ix_program_activity_park_main_account_number'), table_name='program_activity_park')
    op.drop_index(op.f('ix_program_activity_park_fiscal_year'), table_name='program_activity_park')
    op.drop_index(op.f('ix_program_activity_park_allocation_transfer_id'), table_name='program_activity_park')
    op.drop_index(op.f('ix_program_activity_park_agency_id'), table_name='program_activity_park')
    op.drop_index('ix_pap_tas_park', table_name='program_activity_park')
    op.drop_table('program_activity_park')
    # ### end Alembic commands ###

