"""changing date to datetime in externaldataloadddate

Revision ID: 816e7367bbc9
Revises: 7d2d17f4e86a
Create Date: 2018-06-13 19:30:02.562857

"""

# revision identifiers, used by Alembic.
revision = '816e7367bbc9'
down_revision = '7d2d17f4e86a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_data_load_date', 'last_load_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_data_load_date', 'last_load_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###

