"""add_cgac

Revision ID: 849e1ac35007
Revises: 3a79d7a4d1c1
Create Date: 2016-05-27 14:12:36.252000

"""

# revision identifiers, used by Alembic.
revision = '849e1ac35007'
down_revision = '3a79d7a4d1c1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cgac',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cgac_id', sa.Integer(), nullable=False),
    sa.Column('cgac_code', sa.Text(), nullable=False),
    sa.Column('agency_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cgac_id')
    )
    op.create_index(op.f('ix_cgac_cgac_code'), 'cgac', ['cgac_code'], unique=True)
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cgac_cgac_code'), table_name='cgac')
    op.drop_table('cgac')
    ### end Alembic commands ###


def upgrade_staging():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_staging():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

