"""Adding PARK and PYA to object_class_program_activity and award_financial tables

Revision ID: 86316f32dad9
Revises: 39c82fc41ad1
Create Date: 2024-09-19 11:50:31.607645

"""

# revision identifiers, used by Alembic.
revision = '86316f32dad9'
down_revision = '39c82fc41ad1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial', sa.Column('pa_reporting_key', sa.Text(), nullable=True))
    op.add_column('award_financial', sa.Column('prior_year_adjustment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_award_financial_pa_reporting_key'), 'award_financial', ['pa_reporting_key'], unique=False)
    op.create_index(op.f('ix_award_financial_prior_year_adjustment'), 'award_financial', ['prior_year_adjustment'], unique=False)
    op.add_column('object_class_program_activity', sa.Column('pa_reporting_key', sa.Text(), nullable=True))
    op.add_column('object_class_program_activity', sa.Column('prior_year_adjustment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_object_class_program_activity_pa_reporting_key'), 'object_class_program_activity', ['pa_reporting_key'], unique=False)
    op.create_index(op.f('ix_object_class_program_activity_prior_year_adjustment'), 'object_class_program_activity', ['prior_year_adjustment'], unique=False)
    op.add_column('published_award_financial', sa.Column('pa_reporting_key', sa.Text(), nullable=True))
    op.add_column('published_award_financial', sa.Column('prior_year_adjustment', sa.Text(), nullable=True))
    op.add_column('published_object_class_program_activity', sa.Column('pa_reporting_key', sa.Text(), nullable=True))
    op.add_column('published_object_class_program_activity', sa.Column('prior_year_adjustment', sa.Text(), nullable=True))
    op.drop_constraint('sam_recipient_unregistered_uei_key', 'sam_recipient_unregistered', type_='unique')
    op.drop_index('ix_sam_recipient_unregistered_uei', table_name='sam_recipient_unregistered')
    op.create_index(op.f('ix_sam_recipient_unregistered_uei'), 'sam_recipient_unregistered', ['uei'], unique=True)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sam_recipient_unregistered_uei'), table_name='sam_recipient_unregistered')
    op.create_index('ix_sam_recipient_unregistered_uei', 'sam_recipient_unregistered', ['uei'], unique=False)
    op.create_unique_constraint('sam_recipient_unregistered_uei_key', 'sam_recipient_unregistered', ['uei'])
    op.drop_column('published_object_class_program_activity', 'prior_year_adjustment')
    op.drop_column('published_object_class_program_activity', 'pa_reporting_key')
    op.drop_column('published_award_financial', 'prior_year_adjustment')
    op.drop_column('published_award_financial', 'pa_reporting_key')
    op.drop_index(op.f('ix_object_class_program_activity_prior_year_adjustment'), table_name='object_class_program_activity')
    op.drop_index(op.f('ix_object_class_program_activity_pa_reporting_key'), table_name='object_class_program_activity')
    op.drop_column('object_class_program_activity', 'prior_year_adjustment')
    op.drop_column('object_class_program_activity', 'pa_reporting_key')
    op.drop_index(op.f('ix_award_financial_prior_year_adjustment'), table_name='award_financial')
    op.drop_index(op.f('ix_award_financial_pa_reporting_key'), table_name='award_financial')
    op.drop_column('award_financial', 'prior_year_adjustment')
    op.drop_column('award_financial', 'pa_reporting_key')
    # ### end Alembic commands ###

