"""Adding awarding office name

Revision ID: 8b8b204f1b20
Revises: 539307ecadea
Create Date: 2017-09-20 13:33:38.551181

"""

# revision identifiers, used by Alembic.
revision = '8b8b204f1b20'
down_revision = '539307ecadea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_financial_assistance', sa.Column('awarding_office_name', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detached_award_financial_assistance', 'awarding_office_name')
    ### end Alembic commands ###

