"""Adding submission comment

Revision ID: 8b8e9fe94b4a
Revises: c0be99167fbf
Create Date: 2021-01-13 19:26:51.112780

"""

# revision identifiers, used by Alembic.
revision = '8b8e9fe94b4a'
down_revision = 'c0be99167fbf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certified_comment', sa.Column('submission_comment', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('certified_comment', 'file_type_id', existing_type=sa.INTEGER(), nullable=True)
    op.add_column('comment', sa.Column('submission_comment', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('comment', 'file_type_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'file_type_id', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('comment', 'submission_comment')
    op.alter_column('certified_comment', 'file_type_id', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('certified_comment', 'submission_comment')
    # ### end Alembic commands ###

