"""Adding test_submission flag to submission

Revision ID: 9472a2385e99
Revises: feaf7887d023
Create Date: 2020-05-26 17:06:06.040725

"""

# revision identifiers, used by Alembic.
revision = '9472a2385e99'
down_revision = 'feaf7887d023'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('test_submission', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'test_submission')
    # ### end Alembic commands ###

