"""add_sql_rule_table

Revision ID: 94f7bda375e2
Revises: a21dbed90f9f
Create Date: 2016-06-13 13:29:11.441319

"""

# revision identifiers, used by Alembic.
revision = '94f7bda375e2'
down_revision = 'a21dbed90f9f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    pass


def downgrade_error_data():
    pass


def upgrade_job_tracker():
    pass


def downgrade_job_tracker():
    pass


def upgrade_user_manager():
    pass


def downgrade_user_manager():
    pass


def upgrade_validation():
    op.create_table('rule_severity',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rule_severity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('rule_severity_id')
    )
    op.create_table('rule_sql',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rule_sql_id', sa.Integer(), nullable=False),
    sa.Column('rule_sql', sa.Text(), nullable=False),
    sa.Column('rule_label', sa.Text(), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('rule_error_message', sa.Text(), nullable=False),
    sa.Column('rule_cross_file_flag', sa.Boolean(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('rule_severity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_type.file_id'], ),
    sa.ForeignKeyConstraint(['rule_severity_id'], ['rule_severity.rule_severity_id'], ),
    sa.PrimaryKeyConstraint('rule_sql_id')
    )


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_sql')
    op.drop_table('rule_severity')
    ### end Alembic commands ###


def upgrade_staging():
    pass


def downgrade_staging():
    pass

