"""Fix detached_award_procurement table and add more descriptions

Revision ID: 950b7075ebc3
Revises: 4d0c120e2de4
Create Date: 2017-05-11 10:26:06.381010

"""

# revision identifiers, used by Alembic.
revision = '950b7075ebc3'
down_revision = '4d0c120e2de4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_procurement', sa.Column('last_modified', sa.Text(), nullable=True))
    op.add_column('detached_award_procurement', sa.Column('place_of_perform_county_na', sa.Text(), nullable=True))
    op.add_column('detached_award_procurement', sa.Column('referenced_idv_agency_desc', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detached_award_procurement', 'referenced_idv_agency_desc')
    op.drop_column('detached_award_procurement', 'place_of_perform_county_na')
    op.drop_column('detached_award_procurement', 'last_modified')
    ### end Alembic commands ###

