"""remove is_active from user

Revision ID: 98ad59ff4711
Revises: d1f40bcf04b0
Create Date: 2016-12-22 09:51:27.399247

"""

# revision identifiers, used by Alembic.
revision = '98ad59ff4711'
down_revision = 'd1f40bcf04b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    ### end Alembic commands ###

