""" Rename CFDA to AssistanceListing

Revision ID: 9a5e71474232
Revises: 1b55916099f4
Create Date: 2024-01-17 20:01:34.004322

"""

# revision identifiers, used by Alembic.
revision = '9a5e71474232'
down_revision = '1b55916099f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    # CFDAProgram -> AssistanceListing
    op.alter_column('cfda_program', 'cfda_program_id', new_column_name='assistance_listing_id')
    op.execute('ALTER SEQUENCE cfda_program_cfda_program_id_seq RENAME TO assistance_listing_assistance_listing_id_seq')
    op.execute('ALTER INDEX cfda_program_pkey RENAME TO assistance_listing_pkey')
    op.execute('ALTER INDEX ix_cfda_program_archived_date RENAME TO ix_assistance_listing_archived_date')
    op.execute('ALTER INDEX ix_cfda_program_published_date RENAME TO ix_assistance_listing_published_date')
    op.execute('ALTER INDEX ix_cfda_program_program_number RENAME TO ix_assistance_listing_program_number')
    op.rename_table('cfda_program', 'assistance_listing')

    # AwardFinancialAssistance
    op.alter_column('award_financial_assistance', 'cfda_number', new_column_name='assistance_listing_number')
    op.alter_column('award_financial_assistance', 'cfda_title', new_column_name='assistance_listing_title')
    op.execute('ALTER INDEX ix_award_financial_assistance_cfda_number RENAME TO ix_award_financial_assistance_assistance_listing_number')

    # PublishedAwardFinancialAssistance
    op.alter_column('published_award_financial_assistance', 'cfda_number', new_column_name='assistance_listing_number')
    op.alter_column('published_award_financial_assistance', 'cfda_title', new_column_name='assistance_listing_title')

    # FABS
    op.alter_column('fabs', 'cfda_number', new_column_name='assistance_listing_number')
    op.execute('ALTER INDEX ix_fabs_cfda_number RENAME TO ix_fabs_assistance_listing_number')

    # PublishedFABS
    op.alter_column('published_fabs', 'cfda_number', new_column_name='assistance_listing_number')
    op.alter_column('published_fabs', 'cfda_title', new_column_name='assistance_listing_title')
    op.execute('ALTER INDEX ix_published_fabs_cfda_number RENAME TO ix_published_fabs_assistance_listing_number')

    # FSRSGrant
    op.alter_column('fsrs_grant', 'cfda_numbers', new_column_name='assistance_listing_numbers')

    # FSRSSubgrant
    op.alter_column('fsrs_subgrant', 'cfda_numbers', new_column_name='assistance_listing_numbers')

    # Subaward
    op.alter_column('subaward', 'cfda_numbers', new_column_name='assistance_listing_numbers')
    op.alter_column('subaward', 'cfda_titles', new_column_name='assistance_listing_titles')
    op.alter_column('subaward', 'sub_cfda_numbers', new_column_name='sub_assistance_listing_numbers')

    # FundingOpportunity
    op.alter_column('funding_opportunity', 'cfda_numbers', new_column_name='assistance_listing_numbers')

    # Rename CFDA PSQL functions
    op.execute('ALTER FUNCTION cfda_num(TEXT) RENAME TO assistance_listing_num')
    op.execute('ALTER FUNCTION cfda_word(TEXT) RENAME TO assistance_listing_word')
    op.execute('ALTER FUNCTION cfda_num_loop(TEXT) RENAME TO assistance_listing_num_loop')
    op.execute('ALTER FUNCTION cfda_word_loop(TEXT) RENAME TO assistance_listing_word_loop')
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    # AssistanceListing -> CFDAProgram
    op.alter_column('assistance_listing', 'assistance_listing_id', new_column_name='cfda_program_id')
    op.execute('ALTER SEQUENCE assistance_listing_assistance_listing_id_seq RENAME TO cfda_program_cfda_program_id_seq')
    op.execute('ALTER INDEX assistance_listing_pkey RENAME TO cfda_program_pkey')
    op.execute('ALTER INDEX ix_assistance_listing_archived_date RENAME TO ix_cfda_program_archived_date')
    op.execute('ALTER INDEX ix_assistance_listing_published_date RENAME TO ix_cfda_program_published_date')
    op.execute('ALTER INDEX ix_assistance_listing_program_number RENAME TO ix_cfda_program_program_number')
    op.rename_table('assistance_listing', 'cfda_program')

    # AwardFinancialAssistance
    op.alter_column('award_financial_assistance', 'assistance_listing_number', new_column_name='cfda_number')
    op.alter_column('award_financial_assistance', 'assistance_listing_title', new_column_name='cfda_title')
    op.execute('ALTER INDEX ix_award_financial_assistance_assistance_listing_number RENAME TO ix_award_financial_assistance_cfda_number')

    # PublishedAwardFinancialAssistance
    op.alter_column('published_award_financial_assistance', 'assistance_listing_number', new_column_name='cfda_number')
    op.alter_column('published_award_financial_assistance', 'assistance_listing_title', new_column_name='cfda_title')

    # FABS
    op.alter_column('fabs', 'assistance_listing_number', new_column_name='cfda_number')
    op.execute('ALTER INDEX ix_fabs_assistance_listing_number RENAME TO ix_fabs_cfda_number')

    # PublishedFABS
    op.alter_column('published_fabs', 'assistance_listing_number', new_column_name='cfda_number')
    op.alter_column('published_fabs', 'assistance_listing_title', new_column_name='cfda_title')
    op.execute('ALTER INDEX ix_published_fabs_assistance_listing_number RENAME TO ix_published_fabs_cfda_number')

    # FSRSGrant
    op.alter_column('fsrs_grant', 'assistance_listing_numbers', new_column_name='cfda_numbers')

    # FSRSSubgrant
    op.alter_column('fsrs_subgrant', 'assistance_listing_numbers', new_column_name='cfda_numbers')

    # Subaward
    op.alter_column('subaward', 'assistance_listing_numbers', new_column_name='cfda_numbers')
    op.alter_column('subaward', 'assistance_listing_titles', new_column_name='cfda_titles')
    op.alter_column('subaward', 'sub_assistance_listing_numbers', new_column_name='sub_cfda_numbers')

    # FundingOpportunity
    op.alter_column('funding_opportunity', 'assistance_listing_numbers', new_column_name='cfda_numbers')

    # Rename CFDA PSQL functions
    op.execute('ALTER FUNCTION assistance_listing_num(TEXT) RENAME TO cfda_num')
    op.execute('ALTER FUNCTION assistance_listing_word(TEXT) RENAME TO cfda_word')
    op.execute('ALTER FUNCTION assistance_listing_num_loop(TEXT) RENAME TO cfda_num_loop')
    op.execute('ALTER FUNCTION assistance_listing_word_loop(TEXT) RENAME TO cfda_word_loop')
    # ### end Alembic commands ###

