"""Add total_funding_amount to published_award_financial_assistance table

Revision ID: 9eb921552907
Revises: 20b5109967bf
Create Date: 2017-04-20 10:38:25.607246

"""

# revision identifiers, used by Alembic.
revision = '9eb921552907'
down_revision = '20b5109967bf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_award_financial_assistance', sa.Column('total_funding_amount', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_award_financial_assistance', 'total_funding_amount')
    ### end Alembic commands ###

