"""Adding Entity Structure to DUNS

Revision ID: a9d1268b8b2a
Revises: 4bbc47f2b48d
Create Date: 2018-11-19 22:04:17.701916

"""

# revision identifiers, used by Alembic.
revision = 'a9d1268b8b2a'
down_revision = '4bbc47f2b48d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duns', sa.Column('entity_structure', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duns', 'entity_structure')
    # ### end Alembic commands ###

