"""Create county_code table

Revision ID: aa10ae595d3e
Revises: ea02faf8bc7a
Create Date: 2017-06-20 12:21:46.165312

"""

# revision identifiers, used by Alembic.
revision = 'aa10ae595d3e'
down_revision = 'ea02faf8bc7a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county_code',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('county_code_id', sa.Integer(), nullable=False),
        sa.Column('county_number', sa.Text(), nullable=True),
        sa.Column('county_name', sa.Text(), nullable=True),
        sa.Column('state_code', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('county_code_id')
    )
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('county_code')
    ### end Alembic commands ###

