"""Add idv_delete_key column to detached_award_procurement

Revision ID: ab4eac43f605
Revises: a9b778fd5181
Create Date: 2018-09-04 10:49:34.468602

"""

# revision identifiers, used by Alembic.
revision = 'ab4eac43f605'
down_revision = 'a9b778fd5181'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_procurement', sa.Column('idv_delete_key', sa.Text(), nullable=True))
    op.create_index(op.f('ix_detached_award_procurement_idv_delete_key'), 'detached_award_procurement', ['idv_delete_key'], unique=False)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detached_award_procurement_idv_delete_key'), table_name='detached_award_procurement')
    op.drop_column('detached_award_procurement', 'idv_delete_key')
    # ### end Alembic commands ###

