"""Add index to pulled_from column in detached_award_procurement

Revision ID: ab4eac43f605
Revises: a9b778fd5181
Create Date: 2018-09-04 10:49:34.468602

"""

# revision identifiers, used by Alembic.
revision = 'ab4eac43f605'
down_revision = '67feaf4d50b8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_detached_award_procurement_pulled_from'), 'detached_award_procurement', ['pulled_from'], unique=False)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detached_award_procurement_pulled_from'), table_name='detached_award_procurement')
    # ### end Alembic commands ###

