"""add activation and expiration date columns to executive_compensation table

Revision ID: acdfe80a85d4
Revises: 52b3c1a122ce
Create Date: 2017-06-21 13:04:53.946759

"""

# revision identifiers, used by Alembic.
revision = 'acdfe80a85d4'
down_revision = '52b3c1a122ce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_compensation', sa.Column('activation_date', sa.Date(), nullable=True))
    op.add_column('executive_compensation', sa.Column('expiration_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_compensation', 'expiration_date')
    op.drop_column('executive_compensation', 'activation_date')
    ### end Alembic commands ###

