"""Unique constraints for rule_setting and user

Revision ID: ad583d48ce5e
Revises: 9907f0bc45f4
Create Date: 2026-09-09 14:47:32.354008

"""

# revision identifiers, used by Alembic.
revision = 'ad583d48ce5e'
down_revision = '9907f0bc45f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rule_setting_code_file_label_unique', 'rule_settings', ['agency_code', 'file_id', 'rule_label', sa.func.coalesce(sa.column("target_file_id"), 0)], unique=True)
    op.create_index('ix_users_upper_email_unique', 'users', [sa.text("UPPER(email)")], unique=True)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_upper_email_unique', table_name='users')
    op.drop_index('ix_rule_setting_code_file_label_unique', table_name='rule_settings')
    # ### end Alembic commands ###

