"""update_sf133_tas_cols

Revision ID: b64a9cc871cc
Revises: de141f790505
Create Date: 2016-06-27 17:17:28.426480

"""

# revision identifiers, used by Alembic.
revision = 'b64a9cc871cc'
down_revision = 'de141f790505'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_data_broker():
    pass

def downgrade_data_broker():
    pass

def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_validation():
    op.alter_column('sf_133', 'subaccountcode', new_column_name='sub_account_code')
    op.alter_column('sf_133', 'mainaccountcode', new_column_name='main_account_code')
    op.alter_column('sf_133', 'endingperiodofavailability', new_column_name='ending_period_of_availabil')
    op.alter_column('sf_133', 'beginningperiodofavailability', new_column_name='beginning_period_of_availa')
    op.alter_column('sf_133', 'availabilitytypecode', new_column_name='availability_type_code')
    op.alter_column('sf_133', 'allocationtransferagencyidentifier', new_column_name='allocation_transfer_agency')
    op.alter_column('sf_133', 'agencyidentifier', new_column_name='agency_identifier')


def downgrade_validation():
    op.alter_column('sf_133', 'sub_account_code', new_column_name='subaccountcode', )
    op.alter_column('sf_133', 'main_account_code', new_column_name='mainaccountcode',)
    op.alter_column('sf_133', 'ending_period_of_availabil', new_column_name='endingperiodofavailability', )
    op.alter_column('sf_133', 'beginning_period_of_availa', new_column_name='beginningperiodofavailability', )
    op.alter_column('sf_133', 'availability_type_code', new_column_name='availabilitytypecode',)
    op.alter_column('sf_133', 'allocation_transfer_agency', new_column_name='allocationtransferagencyidentifier', )
    op.alter_column('sf_133', 'agency_identifier', new_column_name='agencyidentifier', )

