"""Adding upper fabs awarding subtier code index

Revision ID: b998d20b46e6
Revises: d7e1a2433dca
Create Date: 2019-09-06 15:51:01.640884

"""

# revision identifiers, used by Alembic.
revision = 'b998d20b46e6'
down_revision = 'd7e1a2433dca'
branch_labels = None
depends_on = None

from alembic import op
from sqlalchemy import text

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pafa_awarding_subtier_c_upper', 'published_award_financial_assistance',
                    [text('UPPER(awarding_sub_tier_agency_c)')], unique=False)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pafa_awarding_subtier_c_upper', table_name='published_award_financial_assistance')
    # ### end Alembic commands ###

