"""Add descriptions to (Published)AwardFinancialAssistance

Revision ID: c4d42e86c655
Revises: 668d9fa93acb
Create Date: 2018-04-04 11:00:18.103961

"""

# revision identifiers, used by Alembic.
revision = 'c4d42e86c655'
down_revision = '668d9fa93acb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial_assistance', sa.Column('action_type_description', sa.Text(), nullable=True))
    op.add_column('award_financial_assistance', sa.Column('assistance_type_desc', sa.Text(), nullable=True))
    op.add_column('award_financial_assistance', sa.Column('business_funds_ind_desc', sa.Text(), nullable=True))
    op.add_column('award_financial_assistance', sa.Column('business_types_desc', sa.Text(), nullable=True))
    op.add_column('award_financial_assistance', sa.Column('correction_delete_ind_desc', sa.Text(), nullable=True))
    op.add_column('award_financial_assistance', sa.Column('record_type_description', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('action_type_description', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('assistance_type_desc', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('business_funds_ind_desc', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('business_types_desc', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('correction_delete_ind_desc', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('record_type_description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_award_financial_assistance', 'record_type_description')
    op.drop_column('published_award_financial_assistance', 'correction_delete_ind_desc')
    op.drop_column('published_award_financial_assistance', 'business_types_desc')
    op.drop_column('published_award_financial_assistance', 'business_funds_ind_desc')
    op.drop_column('published_award_financial_assistance', 'assistance_type_desc')
    op.drop_column('published_award_financial_assistance', 'action_type_description')
    op.drop_column('award_financial_assistance', 'record_type_description')
    op.drop_column('award_financial_assistance', 'correction_delete_ind_desc')
    op.drop_column('award_financial_assistance', 'business_types_desc')
    op.drop_column('award_financial_assistance', 'business_funds_ind_desc')
    op.drop_column('award_financial_assistance', 'assistance_type_desc')
    op.drop_column('award_financial_assistance', 'action_type_description')
    ### end Alembic commands ###

