"""Add element_numbers column to file_generation table

Revision ID: c5449ab3577f
Revises: 6e3be68b87ae
Create Date: 2020-08-06 15:38:13.802389

"""

# revision identifiers, used by Alembic.
revision = 'c5449ab3577f'
down_revision = '0d570ef8292d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_generation', sa.Column('element_numbers', sa.Boolean(), server_default="False", nullable=False))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_generation', 'element_numbers')
    # ### end Alembic commands ###

