"""duns_dba_name

Revision ID: c7da6e4c9b8a
Revises: 089e94d3dc03
Create Date: 2018-08-16 15:58:26.564095

"""

# revision identifiers, used by Alembic.
revision = 'c7da6e4c9b8a'
down_revision = '089e94d3dc03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duns', sa.Column('dba_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duns', 'dba_name')
    # ### end Alembic commands ###

