"""add last login to user table

Revision ID: cdcaa9c693e3
Revises: 608afa719fb8
Create Date: 2016-04-04 13:40:48.574963

"""

# revision identifiers, used by Alembic.
revision = 'cdcaa9c693e3'
down_revision = 'a04d38e74be3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###

