""" Dropping ExecutiveCompensation

Revision ID: d1dda3bf2daf
Revises: 5d1cdc179c1b
Create Date: 2019-07-10 19:44:30.553440

"""

# revision identifiers, used by Alembic.
revision = 'd1dda3bf2daf'
down_revision = '5d1cdc179c1b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executive_compensation')
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_compensation',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('executive_compensation_id', sa.INTEGER(), nullable=False),
    sa.Column('awardee_or_recipient_uniqu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ultimate_parent_unique_ide', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ultimate_parent_legal_enti', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer1_full_na', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer1_amount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer2_full_na', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer2_amount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer3_full_na', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer3_amount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer4_full_na', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer4_amount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer5_full_na', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_comp_officer5_amount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('awardee_or_recipient_legal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('executive_compensation_id', name='executive_compensation_pkey')
    )
    # ### end Alembic commands ###

