"""Remove cgac_code

Revision ID: d1f40bcf04b0
Revises: b4628b5a3f23
Create Date: 2016-12-20 16:50:04.204768

"""

# revision identifiers, used by Alembic.
revision = 'd1f40bcf04b0'
down_revision = 'b4628b5a3f23'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cgac_code')
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cgac_code', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###

