"""remove-staging-valid-record-flag

Revision ID: d279720144e8
Revises: b8d1160265a9
Create Date: 2016-07-29 09:13:55.191803

"""

# revision identifiers, used by Alembic.
revision = 'd279720144e8'
down_revision = 'b8d1160265a9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_data_broker():
    pass

def downgrade_data_broker():
    pass


def upgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_error_data():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_job_tracker():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_user_manager():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appropriation', 'valid_record')
    op.drop_column('award_financial', 'valid_record')
    op.drop_column('award_financial_assistance', 'valid_record')
    op.drop_column('object_class_program_activity', 'valid_record')
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_class_program_activity', sa.Column('valid_record', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('award_financial_assistance', sa.Column('valid_record', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('award_financial', sa.Column('valid_record', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('appropriation', sa.Column('valid_record', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    ### end Alembic commands ###

