"""Add expected value to rule_sql table

Revision ID: d753553fa79b
Revises: f538dc9dc328
Create Date: 2019-09-25 09:32:46.816908

"""

# revision identifiers, used by Alembic.
revision = 'd753553fa79b'
down_revision = 'f538dc9dc328'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_sql', sa.Column('expected_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_sql', 'expected_value')
    # ### end Alembic commands ###

