"""Adding USSGL480110 and USSGL490110 to object_class_program_activity and award_financial tables

Revision ID: d8a5f8a78676
Revises: 86316f32dad9
Create Date: 2024-09-19 11:56:00.550543

"""

# revision identifiers, used by Alembic.
revision = 'd8a5f8a78676'
down_revision = '86316f32dad9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial', sa.Column('ussgl480110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('award_financial', sa.Column('ussgl490110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('object_class_program_activity', sa.Column('ussgl480110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('object_class_program_activity', sa.Column('ussgl490110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_award_financial', sa.Column('ussgl480110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_award_financial', sa.Column('ussgl490110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_object_class_program_activity', sa.Column('ussgl480110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    op.add_column('published_object_class_program_activity', sa.Column('ussgl490110_reinstated_del_cpe', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_object_class_program_activity', 'ussgl490110_reinstated_del_cpe')
    op.drop_column('published_object_class_program_activity', 'ussgl480110_reinstated_del_cpe')
    op.drop_column('published_award_financial', 'ussgl490110_reinstated_del_cpe')
    op.drop_column('published_award_financial', 'ussgl480110_reinstated_del_cpe')
    op.drop_column('object_class_program_activity', 'ussgl490110_reinstated_del_cpe')
    op.drop_column('object_class_program_activity', 'ussgl480110_reinstated_del_cpe')
    op.drop_column('award_financial', 'ussgl490110_reinstated_del_cpe')
    op.drop_column('award_financial', 'ussgl480110_reinstated_del_cpe')
    # ### end Alembic commands ###

