"""add_fsrs_indices

Revision ID: dcbb5afa125e
Revises: 1ae491ca0925
Create Date: 2016-09-08 14:43:04.547230

"""

# revision identifiers, used by Alembic.
revision = 'dcbb5afa125e'
down_revision = '1ae491ca0925'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fsrs_grant_fain'), 'fsrs_grant', ['fain'], unique=False)
    op.create_index(op.f('ix_fsrs_procurement_contract_number'), 'fsrs_procurement', ['contract_number'], unique=False)
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fsrs_procurement_contract_number'), table_name='fsrs_procurement')
    op.drop_index(op.f('ix_fsrs_grant_fain'), table_name='fsrs_grant')
    ### end Alembic commands ###

