"""add_new_short_colnames

Revision ID: de141f790505
Revises: 18e9827a876d
Create Date: 2016-06-27 10:38:09.183770

"""

# revision identifiers, used by Alembic.
revision = 'de141f790505'
down_revision = '18e9827a876d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()

def upgrade_data_broker():
    pass

def downgrade_data_broker():
    pass

def upgrade_error_data():
    pass


def downgrade_error_data():
    pass


def upgrade_job_tracker():
    pass


def downgrade_job_tracker():
    pass


def upgrade_user_manager():
    pass


def downgrade_user_manager():
    pass


def upgrade_validation():

    #rename appropriation columns
    op.alter_column('appropriation', 'adjustmentstounobligatedbalancebroughtforward_cpe', new_column_name='adjustments_to_unobligated_cpe')
    op.alter_column('appropriation', 'spendingauthorityfromoffsettingcollectionsamounttotal_cpe', new_column_name='spending_authority_from_of_cpe')
    op.alter_column('appropriation', 'obligationsincurredtotalbytas_cpe', new_column_name='obligations_incurred_total_cpe')
    op.alter_column('appropriation', 'endingperiodofavailability', new_column_name='ending_period_of_availabil')
    op.alter_column('appropriation', 'contractauthorityamounttotal_cpe', new_column_name='contract_authority_amount_cpe')
    op.alter_column('appropriation', 'beginningperiodofavailability', new_column_name='beginning_period_of_availa')
    op.alter_column('appropriation', 'allocationtransferagencyidentifier', new_column_name='allocation_transfer_agency')
    op.alter_column('appropriation', 'subaccountcode', new_column_name='sub_account_code')
    op.alter_column('appropriation', 'unobligatedbalance_cpe', new_column_name='unobligated_balance_cpe')
    op.alter_column('appropriation', 'grossoutlayamountbytas_cpe', new_column_name='gross_outlay_amount_by_tas_cpe')
    op.alter_column('appropriation', 'budgetauthorityavailableamounttotal_cpe', new_column_name='budget_authority_available_cpe')
    op.alter_column('appropriation', 'availabilitytypecode', new_column_name='availability_type_code')
    op.alter_column('appropriation', 'budgetauthorityappropriatedamount_cpe', new_column_name='budget_authority_appropria_cpe')
    op.alter_column('appropriation', 'agencyidentifier', new_column_name='agency_identifier')
    op.alter_column('appropriation', 'otherbudgetaryresourcesamount_cpe', new_column_name='other_budgetary_resources_cpe')
    op.alter_column('appropriation', 'deobligationsrecoveriesrefundsbytas_cpe', new_column_name='deobligations_recoveries_r_cpe')
    op.alter_column('appropriation', 'borrowingauthorityamounttotal_cpe', new_column_name='borrowing_authority_amount_cpe')
    op.alter_column('appropriation', 'mainaccountcode', new_column_name='main_account_code')
    op.alter_column('appropriation', 'statusofbudgetaryresourcestotal_cpe', new_column_name='status_of_budgetary_resour_cpe')
    op.alter_column('appropriation', 'budgetauthorityunobligatedbalancebroughtforward_fyb', new_column_name='budget_authority_unobligat_fyb')


    op.alter_column('award_financial', 'programactivitycode', new_column_name='program_activity_code')
    op.alter_column('award_financial', 'grossoutlaysundeliveredordersprepaidtotal_cpe', new_column_name='gross_outlays_undelivered_cpe')
    op.alter_column('award_financial', 'allocationtransferagencyidentifier', new_column_name='allocation_transfer_agency')
    op.alter_column('award_financial', 'subaccountcode', new_column_name='sub_account_code')
    op.alter_column('award_financial', 'transactionobligatedamount', new_column_name='transaction_obligated_amou')
    op.alter_column('award_financial', 'obligationsdeliveredordersunpaidtotal_fyb', new_column_name='obligations_delivered_orde_fyb')
    op.alter_column('award_financial', 'ussgl497100_downadjsprioryrunpaiddelivordersobligrec_cpe', new_column_name='ussgl497100_downward_adjus_cpe')
    op.alter_column('award_financial', 'ussgl480200_undeliveredordersobligationsprepaidadvanced_fyb', new_column_name='ussgl480200_undelivered_or_fyb')
    op.alter_column('award_financial', 'ussgl490100_deliveredordersobligationsunpaid_cpe', new_column_name='ussgl490100_delivered_orde_cpe')
    op.alter_column('award_financial', 'agencyidentifier', new_column_name='agency_identifier')
    op.alter_column('award_financial', 'obligationsundeliveredordersunpaidtotal_fyb', new_column_name='obligations_undelivered_or_fyb')
    op.alter_column('award_financial', 'grossoutlayamountbyaward_fyb', new_column_name='gross_outlay_amount_by_awa_fyb')
    op.alter_column('award_financial', 'ussgl480100_undeliveredordersobligationsunpaid_cpe', new_column_name='ussgl480100_undelivered_or_cpe')
    op.alter_column('award_financial', 'obligationsundeliveredordersunpaidtotal_cpe', new_column_name='obligations_undelivered_or_cpe')
    op.alter_column('award_financial', 'endingperiodofavailability', new_column_name='ending_period_of_availabil')
    op.alter_column('award_financial', 'parentawardid', new_column_name='parent_award_id')
    op.alter_column('award_financial', 'obligationsdeliveredordersunpaidtotal_cpe', new_column_name='obligations_delivered_orde_cpe')
    op.alter_column('award_financial', 'programactivityname', new_column_name='program_activity_name')
    op.alter_column('award_financial', 'ussgl490200_deliveredordersobligationspaid_cpe', new_column_name='ussgl490200_delivered_orde_cpe')
    op.alter_column('award_financial', 'grossoutlaysdeliveredorderspaidtotal_fyb', new_column_name='gross_outlays_delivered_or_fyb')
    op.alter_column('award_financial', 'ussgl490800_authorityoutlayednotyetdisbursed_cpe', new_column_name='ussgl490800_authority_outl_cpe')
    op.alter_column('award_financial', 'obligationsincurredtotalbyaward_cpe', new_column_name='obligations_incurred_byawa_cpe')
    op.alter_column('award_financial', 'ussgl487200_downadjsprioryrppdadvundelivordersobligref_cpe', new_column_name='ussgl487200_downward_adjus_cpe')
    op.alter_column('award_financial', 'ussgl483100_undeliveredordersobligtransferredunpaid_cpe', new_column_name='ussgl483100_undelivered_or_cpe')
    op.alter_column('award_financial', 'grossoutlayamountbyaward_cpe', new_column_name='gross_outlay_amount_by_awa_cpe')
    op.alter_column('award_financial', 'beginningperiodofavailability', new_column_name='beginning_period_of_availa')
    op.alter_column('award_financial', 'ussgl493100_deliveredordersobligstransferredunpaid_cpe', new_column_name='ussgl493100_delivered_orde_cpe')
    op.alter_column('award_financial', 'ussgl490800_authorityoutlayednotyetdisbursed_fyb', new_column_name='ussgl490800_authority_outl_fyb')
    op.alter_column('award_financial', 'ussgl483200_undeliveredordersobligtransferredppdadv_cpe', new_column_name='ussgl483200_undelivered_or_cpe')
    op.alter_column('award_financial', 'ussgl480200_undeliveredordersobligationsprepaidadv_cpe', new_column_name='ussgl480200_undelivered_or_cpe')
    op.alter_column('award_financial', 'ussgl498100_upadjsprioryeardeliveredordersobligunpaid_cpe', new_column_name='ussgl498100_upward_adjustm_cpe')
    op.alter_column('award_financial', 'deobligationsrecoveriesrefundsofprioryearbyaward_cpe', new_column_name='deobligations_recov_by_awa_cpe')
    op.alter_column('award_financial', 'ussgl488200_upadjsprioryrundelivordersobligprepaidadv_cpe', new_column_name='ussgl488200_upward_adjustm_cpe')
    op.alter_column('award_financial', 'ussgl498200_upadjsprioryrdelivordersobligpaid_cpe', new_column_name='ussgl498200_upward_adjustm_cpe')
    op.alter_column('award_financial', 'grossoutlaysundeliveredordersprepaidtotal_fyb', new_column_name='gross_outlays_undelivered_fyb')
    op.alter_column('award_financial', 'ussgl487100_downadjsprioryrunpaidundelivordersobligrec_cpe', new_column_name='ussgl487100_downward_adjus_cpe')
    op.alter_column('award_financial', 'ussgl490100_deliveredordersobligationsunpaid_fyb', new_column_name='ussgl490100_delivered_orde_fyb')
    op.alter_column('award_financial', 'ussgl488100_upadjsprioryearundelivordersobligunpaid_cpe', new_column_name='ussgl488100_upward_adjustm_cpe')
    op.alter_column('award_financial', 'ussgl480100_undeliveredordersobligationsunpaid_fyb', new_column_name='ussgl480100_undelivered_or_fyb')
    op.alter_column('award_financial', 'bydirectreimbursablefundingsource', new_column_name='by_direct_reimbursable_fun')
    op.alter_column('award_financial', 'ussgl497200_downadjsprioryrpaiddelivordersobligrefclt_cpe', new_column_name='ussgl497200_downward_adjus_cpe')
    op.alter_column('award_financial', 'objectclass', new_column_name='object_class')
    op.alter_column('award_financial', 'availabilitytypecode', new_column_name='availability_type_code')
    op.alter_column('award_financial', 'grossoutlaysdeliveredorderspaidtotal_cpe', new_column_name='gross_outlays_delivered_or_cpe')
    op.alter_column('award_financial', 'mainaccountcode', new_column_name='main_account_code')

    op.drop_index('ix_award_financial_tas_oc_pa', table_name='award_financial')
    op.create_index('ix_award_financial_tas_oc_pa', 'award_financial', ['tas', 'object_class', 'program_activity_code'],
                    unique=False)

    # rename award_financial_assistance columns

    op.alter_column('award_financial_assistance', 'correctionlatedeleteindicator', new_column_name='correction_late_delete_ind')
    op.alter_column('award_financial_assistance', 'federalactionobligation', new_column_name='federal_action_obligation')
    op.alter_column('award_financial_assistance', 'legalentitystatename', new_column_name='legal_entity_state_name')
    op.alter_column('award_financial_assistance', 'fundingsubtieragencycode', new_column_name='funding_sub_tier_agency_co')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformanceforeignlocationdescription', new_column_name='place_of_performance_forei')
    op.alter_column('award_financial_assistance', 'fundingagencyofficename', new_column_name='funding_office_name')
    op.alter_column('award_financial_assistance', 'awardingsubtieragencyname', new_column_name='awarding_sub_tier_agency_n')
    op.alter_column('award_financial_assistance', 'periodofperformancecurrentenddate', new_column_name='period_of_performance_curr')
    op.alter_column('award_financial_assistance', 'legalentitycountycode', new_column_name='legal_entity_county_code')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancecongressionaldistrict', new_column_name='place_of_performance_congr')
    op.alter_column('award_financial_assistance', 'fiscalyearandquartercorrection', new_column_name='fiscal_year_and_quarter_co')
    op.alter_column('award_financial_assistance', 'legalentitystatecode', new_column_name='legal_entity_state_code')
    op.alter_column('award_financial_assistance', 'legalentitycongressionaldistrict', new_column_name='legal_entity_congressional')
    op.alter_column('award_financial_assistance', 'legalentityforeigncityname', new_column_name='legal_entity_foreign_city')
    op.alter_column('award_financial_assistance', 'awardingofficename', new_column_name='awarding_office_name')
    op.alter_column('award_financial_assistance', 'awardingofficecode', new_column_name='awarding_office_code')
    op.alter_column('award_financial_assistance', 'actiondate', new_column_name='action_date')
    op.alter_column('award_financial_assistance', 'fundingagencycode', new_column_name='funding_agency_code')
    op.alter_column('award_financial_assistance', 'awardingsubtieragencycode', new_column_name='awarding_sub_tier_agency_c')
    op.alter_column('award_financial_assistance', 'awardingagencyname', new_column_name='awarding_agency_name')
    op.alter_column('award_financial_assistance', 'legalentitycountrycode', new_column_name='legal_entity_country_code')
    op.alter_column('award_financial_assistance', 'legalentityaddressline3', new_column_name='legal_entity_address_line3')
    op.alter_column('award_financial_assistance', 'legalentityaddressline2', new_column_name='legal_entity_address_line2')
    op.alter_column('award_financial_assistance', 'legalentityaddressline1', new_column_name='legal_entity_address_line1')
    op.alter_column('award_financial_assistance', 'fundingsubtieragencyname', new_column_name='funding_sub_tier_agency_na')
    op.alter_column('award_financial_assistance', 'businesstypes', new_column_name='business_types')
    op.alter_column('award_financial_assistance', 'nonfederalfundingamount', new_column_name='non_federal_funding_amount')
    op.alter_column('award_financial_assistance', 'fundingofficecode', new_column_name='funding_office_code')
    op.alter_column('award_financial_assistance', 'legalentityziplast4', new_column_name='legal_entity_zip_last4')
    op.alter_column('award_financial_assistance', 'businessfundsindicator', new_column_name='business_funds_indicator')
    op.alter_column('award_financial_assistance', 'facevalueloanguarantee', new_column_name='face_value_loan_guarantee')
    op.alter_column('award_financial_assistance', 'awardmodificationamendmentnumber', new_column_name='award_modification_amendme')
    op.alter_column('award_financial_assistance', 'originalloansubsidycost', new_column_name='original_loan_subsidy_cost')
    op.alter_column('award_financial_assistance', 'legalentitycitycode', new_column_name='legal_entity_city_code')
    op.alter_column('award_financial_assistance', 'awardingagencycode', new_column_name='awarding_agency_code')
    op.alter_column('award_financial_assistance', 'fundingagencyname', new_column_name='funding_agency_name')
    op.alter_column('award_financial_assistance', 'legalentitycityname', new_column_name='legal_entity_city_name')
    op.alter_column('award_financial_assistance', 'legalentityforeignpostalcode', new_column_name='legal_entity_foreign_posta')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancecityname', new_column_name='place_of_performance_city')
    op.alter_column('award_financial_assistance', 'periodofperformancestartdate', new_column_name='period_of_performance_star')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancecode', new_column_name='place_of_performance_code')
    op.alter_column('award_financial_assistance', 'awardeeorrecipientlegalentityname', new_column_name='awardee_or_recipient_legal')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancezipplus4', new_column_name='place_of_performance_zip4a')
    op.alter_column('award_financial_assistance', 'assistancetype', new_column_name='assistance_type')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancestatename', new_column_name='place_of_perform_state_nam')
    op.alter_column('award_financial_assistance', 'legalentitycountyname', new_column_name='legal_entity_county_name')
    op.alter_column('award_financial_assistance', 'recordtype', new_column_name='record_type')
    op.alter_column('award_financial_assistance', 'legalentityforeignprovincename', new_column_name='legal_entity_foreign_provi')
    op.alter_column('award_financial_assistance', 'legalentityzip5', new_column_name='legal_entity_zip5')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancecountyname', new_column_name='place_of_perform_county_na')
    op.alter_column('award_financial_assistance', 'totalfundingamount', new_column_name='total_funding_amount')
    op.alter_column('award_financial_assistance', 'actiontype', new_column_name='action_type')
    op.alter_column('award_financial_assistance', 'awarddescription', new_column_name='award_description')
    op.alter_column('award_financial_assistance', 'awardeeorrecipientuniqueidentifier', new_column_name='awardee_or_recipient_uniqu')
    op.alter_column('award_financial_assistance', 'primaryplaceofperformancecountrycode', new_column_name='place_of_perform_country_c')

    #rename object_class_program_activity columns

    op.alter_column('object_class_program_activity', 'obligationsdeliveredordersunpaidtotal_cpe', new_column_name='obligations_delivered_orde_cpe')
    op.alter_column('object_class_program_activity', 'ussgl488200_upadjsprioryrundelivordersobligprepaidadv_cpe', new_column_name='ussgl488200_upward_adjustm_cpe')
    op.alter_column('object_class_program_activity', 'grossoutlaysundeliveredordersprepaidtotal_cpe', new_column_name='gross_outlays_undelivered_cpe')
    op.alter_column('object_class_program_activity', 'allocationtransferagencyidentifier', new_column_name='allocation_transfer_agency')
    op.alter_column('object_class_program_activity', 'subaccountcode', new_column_name='sub_account_code')
    op.alter_column('object_class_program_activity', 'ussgl480200_undeliveredordersobligationsprepaidadv_fyb', new_column_name='ussgl480200_undelivered_or_fyb')
    op.alter_column('object_class_program_activity', 'obligationsdeliveredordersunpaidtotal_fyb', new_column_name='obligations_delivered_orde_fyb')
    op.alter_column('object_class_program_activity', 'ussgl497100_downadjsprioryrunpaiddelivordersobligrec_cpe', new_column_name='ussgl497100_downward_adjus_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490100_deliveredordersobligationsunpaid_cpe', new_column_name='ussgl490100_delivered_orde_cpe')
    op.alter_column('object_class_program_activity', 'agencyidentifier', new_column_name='agency_identifier')
    op.alter_column('object_class_program_activity', 'obligationsundeliveredordersunpaidtotal_fyb', new_column_name='obligations_undelivered_or_fyb')
    op.alter_column('object_class_program_activity', 'ussgl480100_undeliveredordersobligationsunpaid_cpe', new_column_name='ussgl480100_undelivered_or_cpe')
    op.alter_column('object_class_program_activity', 'obligationsundeliveredordersunpaidtotal_cpe', new_column_name='obligations_undelivered_or_cpe')
    op.alter_column('object_class_program_activity', 'endingperiodofavailability', new_column_name='ending_period_of_availabil')
    op.alter_column('object_class_program_activity', 'grossoutlayamountbyprogramobjectclass_fyb', new_column_name='gross_outlay_amount_by_pro_fyb')
    op.alter_column('object_class_program_activity', 'programactivitycode', new_column_name='program_activity_code')
    op.alter_column('object_class_program_activity', 'programactivityname', new_column_name='program_activity_name')
    op.alter_column('object_class_program_activity', 'ussgl490200_deliveredordersobligationspaid_cpe', new_column_name='ussgl490200_delivered_orde_cpe')
    op.alter_column('object_class_program_activity', 'ussgl498100_upadjsprioryeardeliveredordersobligunpaid_cpe', new_column_name='ussgl498100_upward_adjustm_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490800_authorityoutlayednotyetdisbursed_cpe', new_column_name='ussgl490800_authority_outl_cpe')
    op.alter_column('object_class_program_activity', 'ussgl487200_downadjsprioryrppdadvundelivordersobligref_cpe', new_column_name='ussgl487200_downward_adjus_cpe')
    op.alter_column('object_class_program_activity', 'ussgl483100_undeliveredordersobligtransferredunpaid_cpe', new_column_name='ussgl483100_undelivered_or_cpe')
    op.alter_column('object_class_program_activity', 'grossoutlaysdeliveredorderspaidtotal_fyb', new_column_name='gross_outlays_delivered_or_fyb')
    op.alter_column('object_class_program_activity', 'beginningperiodofavailability', new_column_name='beginning_period_of_availa')
    op.alter_column('object_class_program_activity', 'ussgl493100_deliveredordersobligstransferredunpaid_cpe', new_column_name='ussgl493100_delivered_orde_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490800_authorityoutlayednotyetdisbursed_fyb', new_column_name='ussgl490800_authority_outl_fyb')
    op.alter_column('object_class_program_activity', 'ussgl483200_undeliveredordersobligtransferredppdadv_cpe', new_column_name='ussgl483200_undelivered_or_cpe')
    op.alter_column('object_class_program_activity', 'ussgl480200_undeliveredordersobligationsprepaidadv_cpe', new_column_name='ussgl480200_undelivered_or_cpe')
    op.alter_column('object_class_program_activity', 'grossoutlayamountbyprogramobjectclass_cpe', new_column_name='gross_outlay_amount_by_pro_cpe')
    op.alter_column('object_class_program_activity', 'deobligationsrecoveriesrefundsprioryrbyprogobjectclass_cpe', new_column_name='deobligations_recov_by_pro_cpe')
    op.alter_column('object_class_program_activity', 'ussgl498200_upadjsprioryrdelivordersobligpaid_cpe', new_column_name='ussgl498200_upward_adjustm_cpe')
    op.alter_column('object_class_program_activity', 'obligationsincurredbyprogramobjectclass_cpe', new_column_name='obligations_incurred_by_pr_cpe')
    op.alter_column('object_class_program_activity', 'grossoutlaysundeliveredordersprepaidtotal_fyb', new_column_name='gross_outlays_undelivered_fyb')
    op.alter_column('object_class_program_activity', 'ussgl487100_downadjsprioryrunpaidundelivordersobligrec_cpe', new_column_name='ussgl487100_downward_adjus_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490100_deliveredordersobligationsunpaid_fyb', new_column_name='ussgl490100_delivered_orde_fyb')
    op.alter_column('object_class_program_activity', 'ussgl488100_upadjsprioryearundelivordersobligunpaid_cpe', new_column_name='ussgl488100_upward_adjustm_cpe')
    op.alter_column('object_class_program_activity', 'ussgl480100_undeliveredordersobligationsunpaid_fyb', new_column_name='ussgl480100_undelivered_or_fyb')
    op.alter_column('object_class_program_activity', 'bydirectreimbursablefundingsource', new_column_name='by_direct_reimbursable_fun')
    op.alter_column('object_class_program_activity', 'ussgl497200_downadjsprioryrpaiddelivordersobligrefclt_cpe', new_column_name='ussgl497200_downward_adjus_cpe')
    op.alter_column('object_class_program_activity', 'objectclass', new_column_name='object_class')
    op.alter_column('object_class_program_activity', 'availabilitytypecode', new_column_name='availability_type_code')
    op.alter_column('object_class_program_activity', 'grossoutlaysdeliveredorderspaidtotal_cpe', new_column_name='gross_outlays_delivered_or_cpe')
    op.alter_column('object_class_program_activity', 'mainaccountcode', new_column_name='main_account_code')

    op.drop_index('ix_oc_pa_tas_oc_pa', table_name='object_class_program_activity')
    op.create_index('ix_oc_pa_tas_oc_pa', 'object_class_program_activity',
                    ['tas', 'object_class', 'program_activity_code'], unique=False)


def downgrade_validation():


    op.alter_column('object_class_program_activity', 'ussgl498200_upward_adjustm_cpe', new_column_name='ussgl498200_upadjsprioryrdelivordersobligpaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl498100_upward_adjustm_cpe', new_column_name='ussgl498100_upadjsprioryeardeliveredordersobligunpaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl497200_downward_adjus_cpe', new_column_name='ussgl497200_downadjsprioryrpaiddelivordersobligrefclt_cpe')
    op.alter_column('object_class_program_activity', 'ussgl497100_downward_adjus_cpe', new_column_name='ussgl497100_downadjsprioryrunpaiddelivordersobligrec_cpe')
    op.alter_column('object_class_program_activity', 'ussgl493100_delivered_orde_cpe', new_column_name='ussgl493100_deliveredordersobligstransferredunpaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490800_authority_outl_fyb', new_column_name='ussgl490800_authorityoutlayednotyetdisbursed_fyb')
    op.alter_column('object_class_program_activity', 'ussgl490800_authority_outl_cpe', new_column_name='ussgl490800_authorityoutlayednotyetdisbursed_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490200_delivered_orde_cpe', new_column_name='ussgl490200_deliveredordersobligationspaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl490100_delivered_orde_fyb', new_column_name='ussgl490100_deliveredordersobligationsunpaid_fyb')
    op.alter_column('object_class_program_activity', 'ussgl490100_delivered_orde_cpe', new_column_name='ussgl490100_deliveredordersobligationsunpaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl488200_upward_adjustm_cpe', new_column_name='ussgl488200_upadjsprioryrundelivordersobligprepaidadv_cpe')
    op.alter_column('object_class_program_activity', 'ussgl488100_upward_adjustm_cpe', new_column_name='ussgl488100_upadjsprioryearundelivordersobligunpaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl487200_downward_adjus_cpe', new_column_name='ussgl487200_downadjsprioryrppdadvundelivordersobligref_cpe')
    op.alter_column('object_class_program_activity', 'ussgl487100_downward_adjus_cpe', new_column_name='ussgl487100_downadjsprioryrunpaidundelivordersobligrec_cpe')
    op.alter_column('object_class_program_activity', 'ussgl483200_undelivered_or_cpe', new_column_name='ussgl483200_undeliveredordersobligtransferredppdadv_cpe')
    op.alter_column('object_class_program_activity', 'ussgl483100_undelivered_or_cpe', new_column_name='ussgl483100_undeliveredordersobligtransferredunpaid_cpe')
    op.alter_column('object_class_program_activity', 'ussgl480200_undelivered_or_fyb', new_column_name='ussgl480200_undeliveredordersobligationsprepaidadv_fyb')
    op.alter_column('object_class_program_activity', 'ussgl480200_undelivered_or_cpe', new_column_name='ussgl480200_undeliveredordersobligationsprepaidadv_cpe')
    op.alter_column('object_class_program_activity', 'ussgl480100_undelivered_or_fyb', new_column_name='ussgl480100_undeliveredordersobligationsunpaid_fyb')
    op.alter_column('object_class_program_activity', 'ussgl480100_undelivered_or_cpe', new_column_name='ussgl480100_undeliveredordersobligationsunpaid_cpe')
    op.alter_column('object_class_program_activity', 'sub_account_code', new_column_name='subaccountcode')
    op.alter_column('object_class_program_activity', 'program_activity_name', new_column_name='programactivityname')
    op.alter_column('object_class_program_activity', 'program_activity_code', new_column_name='programactivitycode')
    op.alter_column('object_class_program_activity', 'obligations_undelivered_or_fyb', new_column_name='obligationsundeliveredordersunpaidtotal_fyb')
    op.alter_column('object_class_program_activity', 'obligations_undelivered_or_cpe', new_column_name='obligationsundeliveredordersunpaidtotal_cpe')
    op.alter_column('object_class_program_activity', 'obligations_incurred_by_pr_cpe', new_column_name='obligationsincurredbyprogramobjectclass_cpe')
    op.alter_column('object_class_program_activity', 'obligations_delivered_orde_fyb', new_column_name='obligationsdeliveredordersunpaidtotal_fyb')
    op.alter_column('object_class_program_activity', 'obligations_delivered_orde_cpe', new_column_name='obligationsdeliveredordersunpaidtotal_cpe')
    op.alter_column('object_class_program_activity', 'object_class', new_column_name='objectclass')
    op.alter_column('object_class_program_activity', 'main_account_code', new_column_name='mainaccountcode')
    op.alter_column('object_class_program_activity', 'gross_outlays_undelivered_fyb', new_column_name='grossoutlaysundeliveredordersprepaidtotal_fyb')
    op.alter_column('object_class_program_activity', 'gross_outlays_undelivered_cpe', new_column_name='grossoutlaysundeliveredordersprepaidtotal_cpe')
    op.alter_column('object_class_program_activity', 'gross_outlays_delivered_or_fyb', new_column_name='grossoutlaysdeliveredorderspaidtotal_fyb')
    op.alter_column('object_class_program_activity', 'gross_outlays_delivered_or_cpe', new_column_name='grossoutlaysdeliveredorderspaidtotal_cpe')
    op.alter_column('object_class_program_activity', 'gross_outlay_amount_by_pro_fyb', new_column_name='grossoutlayamountbyprogramobjectclass_fyb')
    op.alter_column('object_class_program_activity', 'gross_outlay_amount_by_pro_cpe', new_column_name='grossoutlayamountbyprogramobjectclass_cpe')
    op.alter_column('object_class_program_activity', 'ending_period_of_availabil', new_column_name='endingperiodofavailability')
    op.alter_column('object_class_program_activity', 'deobligations_recov_by_pro_cpe', new_column_name='deobligationsrecoveriesrefundsprioryrbyprogobjectclass_cpe')
    op.alter_column('object_class_program_activity', 'by_direct_reimbursable_fun', new_column_name='bydirectreimbursablefundingsource')
    op.alter_column('object_class_program_activity', 'beginning_period_of_availa', new_column_name='beginningperiodofavailability')
    op.alter_column('object_class_program_activity', 'availability_type_code', new_column_name='availabilitytypecode')
    op.alter_column('object_class_program_activity', 'allocation_transfer_agency', new_column_name='allocationtransferagencyidentifier')
    op.alter_column('object_class_program_activity', 'agency_identifier', new_column_name='agencyidentifier')

    op.drop_index('ix_oc_pa_tas_oc_pa', table_name='object_class_program_activity')
    op.create_index('ix_oc_pa_tas_oc_pa', 'object_class_program_activity',
                    ['tas', 'objectclass', 'programactivitycode'], unique=False)


    op.alter_column('award_financial_assistance', 'total_funding_amount', new_column_name='totalfundingamount')
    op.alter_column('award_financial_assistance', 'record_type', new_column_name='recordtype')
    op.alter_column('award_financial_assistance', 'place_of_performance_zip4a', new_column_name='primaryplaceofperformancezipplus4')
    op.alter_column('award_financial_assistance', 'place_of_performance_forei', new_column_name='primaryplaceofperformanceforeignlocationdescription')
    op.alter_column('award_financial_assistance', 'place_of_performance_congr', new_column_name='primaryplaceofperformancecongressionaldistrict')
    op.alter_column('award_financial_assistance', 'place_of_performance_code', new_column_name='primaryplaceofperformancecode')
    op.alter_column('award_financial_assistance', 'place_of_performance_city', new_column_name='primaryplaceofperformancecityname')
    op.alter_column('award_financial_assistance', 'place_of_perform_state_nam', new_column_name='primaryplaceofperformancestatename')
    op.alter_column('award_financial_assistance', 'place_of_perform_county_na', new_column_name='primaryplaceofperformancecountyname')
    op.alter_column('award_financial_assistance', 'place_of_perform_country_c', new_column_name='primaryplaceofperformancecountrycode')
    op.alter_column('award_financial_assistance', 'period_of_performance_star', new_column_name='periodofperformancestartdate')
    op.alter_column('award_financial_assistance', 'period_of_performance_curr', new_column_name='periodofperformancecurrentenddate')
    op.alter_column('award_financial_assistance', 'original_loan_subsidy_cost', new_column_name='originalloansubsidycost')
    op.alter_column('award_financial_assistance', 'non_federal_funding_amount', new_column_name='nonfederalfundingamount')
    op.alter_column('award_financial_assistance', 'legal_entity_zip_last4', new_column_name='legalentityziplast4')
    op.alter_column('award_financial_assistance', 'legal_entity_zip5', new_column_name='legalentityzip5')
    op.alter_column('award_financial_assistance', 'legal_entity_state_name', new_column_name='legalentitystatename')
    op.alter_column('award_financial_assistance', 'legal_entity_state_code', new_column_name='legalentitystatecode')
    op.alter_column('award_financial_assistance', 'legal_entity_foreign_provi', new_column_name='legalentityforeignprovincename')
    op.alter_column('award_financial_assistance', 'legal_entity_foreign_posta', new_column_name='legalentityforeignpostalcode')
    op.alter_column('award_financial_assistance', 'legal_entity_foreign_city', new_column_name='legalentityforeigncityname')
    op.alter_column('award_financial_assistance', 'legal_entity_county_name', new_column_name='legalentitycountyname')
    op.alter_column('award_financial_assistance', 'legal_entity_county_code', new_column_name='legalentitycountycode')
    op.alter_column('award_financial_assistance', 'legal_entity_country_code', new_column_name='legalentitycountrycode')
    op.alter_column('award_financial_assistance', 'legal_entity_congressional', new_column_name='legalentitycongressionaldistrict')
    op.alter_column('award_financial_assistance', 'legal_entity_city_name', new_column_name='legalentitycityname')
    op.alter_column('award_financial_assistance', 'legal_entity_city_code', new_column_name='legalentitycitycode')
    op.alter_column('award_financial_assistance', 'legal_entity_address_line3', new_column_name='legalentityaddressline3')
    op.alter_column('award_financial_assistance', 'legal_entity_address_line2', new_column_name='legalentityaddressline2')
    op.alter_column('award_financial_assistance', 'legal_entity_address_line1', new_column_name='legalentityaddressline1')
    op.alter_column('award_financial_assistance', 'funding_sub_tier_agency_na', new_column_name='fundingsubtieragencyname')
    op.alter_column('award_financial_assistance', 'funding_sub_tier_agency_co', new_column_name='fundingsubtieragencycode')
    op.alter_column('award_financial_assistance', 'funding_office_name', new_column_name='fundingagencyofficename')
    op.alter_column('award_financial_assistance', 'funding_office_code', new_column_name='fundingofficecode')
    op.alter_column('award_financial_assistance', 'funding_agency_name', new_column_name='fundingagencyname')
    op.alter_column('award_financial_assistance', 'funding_agency_code', new_column_name='fundingagencycode')
    op.alter_column('award_financial_assistance', 'fiscal_year_and_quarter_co', new_column_name='fiscalyearandquartercorrection')
    op.alter_column('award_financial_assistance', 'federal_action_obligation', new_column_name='federalactionobligation')
    op.alter_column('award_financial_assistance', 'face_value_loan_guarantee', new_column_name='facevalueloanguarantee')
    op.alter_column('award_financial_assistance', 'correction_late_delete_ind', new_column_name='correctionlatedeleteindicator')
    op.alter_column('award_financial_assistance', 'business_types', new_column_name='businesstypes')
    op.alter_column('award_financial_assistance', 'business_funds_indicator', new_column_name='businessfundsindicator')
    op.alter_column('award_financial_assistance', 'awarding_sub_tier_agency_n', new_column_name='awardingsubtieragencyname')
    op.alter_column('award_financial_assistance', 'awarding_sub_tier_agency_c', new_column_name='awardingsubtieragencycode')
    op.alter_column('award_financial_assistance', 'awarding_office_name', new_column_name='awardingofficename')
    op.alter_column('award_financial_assistance', 'awarding_office_code', new_column_name='awardingofficecode')
    op.alter_column('award_financial_assistance', 'awarding_agency_name', new_column_name='awardingagencyname')
    op.alter_column('award_financial_assistance', 'awarding_agency_code', new_column_name='awardingagencycode')
    op.alter_column('award_financial_assistance', 'awardee_or_recipient_uniqu', new_column_name='awardeeorrecipientuniqueidentifier')
    op.alter_column('award_financial_assistance', 'awardee_or_recipient_legal', new_column_name='awardeeorrecipientlegalentityname')
    op.alter_column('award_financial_assistance', 'award_modification_amendme', new_column_name='awardmodificationamendmentnumber')
    op.alter_column('award_financial_assistance', 'award_description', new_column_name='awarddescription')
    op.alter_column('award_financial_assistance', 'assistance_type', new_column_name='assistancetype')
    op.alter_column('award_financial_assistance', 'action_type', new_column_name='actiontype')
    op.alter_column('award_financial_assistance', 'action_date', new_column_name='actiondate')


    op.alter_column('award_financial', 'ussgl498200_upward_adjustm_cpe', new_column_name='ussgl498200_upadjsprioryrdelivordersobligpaid_cpe')
    op.alter_column('award_financial', 'ussgl498100_upward_adjustm_cpe', new_column_name='ussgl498100_upadjsprioryeardeliveredordersobligunpaid_cpe')
    op.alter_column('award_financial', 'ussgl497200_downward_adjus_cpe', new_column_name='ussgl497200_downadjsprioryrpaiddelivordersobligrefclt_cpe')
    op.alter_column('award_financial', 'ussgl497100_downward_adjus_cpe', new_column_name='ussgl497100_downadjsprioryrunpaiddelivordersobligrec_cpe')
    op.alter_column('award_financial', 'ussgl493100_delivered_orde_cpe', new_column_name='ussgl493100_deliveredordersobligstransferredunpaid_cpe')
    op.alter_column('award_financial', 'ussgl490800_authority_outl_fyb', new_column_name='ussgl490800_authorityoutlayednotyetdisbursed_fyb')
    op.alter_column('award_financial', 'ussgl490800_authority_outl_cpe', new_column_name='ussgl490800_authorityoutlayednotyetdisbursed_cpe')
    op.alter_column('award_financial', 'ussgl490200_delivered_orde_cpe', new_column_name='ussgl490200_deliveredordersobligationspaid_cpe')
    op.alter_column('award_financial', 'ussgl490100_delivered_orde_fyb', new_column_name='ussgl490100_deliveredordersobligationsunpaid_fyb')
    op.alter_column('award_financial', 'ussgl490100_delivered_orde_cpe', new_column_name='ussgl490100_deliveredordersobligationsunpaid_cpe')
    op.alter_column('award_financial', 'ussgl488200_upward_adjustm_cpe', new_column_name='ussgl488200_upadjsprioryrundelivordersobligprepaidadv_cpe')
    op.alter_column('award_financial', 'ussgl488100_upward_adjustm_cpe', new_column_name='ussgl488100_upadjsprioryearundelivordersobligunpaid_cpe')
    op.alter_column('award_financial', 'ussgl487200_downward_adjus_cpe', new_column_name='ussgl487200_downadjsprioryrppdadvundelivordersobligref_cpe')
    op.alter_column('award_financial', 'ussgl487100_downward_adjus_cpe', new_column_name='ussgl487100_downadjsprioryrunpaidundelivordersobligrec_cpe')
    op.alter_column('award_financial', 'ussgl483200_undelivered_or_cpe', new_column_name='ussgl483200_undeliveredordersobligtransferredppdadv_cpe')
    op.alter_column('award_financial', 'ussgl483100_undelivered_or_cpe', new_column_name='ussgl483100_undeliveredordersobligtransferredunpaid_cpe')
    op.alter_column('award_financial', 'ussgl480200_undelivered_or_fyb', new_column_name='ussgl480200_undeliveredordersobligationsprepaidadvanced_fyb')
    op.alter_column('award_financial', 'ussgl480200_undelivered_or_cpe', new_column_name='ussgl480200_undeliveredordersobligationsprepaidadv_cpe')
    op.alter_column('award_financial', 'ussgl480100_undelivered_or_fyb', new_column_name='ussgl480100_undeliveredordersobligationsunpaid_fyb')
    op.alter_column('award_financial', 'ussgl480100_undelivered_or_cpe', new_column_name='ussgl480100_undeliveredordersobligationsunpaid_cpe')
    op.alter_column('award_financial', 'transaction_obligated_amou', new_column_name='transactionobligatedamount')
    op.alter_column('award_financial', 'sub_account_code', new_column_name='subaccountcode')
    op.alter_column('award_financial', 'program_activity_name', new_column_name='programactivityname')
    op.alter_column('award_financial', 'program_activity_code', new_column_name='programactivitycode')
    op.alter_column('award_financial', 'parent_award_id', new_column_name='parentawardid')
    op.alter_column('award_financial', 'obligations_undelivered_or_fyb', new_column_name='obligationsundeliveredordersunpaidtotal_fyb')
    op.alter_column('award_financial', 'obligations_undelivered_or_cpe', new_column_name='obligationsundeliveredordersunpaidtotal_cpe')
    op.alter_column('award_financial', 'obligations_incurred_byawa_cpe', new_column_name='obligationsincurredtotalbyaward_cpe')
    op.alter_column('award_financial', 'obligations_delivered_orde_fyb', new_column_name='obligationsdeliveredordersunpaidtotal_fyb')
    op.alter_column('award_financial', 'obligations_delivered_orde_cpe', new_column_name='obligationsdeliveredordersunpaidtotal_cpe')
    op.alter_column('award_financial', 'object_class', new_column_name='objectclass')
    op.alter_column('award_financial', 'main_account_code', new_column_name='mainaccountcode')
    op.alter_column('award_financial', 'gross_outlays_undelivered_fyb', new_column_name='grossoutlaysundeliveredordersprepaidtotal_fyb')
    op.alter_column('award_financial', 'gross_outlays_undelivered_cpe', new_column_name='grossoutlaysundeliveredordersprepaidtotal_cpe')
    op.alter_column('award_financial', 'gross_outlays_delivered_or_fyb', new_column_name='grossoutlaysdeliveredorderspaidtotal_fyb')
    op.alter_column('award_financial', 'gross_outlays_delivered_or_cpe', new_column_name='grossoutlaysdeliveredorderspaidtotal_cpe')
    op.alter_column('award_financial', 'gross_outlay_amount_by_awa_fyb', new_column_name='grossoutlayamountbyaward_fyb')
    op.alter_column('award_financial', 'gross_outlay_amount_by_awa_cpe', new_column_name='grossoutlayamountbyaward_cpe')
    op.alter_column('award_financial', 'ending_period_of_availabil', new_column_name='endingperiodofavailability')
    op.alter_column('award_financial', 'deobligations_recov_by_awa_cpe', new_column_name='deobligationsrecoveriesrefundsofprioryearbyaward_cpe')
    op.alter_column('award_financial', 'by_direct_reimbursable_fun', new_column_name='bydirectreimbursablefundingsource')
    op.alter_column('award_financial', 'beginning_period_of_availa', new_column_name='beginningperiodofavailability')
    op.alter_column('award_financial', 'availability_type_code', new_column_name='availabilitytypecode')
    op.alter_column('award_financial', 'allocation_transfer_agency', new_column_name='allocationtransferagencyidentifier')
    op.alter_column('award_financial', 'agency_identifier', new_column_name='agencyidentifier')

    op.drop_index('ix_award_financial_tas_oc_pa', table_name='award_financial')
    op.create_index('ix_award_financial_tas_oc_pa', 'award_financial', ['tas', 'objectclass', 'programactivitycode'],
                    unique=False)


    op.alter_column('appropriation', 'unobligated_balance_cpe', new_column_name='unobligatedbalance_cpe')
    op.alter_column('appropriation', 'sub_account_code', new_column_name='subaccountcode')
    op.alter_column('appropriation', 'status_of_budgetary_resour_cpe', new_column_name='statusofbudgetaryresourcestotal_cpe')
    op.alter_column('appropriation', 'spending_authority_from_of_cpe', new_column_name='spendingauthorityfromoffsettingcollectionsamounttotal_cpe')
    op.alter_column('appropriation', 'other_budgetary_resources_cpe', new_column_name='otherbudgetaryresourcesamount_cpe')
    op.alter_column('appropriation', 'obligations_incurred_total_cpe', new_column_name='obligationsincurredtotalbytas_cpe')
    op.alter_column('appropriation', 'main_account_code', new_column_name='mainaccountcode')
    op.alter_column('appropriation', 'gross_outlay_amount_by_tas_cpe', new_column_name='grossoutlayamountbytas_cpe')
    op.alter_column('appropriation', 'ending_period_of_availabil', new_column_name='endingperiodofavailability')
    op.alter_column('appropriation', 'deobligations_recoveries_r_cpe', new_column_name='deobligationsrecoveriesrefundsbytas_cpe')
    op.alter_column('appropriation', 'contract_authority_amount_cpe', new_column_name='contractauthorityamounttotal_cpe')
    op.alter_column('appropriation', 'budget_authority_unobligat_fyb', new_column_name='budgetauthorityunobligatedbalancebroughtforward_fyb')
    op.alter_column('appropriation', 'budget_authority_available_cpe', new_column_name='budgetauthorityavailableamounttotal_cpe')
    op.alter_column('appropriation', 'budget_authority_appropria_cpe', new_column_name='budgetauthorityappropriatedamount_cpe')
    op.alter_column('appropriation', 'borrowing_authority_amount_cpe', new_column_name='borrowingauthorityamounttotal_cpe')
    op.alter_column('appropriation', 'beginning_period_of_availa', new_column_name='beginningperiodofavailability')
    op.alter_column('appropriation', 'availability_type_code', new_column_name='availabilitytypecode')
    op.alter_column('appropriation', 'allocation_transfer_agency', new_column_name='allocationtransferagencyidentifier')
    op.alter_column('appropriation', 'agency_identifier', new_column_name='agencyidentifier')
    op.alter_column('appropriation', 'adjustments_to_unobligated_cpe', new_column_name='adjustmentstounobligatedbalancebroughtforward_cpe')
