"""creating a new model to store dates for the GTAS submission window

Revision ID: df2f541291a5
Revises: aa10ae595d3e
Create Date: 2017-07-06 12:06:53.946926

"""

# revision identifiers, used by Alembic.
revision = 'df2f541291a5'
down_revision = 'aa10ae595d3e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtas_submission_window',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('window_id')
    )
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gtas_submission_window')
    ### end Alembic commands ###

