"""Additional indexes for subaward generation

Revision ID: dfc0fb029b42
Revises: 4d2e50bf6e6e
Create Date: 2025-04-01 17:45:32.070246

"""

# revision identifiers, used by Alembic.
revision = 'dfc0fb029b42'
down_revision = '4d2e50bf6e6e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sam_subcontract_uei_upper', 'sam_subcontract', [sa.text("UPPER(uei)")], unique=False)
    op.create_index('ix_sam_subcontract_puei_upper', 'sam_subcontract', [sa.text("UPPER(parent_uei)")], unique=False)
    op.create_index('ix_sam_subgrant_uei_upper', 'sam_subgrant', [sa.text("UPPER(uei)")], unique=False)
    op.create_index('ix_sam_subgrant_puei_upper', 'sam_subgrant', [sa.text("UPPER(parent_uei)")], unique=False)
    op.create_index('ix_dap_uei_upper', 'detached_award_procurement', [sa.text("UPPER(awardee_or_recipient_uei)")], unique=False)
    op.create_index('ix_dap_puei_upper', 'detached_award_procurement', [sa.text("UPPER(ultimate_parent_uei)")], unique=False)

    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dap_puei_upper', table_name='detached_award_procurement')
    op.drop_index('ix_dap_uei_upper', table_name='detached_award_procurement')
    op.drop_index('ix_sam_subgrant_puei_upper', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_uei_upper', table_name='sam_subgrant')
    op.drop_index('ix_sam_subcontract_puei_upper', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_uei_upper', table_name='sam_subcontract')
    # ### end Alembic commands ###

