"""add_number_errors_job

Revision ID: e3d7eb4d44f0
Revises: 1f5613e38200
Create Date: 2016-08-05 16:56:56.533265

"""

# revision identifiers, used by Alembic.
revision = 'e3d7eb4d44f0'
down_revision = '1f5613e38200'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('number_of_errors', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('number_of_warnings', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'number_of_warnings')
    op.drop_column('job', 'number_of_errors')
    ### end Alembic commands ###

