"""Add general_ledger_post_date to award_financial tables

Revision ID: e5b90e0b2ff8
Revises: 7dd3f4b007e5
Create Date: 2019-05-09 13:16:09.898165

"""

# revision identifiers, used by Alembic.
revision = 'e5b90e0b2ff8'
down_revision = '7dd3f4b007e5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial', sa.Column('general_ledger_post_date', sa.Date(), nullable=True))
    op.add_column('certified_award_financial', sa.Column('general_ledger_post_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certified_award_financial', 'general_ledger_post_date')
    op.drop_column('award_financial', 'general_ledger_post_date')
    # ### end Alembic commands ###

