""" SAM Subaward table populate updates

Revision ID: e7386b41fd9b
Revises: 8effcd11f19c
Create Date: 2025-02-27 00:22:44.447730

"""

# revision identifiers, used by Alembic.
revision = 'e7386b41fd9b'
down_revision = '8effcd11f19c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sam_subcontract_le_country', 'sam_subcontract', ['legal_entity_country_code'], unique=False)
    op.create_index('ix_sam_subcontract_le_state', 'sam_subcontract', ['legal_entity_state_code'], unique=False)
    op.create_index('ix_sam_subcontract_le_zip', 'sam_subcontract', ['legal_entity_zip_code'], unique=False)
    op.create_index('ix_sam_subcontract_ppop_country', 'sam_subcontract', ['ppop_country_code'], unique=False)
    op.create_index('ix_sam_subcontract_ppop_state', 'sam_subcontract', ['ppop_state_code'], unique=False)
    op.create_index('ix_sam_subcontract_ppop_zip', 'sam_subcontract', ['ppop_zip_code'], unique=False)
    op.create_index('ix_sam_subcontract_updated_at', 'sam_subcontract', ['updated_at'], unique=False)

    op.create_index('ix_sam_subgrant_le_country', 'sam_subgrant', ['legal_entity_country_code'], unique=False)
    op.create_index('ix_sam_subgrant_le_state', 'sam_subgrant', ['legal_entity_state_code'], unique=False)
    op.create_index('ix_sam_subgrant_le_zip', 'sam_subgrant', ['legal_entity_zip_code'], unique=False)
    op.create_index('ix_sam_subgrant_ppop_country', 'sam_subgrant', ['ppop_country_code'], unique=False)
    op.create_index('ix_sam_subgrant_ppop_state', 'sam_subgrant', ['ppop_state_code'], unique=False)
    op.create_index('ix_sam_subgrant_ppop_zip', 'sam_subgrant', ['ppop_zip_code'], unique=False)
    op.create_index('ix_sam_subgrant_updated_at', 'sam_subgrant', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sam_subgrant_updated_at', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_ppop_zip', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_ppop_state', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_ppop_country', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_le_zip', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_le_state', table_name='sam_subgrant')
    op.drop_index('ix_sam_subgrant_le_country', table_name='sam_subgrant')

    op.drop_index('ix_sam_subcontract_updated_at', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_ppop_zip', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_ppop_state', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_ppop_country', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_le_zip', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_le_state', table_name='sam_subcontract')
    op.drop_index('ix_sam_subcontract_le_country', table_name='sam_subcontract')
    # ### end Alembic commands ###

