"""remove incorrect_password_attempts from user

Revision ID: e97127c44797
Revises: 98ad59ff4711
Create Date: 2016-12-22 10:02:02.806937

"""

# revision identifiers, used by Alembic.
revision = 'e97127c44797'
down_revision = '98ad59ff4711'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'incorrect_password_attempts')
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('incorrect_password_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    ### end Alembic commands ###

