"""remove_first_quarter_flag

Revision ID: ea8fbaa044d7
Revises: 0c857b50962a
Create Date: 2016-10-14 14:04:16.207464

"""

# revision identifiers, used by Alembic.
revision = 'ea8fbaa044d7'
down_revision = '0c857b50962a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appropriation', 'is_first_quarter')
    op.drop_column('award_financial', 'is_first_quarter')
    op.drop_column('award_financial_assistance', 'is_first_quarter')
    op.drop_column('object_class_program_activity', 'is_first_quarter')
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_class_program_activity', sa.Column('is_first_quarter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('award_financial_assistance', sa.Column('is_first_quarter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('award_financial', sa.Column('is_first_quarter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('appropriation', sa.Column('is_first_quarter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    ### end Alembic commands ###

