"""Add legal_entity_congressional to detached and published award financial assistance tables

Revision ID: f57696aefcc1
Revises: 41350e71ae8c
Create Date: 2017-04-21 10:12:04.850729

"""

# revision identifiers, used by Alembic.
revision = 'f57696aefcc1'
down_revision = '41350e71ae8c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_financial_assistance', sa.Column('legal_entity_congressional', sa.Text(), nullable=True))
    op.add_column('published_award_financial_assistance', sa.Column('legal_entity_congressional', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_award_financial_assistance', 'legal_entity_congressional')
    op.drop_column('detached_award_financial_assistance', 'legal_entity_congressional')
    ### end Alembic commands ###

