"""adding preferred city name to zip city

Revision ID: fb76b653c99d
Revises: d15d2cdfa25e
Create Date: 2023-04-20 17:33:27.323226

"""

# revision identifiers, used by Alembic.
revision = 'fb76b653c99d'
down_revision = 'd15d2cdfa25e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zip_city', sa.Column('preferred_city_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zip_city', 'preferred_city_name')
    # ### end Alembic commands ###

