"""fixing extraneous columns
Revision ID: fd0f86cc5705
Revises: 539307ecadea
Create Date: 2017-09-20 13:58:34.720047
"""

# revision identifiers, used by Alembic.
revision = 'fd0f86cc5705'
down_revision = '539307ecadea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detached_award_financial_assistance', 'legal_entity_country_name')
    op.drop_column('detached_award_financial_assistance', 'funding_office_name')
    op.drop_column('detached_award_financial_assistance', 'place_of_perform_county_na')
    op.drop_column('detached_award_financial_assistance', 'place_of_perform_country_n')
    op.drop_column('detached_award_financial_assistance', 'funding_agency_name')
    op.drop_column('detached_award_financial_assistance', 'place_of_perform_county_co')
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_financial_assistance', sa.Column('place_of_perform_county_co', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('detached_award_financial_assistance', sa.Column('funding_agency_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('detached_award_financial_assistance', sa.Column('place_of_perform_country_n', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('detached_award_financial_assistance', sa.Column('place_of_perform_county_na', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('detached_award_financial_assistance', sa.Column('funding_office_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('detached_award_financial_assistance', sa.Column('legal_entity_country_name', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
