"""add_tas_indices

Revision ID: a118bf9e4970
Revises: c0a714ade734
Create Date: 2016-04-26 22:16:33.624860

"""

# revision identifiers, used by Alembic.
revision = 'a118bf9e4970'
down_revision = 'c0a714ade734'
branch_labels = None
depends_on = None

from alembic import op
from dataactvalidator.models.validationModels import TASLookup


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_validation():
    """Drop existing non-PK indices to handle legacy installs & add new indices."""
    # drop indexes with legacy names, if they still exist
    op.execute('drop index if exists tas_lookup_allocation_transfer_agency_idx')
    op.execute('drop index if exists tas_lookup_availability_type_code_idx')
    op.execute('drop index if exists tas_lookup_beginning_period_of_availability_idx')
    op.execute('drop index if exists tas_lookup_main_account_code_idx')
    op.execute('drop index if exists tas_lookup_ending_period_of_availability_idx')
    op.execute('drop index if exists tas_lookup_sub_account_code_idx')
    op.execute('drop index if exists tas_lookup_agency_identifier_idx')

    # add next indexes based on model definition
    op.create_index(op.f('ix_tas_lookup_agency_identifier'), 'tas_lookup', ['agency_identifier'], unique=False)
    op.create_index(op.f('ix_tas_lookup_allocation_transfer_agency'), 'tas_lookup', ['allocation_transfer_agency'], unique=False)
    op.create_index(op.f('ix_tas_lookup_availability_type_code'), 'tas_lookup', ['availability_type_code'], unique=False)
    op.create_index(op.f('ix_tas_lookup_beginning_period_of_availability'), 'tas_lookup', ['beginning_period_of_availability'], unique=False)
    op.create_index(op.f('ix_tas_lookup_ending_period_of_availability'), 'tas_lookup', ['ending_period_of_availability'], unique=False)
    op.create_index(op.f('ix_tas_lookup_main_account_code'), 'tas_lookup', ['main_account_code'], unique=False)
    op.create_index(op.f('ix_tas_lookup_sub_account_code'), 'tas_lookup', ['sub_account_code'], unique=False)
    ### end Alembic commands ###


def downgrade_validation():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tas_lookup_sub_account_code'), table_name='tas_lookup')
    op.drop_index(op.f('ix_tas_lookup_main_account_code'), table_name='tas_lookup')
    op.drop_index(op.f('ix_tas_lookup_ending_period_of_availability'), table_name='tas_lookup')
    op.drop_index(op.f('ix_tas_lookup_beginning_period_of_availability'), table_name='tas_lookup')
    op.drop_index(op.f('ix_tas_lookup_availability_type_code'), table_name='tas_lookup')
    op.drop_index(op.f('ix_tas_lookup_allocation_transfer_agency'), table_name='tas_lookup')
    op.drop_index(op.f('ix_tas_lookup_agency_identifier'), table_name='tas_lookup')
    ### end Alembic commands ###

