"""addCrossTiming

Revision ID: b9e9c047042d
Revises: c0a714ade734
Create Date: 2016-04-21 19:09:59.778000

"""

# revision identifiers, used by Alembic.
revision = 'b9e9c047042d'
down_revision = 'c0a714ade734'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multi_field_rule', sa.Column('rule_timing_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'multi_field_rule', 'rule_timing', ['rule_timing_id'], ['rule_timing_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multi_field_rule', type_='foreignkey')
    op.drop_column('multi_field_rule', 'rule_timing_id')
    ### end Alembic commands ###
