"""addRuleTiming

Revision ID: e4d26a4b740e
Revises: 77ce67003a95
Create Date: 2016-03-24 14:24:55.778000

"""

# revision identifiers, used by Alembic.
revision = 'e4d26a4b740e'
down_revision = '77ce67003a95'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_timing',
    sa.Column('rule_timing_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('rule_timing_id')
    )
    op.add_column(u'rule', sa.Column('rule_timing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rule', 'rule_timing', ['rule_timing_id'], ['rule_timing_id'])
    op.drop_index('tas_lookup_agency_identifier_idx', table_name='tas_lookup')
    op.drop_index('tas_lookup_allocation_transfer_agency_idx', table_name='tas_lookup')
    op.drop_index('tas_lookup_availability_type_code_idx', table_name='tas_lookup')
    op.drop_index('tas_lookup_beginning_period_of_availability_idx', table_name='tas_lookup')
    op.drop_index('tas_lookup_ending_period_of_availability_idx', table_name='tas_lookup')
    op.drop_index('tas_lookup_main_account_code_idx', table_name='tas_lookup')
    op.drop_index('tas_lookup_sub_account_code_idx', table_name='tas_lookup')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tas_lookup_sub_account_code_idx', 'tas_lookup', ['sub_account_code'], unique=False)
    op.create_index('tas_lookup_main_account_code_idx', 'tas_lookup', ['main_account_code'], unique=False)
    op.create_index('tas_lookup_ending_period_of_availability_idx', 'tas_lookup', ['ending_period_of_availability'], unique=False)
    op.create_index('tas_lookup_beginning_period_of_availability_idx', 'tas_lookup', ['beginning_period_of_availability'], unique=False)
    op.create_index('tas_lookup_availability_type_code_idx', 'tas_lookup', ['availability_type_code'], unique=False)
    op.create_index('tas_lookup_allocation_transfer_agency_idx', 'tas_lookup', ['allocation_transfer_agency'], unique=False)
    op.create_index('tas_lookup_agency_identifier_idx', 'tas_lookup', ['agency_identifier'], unique=False)
    op.drop_constraint(None, 'rule', type_='foreignkey')
    op.drop_column(u'rule', 'rule_timing_id')
    op.drop_table('rule_timing')
    ### end Alembic commands ###
