import factory
from factory import fuzzy

from dataactcore.models import stagingModels


class AppropriationFactory(factory.Factory):
    class Meta:
        model = stagingModels.Appropriation

    appropriation_id = None
    submission_id = fuzzy.FuzzyInteger(9999)
    job_id = fuzzy.FuzzyInteger(9999)
    row_number = fuzzy.FuzzyInteger(1, 9999)
    adjustments_to_unobligated_cpe = fuzzy.FuzzyDecimal(9999)
    agency_identifier = fuzzy.FuzzyText()
    allocation_transfer_agency = fuzzy.FuzzyText()
    availability_type_code = fuzzy.FuzzyText()
    beginning_period_of_availa = fuzzy.FuzzyText()
    borrowing_authority_amount_cpe = fuzzy.FuzzyDecimal(9999)
    budget_authority_appropria_cpe = fuzzy.FuzzyDecimal(9999)
    budget_authority_available_cpe = fuzzy.FuzzyDecimal(9999)
    budget_authority_unobligat_fyb = fuzzy.FuzzyDecimal(9999)
    contract_authority_amount_cpe = fuzzy.FuzzyDecimal(9999)
    deobligations_recoveries_r_cpe = fuzzy.FuzzyDecimal(9999)
    ending_period_of_availabil = fuzzy.FuzzyText()
    gross_outlay_amount_by_tas_cpe = fuzzy.FuzzyDecimal(9999)
    main_account_code = fuzzy.FuzzyText()
    obligations_incurred_total_cpe = fuzzy.FuzzyDecimal(9999)
    other_budgetary_resources_cpe = fuzzy.FuzzyDecimal(9999)
    spending_authority_from_of_cpe = fuzzy.FuzzyDecimal(9999)
    status_of_budgetary_resour_cpe = fuzzy.FuzzyDecimal(9999)
    sub_account_code = fuzzy.FuzzyText()
    unobligated_balance_cpe = fuzzy.FuzzyDecimal(9999)
    tas = fuzzy.FuzzyText()
    is_first_quarter = False

class AwardFinancialFactory(factory.Factory):
    class Meta:
        model = stagingModels.AwardFinancial

    award_financial_id = None
    submission_id = fuzzy.FuzzyInteger(9999)
    job_id = fuzzy.FuzzyInteger(9999)
    row_number = fuzzy.FuzzyInteger(9999)
    agency_identifier = fuzzy.FuzzyText()
    allocation_transfer_agency = fuzzy.FuzzyText()
    availability_type_code = fuzzy.FuzzyText()
    beginning_period_of_availa = fuzzy.FuzzyText()
    by_direct_reimbursable_fun = fuzzy.FuzzyText()
    deobligations_recov_by_awa_cpe = fuzzy.FuzzyDecimal(9999)
    ending_period_of_availabil = fuzzy.FuzzyText()
    fain = fuzzy.FuzzyText()
    gross_outlay_amount_by_awa_cpe = fuzzy.FuzzyDecimal(9999)
    gross_outlay_amount_by_awa_fyb = fuzzy.FuzzyDecimal(9999)
    gross_outlays_delivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    gross_outlays_delivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    gross_outlays_undelivered_cpe = fuzzy.FuzzyDecimal(9999)
    gross_outlays_undelivered_fyb = fuzzy.FuzzyDecimal(9999)
    main_account_code = fuzzy.FuzzyText()
    object_class = fuzzy.FuzzyText()
    obligations_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    obligations_delivered_orde_fyb = fuzzy.FuzzyDecimal(9999)
    obligations_incurred_byawa_cpe = fuzzy.FuzzyDecimal(9999)
    obligations_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    obligations_undelivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    parent_award_id = fuzzy.FuzzyText()
    piid = fuzzy.FuzzyText()
    program_activity_code = fuzzy.FuzzyText()
    program_activity_name = fuzzy.FuzzyText()
    sub_account_code = fuzzy.FuzzyText()
    transaction_obligated_amou = fuzzy.FuzzyDecimal(9999)
    uri = fuzzy.FuzzyText()
    ussgl480100_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl480100_undelivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl480200_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl480200_undelivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl483100_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl483200_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl487100_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl487200_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl488100_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl488200_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490100_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490100_delivered_orde_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl490200_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490800_authority_outl_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490800_authority_outl_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl493100_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl497100_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl497200_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl498100_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl498200_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    tas = fuzzy.FuzzyText()
    is_first_quarter = False


class ObjectClassProgramActivityFactory(factory.Factory):
    class Meta:
        model = stagingModels.ObjectClassProgramActivity

    object_class_program_activity_id = None
    submission_id = fuzzy.FuzzyInteger(9999)
    job_id = fuzzy.FuzzyInteger(9999)
    row_number = fuzzy.FuzzyInteger(9999)
    agency_identifier = fuzzy.FuzzyText()
    allocation_transfer_agency = fuzzy.FuzzyText()
    availability_type_code = fuzzy.FuzzyText()
    beginning_period_of_availa = fuzzy.FuzzyText()
    by_direct_reimbursable_fun = fuzzy.FuzzyText()
    deobligations_recov_by_pro_cpe = fuzzy.FuzzyDecimal(9999)
    ending_period_of_availabil = fuzzy.FuzzyText()
    gross_outlay_amount_by_pro_cpe = fuzzy.FuzzyDecimal(9999)
    gross_outlay_amount_by_pro_fyb = fuzzy.FuzzyDecimal(9999)
    gross_outlays_delivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    gross_outlays_delivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    gross_outlays_undelivered_cpe = fuzzy.FuzzyDecimal(9999)
    gross_outlays_undelivered_fyb = fuzzy.FuzzyDecimal(9999)
    main_account_code = fuzzy.FuzzyText()
    object_class = fuzzy.FuzzyText()
    obligations_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    obligations_delivered_orde_fyb = fuzzy.FuzzyDecimal(9999)
    obligations_incurred_by_pr_cpe = fuzzy.FuzzyDecimal(9999)
    obligations_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    obligations_undelivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    program_activity_code = fuzzy.FuzzyText()
    program_activity_name = fuzzy.FuzzyText()
    sub_account_code = fuzzy.FuzzyText()
    ussgl480100_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl480100_undelivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl480200_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl480200_undelivered_or_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl483100_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl483200_undelivered_or_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl487100_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl487200_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl488100_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl488200_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490100_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490100_delivered_orde_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl490200_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490800_authority_outl_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl490800_authority_outl_fyb = fuzzy.FuzzyDecimal(9999)
    ussgl493100_delivered_orde_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl497100_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl497200_downward_adjus_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl498100_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    ussgl498200_upward_adjustm_cpe = fuzzy.FuzzyDecimal(9999)
    tas = fuzzy.FuzzyText()
    is_first_quarter = False


class AwardFinancialAssistanceFactory(factory.Factory):
    class Meta:
        model = stagingModels.AwardFinancialAssistance

    award_financial_assistance_id = None
    submission_id = fuzzy.FuzzyInteger(9999)
    job_id = fuzzy.FuzzyInteger(9999)
    row_number = fuzzy.FuzzyInteger(9999)
    action_date = fuzzy.FuzzyText()
    action_type = fuzzy.FuzzyText()
    assistance_type = fuzzy.FuzzyText()
    award_description = fuzzy.FuzzyText()
    awardee_or_recipient_legal = fuzzy.FuzzyText()
    awardee_or_recipient_uniqu = fuzzy.FuzzyText()
    awarding_agency_code = fuzzy.FuzzyText()
    awarding_agency_name = fuzzy.FuzzyText()
    awarding_office_code = fuzzy.FuzzyText()
    awarding_office_name = fuzzy.FuzzyText()
    awarding_sub_tier_agency_c = fuzzy.FuzzyText()
    awarding_sub_tier_agency_n = fuzzy.FuzzyText()
    award_modification_amendme = fuzzy.FuzzyText()
    business_funds_indicator = fuzzy.FuzzyText()
    business_types = fuzzy.FuzzyText()
    cfda_number = fuzzy.FuzzyText()
    cfda_title = fuzzy.FuzzyText()
    correction_late_delete_ind = fuzzy.FuzzyText()
    face_value_loan_guarantee = fuzzy.FuzzyText()
    fain = fuzzy.FuzzyText()
    federal_action_obligation = fuzzy.FuzzyText()
    fiscal_year_and_quarter_co = fuzzy.FuzzyText()
    funding_agency_code = fuzzy.FuzzyText()
    funding_agency_name = fuzzy.FuzzyText()
    funding_office_name = fuzzy.FuzzyText()
    funding_office_code = fuzzy.FuzzyText()
    funding_sub_tier_agency_co = fuzzy.FuzzyText()
    funding_sub_tier_agency_na = fuzzy.FuzzyText()
    legal_entity_address_line1 = fuzzy.FuzzyText()
    legal_entity_address_line2 = fuzzy.FuzzyText()
    legal_entity_address_line3 = fuzzy.FuzzyText()
    legal_entity_city_code = fuzzy.FuzzyText()
    legal_entity_city_name = fuzzy.FuzzyText()
    legal_entity_congressional = fuzzy.FuzzyText()
    legal_entity_country_code = fuzzy.FuzzyText()
    legal_entity_county_code = fuzzy.FuzzyText()
    legal_entity_county_name = fuzzy.FuzzyText()
    legal_entity_foreign_city = fuzzy.FuzzyText()
    legal_entity_foreign_posta = fuzzy.FuzzyText()
    legal_entity_foreign_provi = fuzzy.FuzzyText()
    legal_entity_state_code = fuzzy.FuzzyText()
    legal_entity_state_name = fuzzy.FuzzyText()
    legal_entity_zip5 = fuzzy.FuzzyText()
    legal_entity_zip_last4 = fuzzy.FuzzyText()
    non_federal_funding_amount = fuzzy.FuzzyText()
    original_loan_subsidy_cost = fuzzy.FuzzyText()
    period_of_performance_curr = fuzzy.FuzzyText()
    period_of_performance_star = fuzzy.FuzzyText()
    place_of_performance_city = fuzzy.FuzzyText()
    place_of_performance_code = fuzzy.FuzzyText()
    place_of_performance_congr = fuzzy.FuzzyText()
    place_of_perform_country_c = fuzzy.FuzzyText()
    place_of_perform_county_na = fuzzy.FuzzyText()
    place_of_performance_forei = fuzzy.FuzzyText()
    place_of_perform_state_nam = fuzzy.FuzzyText()
    place_of_performance_zip4a = fuzzy.FuzzyText()
    record_type = fuzzy.FuzzyText()
    sai_number = fuzzy.FuzzyText()
    total_funding_amount = fuzzy.FuzzyText()
    uri = fuzzy.FuzzyText()
    is_first_quarter = False