from collections import OrderedDict
from sqlalchemy import func, cast, Date

from dataactcore.models.stagingModels import DetachedAwardProcurement

file_model = DetachedAwardProcurement

mapping = OrderedDict([
    ('detached_award_proc_unique', ['ContractTransactionUniqueKey', 'ContractTransactionUniqueKey (407)']),
    ('unique_award_key', ['PrimeAwardUniqueKey', 'PrimeAwardUniqueKey (379)']),
    ('piid', ['PIID', 'PIID (34(A))']),
    ('award_modification_amendme', ['AwardModificationAmendmentNumber', 'AwardModificationAmendmentNumber (23)']),
    ('transaction_number', ['Transaction Number', 'Transaction Number (224)']),
    ('referenced_idv_agency_iden', ['Referenced IDV Agency Identifier', 'Referenced IDV Agency Identifier (93)']),
    ('referenced_idv_agency_desc', ['Referenced IDV Agency Name', 'Referenced IDV Agency Name (258)']),
    ('parent_award_id', ['ParentAwardId', 'ParentAwardId (24)']),
    ('referenced_idv_modificatio', ['Referenced IDV Modification Number', 'Referenced IDV Modification Number (254)']),
    ('federal_action_obligation', ['FederalActionObligation', 'FederalActionObligation (13)']),
    ('total_obligated_amount', ['TotalDollarsObligated', 'TotalDollarsObligated (314)']),
    ('base_exercised_options_val', ['BaseAndExercisedOptionsValue', 'BaseAndExercisedOptionsValue (259)']),
    ('current_total_value_award', ['CurrentTotalValueOfAward', 'CurrentTotalValueOfAward (14(A))']),
    ('base_and_all_options_value', ['BaseAndAllOptionsValue', 'BaseAndAllOptionsValue (260)']),
    ('potential_total_value_awar', ['PotentialTotalValueOfAward', 'PotentialTotalValueOfAward (15)']),
    ('action_date', ['ActionDate', 'ActionDate (25)']),
    ('period_of_performance_star', ['PeriodOfPerformanceStartDate', 'PeriodOfPerformanceStartDate (26)']),
    ('period_of_performance_curr', ['PeriodOfPerformanceCurrentEndDate', 'PeriodOfPerformanceCurrentEndDate (27)']),
    ('period_of_perf_potential_e', ['PeriodOfPerformancePotentialEndDate', 'PeriodOfPerformancePotentialEndDate (28)']),
    ('ordering_period_end_date', ['OrderingPeriodEndDate', 'OrderingPeriodEndDate (29)']),
    ('solicitation_date', ['SolicitationDate', 'SolicitationDate (414)']),
    ('awarding_agency_code', ['AwardingAgencyCode', 'AwardingAgencyCode (45)']),
    ('awarding_agency_name', ['AwardingAgencyName', 'AwardingAgencyName (44)']),
    ('awarding_sub_tier_agency_c', ['AwardingSubTierAgencyCode', 'AwardingSubTierAgencyCode (47)']),
    ('awarding_sub_tier_agency_n', ['AwardingSubTierAgencyName', 'AwardingSubTierAgencyName (46)']),
    ('awarding_office_code', ['AwardingOfficeCode', 'AwardingOfficeCode (49)']),
    ('awarding_office_name', ['AwardingOfficeName', 'AwardingOfficeName (48)']),
    ('funding_agency_code', ['FundingAgencyCode', 'FundingAgencyCode (39)']),
    ('funding_agency_name', ['FundingAgencyName', 'FundingAgencyName (38)']),
    ('funding_sub_tier_agency_co', ['FundingSubTierAgencyCode', 'FundingSubTierAgencyCode (41)']),
    ('funding_sub_tier_agency_na', ['FundingSubTierAgencyName', 'FundingSubTierAgencyName (40)']),
    ('funding_office_code', ['FundingOfficeCode', 'FundingOfficeCode (43)']),
    ('funding_office_name', ['FundingOfficeName', 'FundingOfficeName (42)']),
    ('foreign_funding', ['Foreign Funding', 'Foreign Funding (87)']),
    ('foreign_funding_desc', ['Foreign Funding Description Tag', 'Foreign Funding Description Tag (261)']),
    ('sam_exception', ['SAM Exception', 'SAM Exception (66)']),
    ('sam_exception_description', ['SAM Exception Description Tag', 'SAM Exception Description Tag (282)']),
    ('awardee_or_recipient_uniqu', ['AwardeeOrRecipientUniqueIdentifier', 'AwardeeOrRecipientUniqueIdentifier (2)']),
    ('awardee_or_recipient_legal', ['AwardeeOrRecipientLegalEntityName', 'AwardeeOrRecipientLegalEntityName (1)']),
    ('vendor_doing_as_business_n', ['Vendor Doing As Business Name', 'Vendor Doing As Business Name (203)']),
    ('cage_code', ['CAGE Code', 'CAGE Code (316)']),
    ('ultimate_parent_unique_ide', ['UltimateParentUniqueIdentifier', 'UltimateParentUniqueIdentifier (3)']),
    ('ultimate_parent_legal_enti', ['UltimateParentLegalEntityName', 'UltimateParentLegalEntityName (4)']),
    ('legal_entity_country_code', ['LegalEntityCountryCode', 'LegalEntityCountryCode (7)']),
    ('legal_entity_country_name', ['LegalEntityCountryName', 'LegalEntityCountryName (8)']),
    ('legal_entity_address_line1', ['LegalEntityAddressLine1', 'LegalEntityAddressLine1 (5(A))']),
    ('legal_entity_address_line2', ['LegalEntityAddressLine2', 'LegalEntityAddressLine2 (5(B))']),
    ('legal_entity_city_name', ['LegalEntityCityName', 'LegalEntityCityName (5(C)(i))']),
    ('legal_entity_state_code', ['LegalEntityStateCode', 'LegalEntityStateCode (5(D))']),
    ('legal_entity_state_descrip', ['LegalEntityStateDescription', 'LegalEntityStateDescription (5(D)(ii))']),
    ('legal_entity_zip4', ['LegalEntityZIP+4', 'LegalEntityZIP+4 (5(E)(iii))']),
    ('legal_entity_congressional', ['LegalEntityCongressionalDistrict', 'LegalEntityCongressionalDistrict (6)']),
    ('vendor_phone_number', ['Vendor Phone Number', 'Vendor Phone Number (171)']),
    ('vendor_fax_number', ['Vendor Fax Number', 'Vendor Fax Number (83)']),
    ('place_of_perform_city_name', ['PrimaryPlaceOfPerformanceCityName', 'PrimaryPlaceOfPerformanceCityName (30(C))']),
    ('place_of_perform_county_na', ['PrimaryPlaceOfPerformanceCountyName',
                                    'PrimaryPlaceOfPerformanceCountyName (30(E))']),
    ('place_of_performance_state', ['PrimaryPlaceOfPerformanceStateCode',
                                    'PrimaryPlaceOfPerformanceStateCode (30(B))']),
    ('place_of_perfor_state_desc', ['PrimaryPlaceOfPerformanceStateName',
                                    'PrimaryPlaceOfPerformanceStateName (30(D)(i))']),
    ('place_of_performance_zip4a', ['PrimaryPlaceOfPerformanceZIP+4', 'PrimaryPlaceOfPerformanceZIP+4 (30(F)(ii))']),
    ('place_of_performance_congr', ['PrimaryPlaceOfPerformanceCongressionalDistrict',
                                    'PrimaryPlaceOfPerformanceCongressionalDistrict (31)']),
    ('place_of_perform_country_c', ['PrimaryPlaceOfPerformanceCountryCode',
                                    'PrimaryPlaceOfPerformanceCountryCode (32)']),
    ('place_of_perf_country_desc', ['PrimaryPlaceOfPerformanceCountryName',
                                    'PrimaryPlaceOfPerformanceCountryName (33)']),
    ('pulled_from', ['Award Or IDV Flag', 'Award Or IDV Flag (257)']),
    ('contract_award_type', ['ContractAwardType', 'ContractAwardType (16(C))']),
    ('contract_award_type_desc', ['ContractAwardTypeDescriptionTag', 'ContractAwardTypeDescriptionTag (262)']),
    ('idv_type', ['IDV_Type', 'IDV_Type (16(B))']),
    ('idv_type_description', ['IDV_Type Description Tag', 'IDV_Type Description Tag (263)']),
    ('multiple_or_single_award_i', ['Multiple or Single Award IDV', 'Multiple or Single Award IDV (160)']),
    ('multiple_or_single_aw_desc', ['Multiple or Single Award IDV Description Tag',
                                    'Multiple or Single Award IDV Description Tag (264)']),
    ('type_of_idc', ['Type of IDC', 'Type of IDC (198)']),
    ('type_of_idc_description', ['Type of IDC Description Tag', 'Type of IDC Description Tag (265)']),
    ('type_of_contract_pricing', ['TypeOfContractPricing', 'TypeOfContractPricing (16(A))']),
    ('type_of_contract_pric_desc', ['TypeOfContractPricingDescriptionTag',
                                    'TypeOfContractPricingDescriptionTag (268)']),
    ('award_description', ['AwardDescription', 'AwardDescription (22)']),
    ('action_type', ['ActionType', 'ActionType (36(A))']),
    ('action_type_description', ['ActionTypeDescriptionTag', 'ActionTypeDescriptionTag (36(B))']),
    ('solicitation_identifier', ['Solicitation Identifier', 'Solicitation Identifier (190)']),
    ('number_of_actions', ['Number of Actions', 'Number of Actions (165)']),
    ('inherently_government_func', ['Inherently Governmental Functions', 'Inherently Governmental Functions (317)']),
    ('inherently_government_desc', ['Inherently Governmental Functions Description Tag',
                                    'Inherently Governmental Functions Description Tag (318)']),
    ('product_or_service_code', ['Product or Service Code', 'Product or Service Code (174)']),
    ('product_or_service_co_desc', ['Product or Service Code Description Tag',
                                    'Product or Service Code Description Tag (291)']),
    ('contract_bundling', ['Contract Bundling', 'Contract Bundling (70)']),
    ('contract_bundling_descrip', ['Contract Bundling Description Tag', 'Contract Bundling Description Tag (292)']),
    ('dod_claimant_program_code', ['DoD Claimant Program Code', 'DoD Claimant Program Code (62)']),
    ('dod_claimant_prog_cod_desc', ['DoD Claimant Program Code Description Tag',
                                    'DoD Claimant Program Code Description Tag (293)']),
    ('naics', ['NAICS', 'NAICS (17)']),
    ('naics_description', ['NAICS_Description', 'NAICS_Description (18)']),
    ('recovered_materials_sustai', ['Recovered Materials/Sustainability', 'Recovered Materials/Sustainability (182)']),
    ('recovered_materials_s_desc', ['Recovered Materials/Sustainability Description Tag',
                                    'Recovered Materials/Sustainability Description Tag (294)']),
    ('domestic_or_foreign_entity', ['Domestic or Foreign Entity', 'Domestic or Foreign Entity (253)']),
    ('domestic_or_foreign_e_desc', ['Domestic or Foreign Entity Description Tag',
                                    'Domestic or Foreign Entity Description Tag (295)']),
    ('program_system_or_equipmen', ['DOD Acquisition Program', 'DOD Acquisition Program (196)']),
    ('program_system_or_equ_desc', ['DOD Acquisition Program Description Tag',
                                    'DOD Acquisition Program Description Tag (296)']),
    ('information_technology_com', ['Information Technology Commercial Item Category',
                                    'Information Technology Commercial Item Category (94)']),
    ('information_technolog_desc', ['Information Technology Commercial Item Category Description Tag',
                                    'Information Technology Commercial Item Category Description Tag (297)']),
    ('epa_designated_product', ['EPA-Designated Product', 'EPA-Designated Product (200)']),
    ('epa_designated_produc_desc', ['EPA-Designated Product Description Tag',
                                    'EPA-Designated Product Description Tag (298)']),
    ('country_of_product_or_serv', ['Country of Product or Service Origin',
                                    'Country of Product or Service Origin (75)']),
    ('country_of_product_or_desc', ['Country of Product or Service Origin Description Tag',
                                    'Country of Product or Service Origin Description Tag (299)']),
    ('place_of_manufacture', ['Place of Manufacture', 'Place of Manufacture (172)']),
    ('place_of_manufacture_desc', ['Place of Manufacture Description Tag',
                                   'Place of Manufacture Description Tag (300)']),
    ('subcontracting_plan', ['Subcontracting Plan', 'Subcontracting Plan (195)']),
    ('subcontracting_plan_desc', ['Subcontracting Plan Description Tag', 'Subcontracting Plan Description Tag (313)']),
    ('extent_competed', ['Extent Competed', 'Extent Competed (82)']),
    ('extent_compete_description', ['Extent Competed Description Tag', 'Extent Competed Description Tag (301)']),
    ('solicitation_procedures', ['Solicitation Procedures', 'Solicitation Procedures (191)']),
    ('solicitation_procedur_desc', ['Solicitation Procedures Description Tag',
                                    'Solicitation Procedures Description Tag (302)']),
    ('type_set_aside', ['Type Set Aside', 'Type Set Aside (199)']),
    ('type_set_aside_description', ['Type Set Aside Description Tag', 'Type Set Aside Description Tag (303)']),
    ('evaluated_preference', ['Evaluated Preference', 'Evaluated Preference (81)']),
    ('evaluated_preference_desc', ['Evaluated Preference Description Tag',
                                   'Evaluated Preference Description Tag (304)']),
    ('research', ['Research', 'Research (183)']),
    ('research_description', ['Research Description Tag', 'Research Description Tag (305)']),
    ('fair_opportunity_limited_s', ['Fair Opportunity Limited Sources', 'Fair Opportunity Limited Sources (194)']),
    ('fair_opportunity_limi_desc', ['Fair Opportunity Limited Sources Description Tag',
                                    'Fair Opportunity Limited Sources Description Tag (306)']),
    ('other_than_full_and_open_c', ['Other than Full and Open Competition',
                                    'Other than Full and Open Competition (177)']),
    ('other_than_full_and_o_desc', ['Other than Full and Open Competition Description Tag',
                                    'Other than Full and Open Competition Description Tag (307)']),
    ('number_of_offers_received', ['Number of Offers Received', 'Number of Offers Received (168)']),
    ('commercial_item_acquisitio', ['Commercial Item Acquisition Procedures',
                                    'Commercial Item Acquisition Procedures (64)']),
    ('commercial_item_acqui_desc', ['Commercial Item Acquisition Procedures Description Tag',
                                    'Commercial Item Acquisition Procedures Description Tag (308)']),
    ('small_business_competitive', ['Small Business Competitiveness Demonstration Program',
                                    'Small Business Competitiveness Demonstration Program (189)']),
    ('commercial_item_test_progr', ['Simplified Procedures for Certain Commercial Items',
                                    'Simplified Procedures for Certain Commercial Items (65)']),
    ('commercial_item_test_desc', ['Commercial Item Test Program Description Tag',
                                   'Commercial Item Test Program Description Tag (309)']),
    ('a_76_fair_act_action', ['A-76 FAIR Act Action', 'A-76 FAIR Act Action (58)']),
    ('a_76_fair_act_action_desc', ['A-76 FAIR Act Action Description Tag',
                                   'A-76 FAIR Act Action Description Tag (310)']),
    ('fed_biz_opps', ['FedBizOpps', 'FedBizOpps (84)']),
    ('fed_biz_opps_description', ['FedBizOppsDescriptionTag', 'FedBizOppsDescriptionTag (311)']),
    ('local_area_set_aside', ['Local Area Set Aside', 'Local Area Set Aside (154)']),
    ('local_area_set_aside_desc', ['Local Area Set Aside Description Tag',
                                   'Local Area Set Aside Description Tag (312)']),
    ('price_evaluation_adjustmen', ['Price Evaluation Adjustment Preference Percent Difference',
                                    'Price Evaluation Adjustment Preference Percent Difference (173)']),
    ('clinger_cohen_act_planning', ['Clinger-Cohen Act Planning Compliance',
                                    'Clinger-Cohen Act Planning Compliance (63)']),
    ('clinger_cohen_act_pla_desc', ['Clinger-Cohen Act Planning Compliance Description Tag',
                                    'Clinger-Cohen Act Planning Compliance Description Tag (285)']),
    ('materials_supplies_article', ['Materials, Supplies, Articles & Equip',
                                    'Materials, Supplies, Articles & Equip (206)']),
    ('materials_supplies_descrip', ['Materials, Supplies, Articles & Equip Description Tag',
                                    'Materials, Supplies, Articles & Equip Description Tag (286)']),
    ('labor_standards', ['Labor Standards', 'Labor Standards (187)']),
    ('labor_standards_descrip', ['Labor Standards Description Tag', 'Labor Standards Description Tag (287)']),
    ('construction_wage_rate_req', ['Construction Wage Rate Requirements', 'Construction Wage Rate Requirements (76)']),
    ('construction_wage_rat_desc', ['Construction Wage Rate Requirements Description Tag',
                                    'Construction Wage Rate Requirements Description Tag (288)']),
    ('interagency_contracting_au', ['Interagency Contracting Authority', 'Interagency Contracting Authority (95)']),
    ('interagency_contract_desc', ['Interagency Contracting Authority Description Tag',
                                   'Interagency Contracting Authority Description Tag (289)']),
    ('other_statutory_authority', ['Other Statutory Authority', 'Other Statutory Authority (169)']),
    ('additional_reporting', ['Additional Reporting', 'Additional Reporting (417)']),
    ('program_acronym', ['Program Acronym', 'Program Acronym (175)']),
    ('referenced_idv_type', ['Referenced IDV Type', 'Referenced IDV Type (255)']),
    ('referenced_idv_type_desc', ['Referenced IDV Type Description Tag', 'Referenced IDV Type Description Tag (266)']),
    ('referenced_mult_or_single', ['Referenced IDV Multiple or Single', 'Referenced IDV Multiple or Single (256)']),
    ('referenced_mult_or_si_desc', ['Referenced IDV Multiple or Single Description Tag',
                                    'Referenced IDV Multiple or Single Description Tag (267)']),
    ('major_program', ['Major program', 'Major program (156)']),
    ('national_interest_action', ['National Interest Action', 'National Interest Action (163)']),
    ('national_interest_desc', ['National Interest Action Description Tag',
                                'National Interest Action Description Tag (270)']),
    ('cost_or_pricing_data', ['Cost or Pricing Data', 'Cost or Pricing Data (74)']),
    ('cost_or_pricing_data_desc', ['Cost or Pricing Data Description Tag',
                                   'Cost or Pricing Data Description Tag (271)']),
    ('cost_accounting_standards', ['Cost Accounting Standards Clause', 'Cost Accounting Standards Clause (73)']),
    ('cost_accounting_stand_desc', ['Cost Accounting Standards Clause Description Tag',
                                    'Cost Accounting Standards Clause Description Tag (272)']),
    ('government_furnished_prope', ['Government Furnished Property (GFP)', 'Government Furnished Property (GFP) (88)']),
    ('government_furnished_desc', ['Government Furnished Property GFP Description Tag',
                                   'Government Furnished Property GFP Description Tag (273)']),
    ('sea_transportation', ['Sea Transportation', 'Sea Transportation (186)']),
    ('sea_transportation_desc', ['Sea Transportation Description Tag', 'Sea Transportation Description Tag (274)']),
    ('undefinitized_action', ['Undefinitized Action', 'Undefinitized Action (153)']),
    ('undefinitized_action_desc', ['Undefinitized Action Description Tag',
                                   'Undefinitized Action Description Tag (275)']),
    ('consolidated_contract', ['Consolidated Contract', 'Consolidated Contract (68)']),
    ('consolidated_contract_desc', ['Consolidated Contract Description Tag',
                                    'Consolidated Contract Description Tag (276)']),
    ('performance_based_service', ['Performance-Based Service Acquisition',
                                   'Performance-Based Service Acquisition (170)']),
    ('performance_based_se_desc', ['Performance-Based Service Acquisition Description Tag',
                                   'Performance-Based Service Acquisition Description Tag (277)']),
    ('multi_year_contract', ['Multi Year Contract', 'Multi Year Contract (161)']),
    ('multi_year_contract_desc', ['Multi Year Contract Description Tag', 'Multi Year Contract Description Tag (278)']),
    ('contract_financing', ['Contract Financing', 'Contract Financing (71)']),
    ('contract_financing_descrip', ['Contract Financing Description Tag', 'Contract Financing Description Tag (280)']),
    ('purchase_card_as_payment_m', ['Purchase Card as Payment Method', 'Purchase Card as Payment Method (157)']),
    ('purchase_card_as_paym_desc', ['Purchase Card as Payment Method Description Tag',
                                    'Purchase Card as Payment Method Description Tag (281)']),
    ('contingency_humanitarian_o', ['Emergency Acquisition', 'Emergency Acquisition (69)']),
    ('contingency_humanitar_desc', ['Emergency Acquisition Description Tag',
                                    'Emergency Acquisition Description Tag (279)']),
    ('alaskan_native_owned_corpo', ['Alaskan Native Corporation Owned Firm',
                                    'Alaskan Native Corporation Owned Firm (100)']),
    ('american_indian_owned_busi', ['American Indian Owned Business', 'American Indian Owned Business (59)']),
    ('indian_tribe_federally_rec', ['Indian Tribe Federally Recognized', 'Indian Tribe Federally Recognized (121)']),
    ('native_hawaiian_owned_busi', ['Native Hawaiian Organization Owned Firm',
                                    'Native Hawaiian Organization Owned Firm (131)']),
    ('tribally_owned_business', ['Tribally Owned Firm', 'Tribally Owned Firm (150)']),
    ('veteran_owned_business', ['Veteran Owned Business', 'Veteran Owned Business (205)']),
    ('service_disabled_veteran_o', ['Service Disabled Veteran Owned Business',
                                    'Service Disabled Veteran Owned Business (192)']),
    ('woman_owned_business', ['Woman Owned Business', 'Woman Owned Business (207)']),
    ('women_owned_small_business', ['Women Owned Small Business', 'Women Owned Small Business (112)']),
    ('economically_disadvantaged', ['Economically Disadvantaged Women Owned Small Business',
                                    'Economically Disadvantaged Women Owned Small Business (112(A))']),
    ('joint_venture_women_owned', ['Joint Venture Women Owned Small Business',
                                   'Joint Venture Women Owned Small Business (112(B))']),
    ('joint_venture_economically', ['Joint Venture Economically Disadvantaged Women Owned Small Business',
                                    'Joint Venture Economically Disadvantaged Women Owned Small Business (112(C))']),
    ('minority_owned_business', ['Minority Owned Business', 'Minority Owned Business (159)']),
    ('subcontinent_asian_asian_i', ['Subcontinent Asian Asian - Indian American Owned Business',
                                    'Subcontinent Asian Asian - Indian American Owned Business (184)']),
    ('asian_pacific_american_own', ['Asian Pacific American Owned Business',
                                    'Asian Pacific American Owned Business (60)']),
    ('black_american_owned_busin', ['Black American Owned Business', 'Black American Owned Business (61)']),
    ('hispanic_american_owned_bu', ['Hispanic American Owned Business', 'Hispanic American Owned Business (89)']),
    ('native_american_owned_busi', ['Native American Owned Business', 'Native American Owned Business (162)']),
    ('other_minority_owned_busin', ['Other Minority Owned Business', 'Other Minority Owned Business (133)']),
    ('contracting_officers_deter', ['Contracting Officer\'s Determination of Business Size',
                                    'Contracting Officer\'s Determination of Business Size (72)']),
    ('contracting_officers_desc', ['Contracting Officer\'s Determination of Business Size Description Tag',
                                   'Contracting Officer\'s Determination of Business Size Description Tag (284)']),
    ('emerging_small_business', ['Emerging Small Business', 'Emerging Small Business (80)']),
    ('community_developed_corpor', ['Community Developed Corporation Owned Firm',
                                    'Community Developed Corporation Owned Firm (103)']),
    ('labor_surplus_area_firm', ['Labor Surplus Area Firm', 'Labor Surplus Area Firm (126)']),
    ('us_federal_government', ['U.S. Federal Government', 'U.S. Federal Government (85)']),
    ('federally_funded_research', ['Federally Funded Research and Development Corp',
                                   'Federally Funded Research and Development Corp (114)']),
    ('federal_agency', ['Federal Agency', 'Federal Agency (113)']),
    ('us_state_government', ['U.S. State Government', 'U.S. State Government (193)']),
    ('us_local_government', ['U.S. Local Government', 'U.S. Local Government (155)']),
    ('city_local_government', ['City Local Government', 'City Local Government (102)']),
    ('county_local_government', ['County Local Government', 'County Local Government (109)']),
    ('inter_municipal_local_gove', ['Inter-Municipal Local Government', 'Inter-Municipal Local Government (122)']),
    ('local_government_owned', ['Local Government Owned', 'Local Government Owned (128)']),
    ('municipality_local_governm', ['Municipality Local Government', 'Municipality Local Government (130)']),
    ('school_district_local_gove', ['School District Local Government', 'School District Local Government (140)']),
    ('township_local_government', ['Township Local Government', 'Township Local Government (147)']),
    ('us_tribal_government', ['U.S. Tribal Government', 'U.S. Tribal Government (197)']),
    ('foreign_government', ['Foreign Government', 'Foreign Government (115)']),
    ('organizational_type', ['OrganizationalType', 'OrganizationalType (331)']),
    ('corporate_entity_not_tax_e', ['Corporate Entity Not Tax Exempt', 'Corporate Entity Not Tax Exempt (106)']),
    ('corporate_entity_tax_exemp', ['Corporate Entity Tax Exempt', 'Corporate Entity Tax Exempt (107)']),
    ('partnership_or_limited_lia', ['Partnership or Limited Liability Partnership',
                                    'Partnership or Limited Liability Partnership (135)']),
    ('sole_proprietorship', ['Sole Proprietorship', 'Sole Proprietorship (144)']),
    ('small_agricultural_coopera', ['Small Agricultural Cooperative', 'Small Agricultural Cooperative (143)']),
    ('international_organization', ['International Organization', 'International Organization (123)']),
    ('us_government_entity', ['U.S. Government Entity', 'U.S. Government Entity (132)']),
    ('community_development_corp', ['Community Development Corporation', 'Community Development Corporation (104)']),
    ('domestic_shelter', ['Domestic Shelter', 'Domestic Shelter (110)']),
    ('educational_institution', ['Educational Institution', 'Educational Institution (79)']),
    ('foundation', ['Foundation', 'Foundation (118)']),
    ('hospital_flag', ['Hospital Flag', 'Hospital Flag (91)']),
    ('manufacturer_of_goods', ['Manufacturer of Goods', 'Manufacturer of Goods (129)']),
    ('veterinary_hospital', ['Veterinary Hospital', 'Veterinary Hospital (152)']),
    ('hispanic_servicing_institu', ['Hispanic Servicing Institution', 'Hispanic Servicing Institution (119)']),
    ('contracts', ['Contracts', 'Contracts (179)']),
    ('grants', ['Federal Assistance Awards', 'Federal Assistance Awards (181)']),
    ('receives_contracts_and_gra', ['All Awards', 'All Awards (180)']),
    ('airport_authority', ['Airport Authority', 'Airport Authority (99)']),
    ('council_of_governments', ['Council of Governments', 'Council of Governments (108)']),
    ('housing_authorities_public', ['Housing Authorities Public/Tribal', 'Housing Authorities Public/Tribal (120)']),
    ('interstate_entity', ['Interstate Entity', 'Interstate Entity (124)']),
    ('planning_commission', ['Planning Commission', 'Planning Commission (136)']),
    ('port_authority', ['Port Authority', 'Port Authority (137)']),
    ('transit_authority', ['Transit Authority', 'Transit Authority (148)']),
    ('subchapter_s_corporation', ['Subchapter S Corporation', 'Subchapter S Corporation (146)']),
    ('limited_liability_corporat', ['Limited Liability Corporation', 'Limited Liability Corporation (127)']),
    ('foreign_owned_and_located', ['Foreign Owned', 'Foreign Owned (116)']),
    ('for_profit_organization', ['For Profit Organization', 'For Profit Organization (117)']),
    ('nonprofit_organization', ['Nonprofit Organization', 'Nonprofit Organization (164)']),
    ('other_not_for_profit_organ', ['Other Not For Profit Organization', 'Other Not For Profit Organization (134)']),
    ('the_ability_one_program', ['The AbilityOne Program', 'The AbilityOne Program (188)']),
    ('private_university_or_coll', ['Private University or College', 'Private University or College (138)']),
    ('state_controlled_instituti', ['State Controlled Institution of Higher Learning',
                                    'State Controlled Institution of Higher Learning (145)']),
    ('c1862_land_grant_college', ['1862 Land Grant College', '1862 Land Grant College (96)']),
    ('c1890_land_grant_college', ['1890 Land Grant College', '1890 Land Grant College (97)']),
    ('c1994_land_grant_college', ['1994 Land Grant College', '1994 Land Grant College (98)']),
    ('minority_institution', ['Minority Institution', 'Minority Institution (158)']),
    ('historically_black_college', ['Historically Black College or University',
                                    'Historically Black College or University (90)']),
    ('tribal_college', ['Tribal College', 'Tribal College (149)']),
    ('alaskan_native_servicing_i', ['Alaskan Native Servicing Institution',
                                    'Alaskan Native Servicing Institution (251)']),
    ('native_hawaiian_servicing', ['Native Hawaiian Servicing Institution',
                                   'Native Hawaiian Servicing Institution (252)']),
    ('school_of_forestry', ['School of Forestry', 'School of Forestry (141)']),
    ('veterinary_college', ['Veterinary College', 'Veterinary College (151)']),
    ('dot_certified_disadvantage', ['DoT Certified Disadvantaged Business Enterprise',
                                    'DoT Certified Disadvantaged Business Enterprise (111)']),
    ('self_certified_small_disad', ['Self-Certified Small Disadvantaged Business',
                                    'Self-Certified Small Disadvantaged Business (185)']),
    ('small_disadvantaged_busine', ['Small Disadvantaged Business', 'Small Disadvantaged Business (139)']),
    ('c8a_program_participant', ['8a Program Participant', '8a Program Participant (86)']),
    ('historically_underutilized', ['Historically Underutilized Business Zone HUBZone Firm',
                                    'Historically Underutilized Business Zone HUBZone Firm (92)']),
    ('sba_certified_8_a_joint_ve', ['SBA Certified 8 a Joint Venture', 'SBA Certified 8 a Joint Venture (125)']),
    ('last_modified', ['LastModifiedDate', 'LastModifiedDate (247)'])
])
db_columns = [key for key in mapping]


def query_data(session, agency_code, agency_type, start, end):
    """ Request D1 file data

        Args:
            session: DB session
            agency_code: FREC or CGAC code for generation
            agency_type: The type of agency (awarding or funding) to generate the file for
            start: Beginning of period for D file
            end: End of period for D file

        Returns:
            The rows using the provided dates for the given agency.
    """
    rows = initial_query(session).\
        filter(func.cast_as_date(file_model.action_date) >= start).\
        filter(func.cast_as_date(file_model.action_date) <= end)

    # Funding or awarding agency filtering
    if agency_type == 'funding':
        rows = rows.filter(file_model.funding_agency_code == agency_code)
    else:
        rows = rows.filter(file_model.awarding_agency_code == agency_code)

    return rows


def initial_query(session):
    return session.query(*[
        file_model.detached_award_proc_unique,
        file_model.unique_award_key,
        file_model.piid,
        file_model.award_modification_amendme,
        file_model.transaction_number,
        file_model.referenced_idv_agency_iden,
        file_model.referenced_idv_agency_desc,
        file_model.parent_award_id,
        file_model.referenced_idv_modificatio,
        file_model.federal_action_obligation,
        file_model.total_obligated_amount,
        file_model.base_exercised_options_val,
        file_model.current_total_value_award,
        file_model.base_and_all_options_value,
        file_model.potential_total_value_awar,
        func.to_char(cast(file_model.action_date, Date), 'YYYYMMDD'),
        func.to_char(cast(file_model.period_of_performance_star, Date), 'YYYYMMDD'),
        func.to_char(cast(file_model.period_of_performance_curr, Date), 'YYYYMMDD'),
        func.to_char(cast(file_model.period_of_perf_potential_e, Date), 'YYYYMMDD'),
        func.to_char(cast(file_model.ordering_period_end_date, Date), 'YYYYMMDD'),
        func.to_char(cast(file_model.solicitation_date, Date), 'YYYYMMDD'),
        file_model.awarding_agency_code,
        file_model.awarding_agency_name,
        file_model.awarding_sub_tier_agency_c,
        file_model.awarding_sub_tier_agency_n,
        file_model.awarding_office_code,
        file_model.awarding_office_name,
        file_model.funding_agency_code,
        file_model.funding_agency_name,
        file_model.funding_sub_tier_agency_co,
        file_model.funding_sub_tier_agency_na,
        file_model.funding_office_code,
        file_model.funding_office_name,
        file_model.foreign_funding,
        file_model.foreign_funding_desc,
        file_model.sam_exception,
        file_model.sam_exception_description,
        file_model.awardee_or_recipient_uniqu,
        file_model.awardee_or_recipient_legal,
        file_model.vendor_doing_as_business_n,
        file_model.cage_code,
        file_model.ultimate_parent_unique_ide,
        file_model.ultimate_parent_legal_enti,
        file_model.legal_entity_country_code,
        file_model.legal_entity_country_name,
        file_model.legal_entity_address_line1,
        file_model.legal_entity_address_line2,
        file_model.legal_entity_city_name,
        file_model.legal_entity_state_code,
        file_model.legal_entity_state_descrip,
        file_model.legal_entity_zip4,
        file_model.legal_entity_congressional,
        file_model.vendor_phone_number,
        file_model.vendor_fax_number,
        file_model.place_of_perform_city_name,
        file_model.place_of_perform_county_na,
        file_model.place_of_performance_state,
        file_model.place_of_perfor_state_desc,
        file_model.place_of_performance_zip4a,
        file_model.place_of_performance_congr,
        file_model.place_of_perform_country_c,
        file_model.place_of_perf_country_desc,
        file_model.pulled_from,
        file_model.contract_award_type,
        file_model.contract_award_type_desc,
        file_model.idv_type,
        file_model.idv_type_description,
        file_model.multiple_or_single_award_i,
        file_model.multiple_or_single_aw_desc,
        file_model.type_of_idc,
        file_model.type_of_idc_description,
        file_model.type_of_contract_pricing,
        file_model.type_of_contract_pric_desc,
        file_model.award_description,
        file_model.action_type,
        file_model.action_type_description,
        file_model.solicitation_identifier,
        file_model.number_of_actions,
        file_model.inherently_government_func,
        file_model.inherently_government_desc,
        file_model.product_or_service_code,
        file_model.product_or_service_co_desc,
        file_model.contract_bundling,
        file_model.contract_bundling_descrip,
        file_model.dod_claimant_program_code,
        file_model.dod_claimant_prog_cod_desc,
        file_model.naics,
        file_model.naics_description,
        file_model.recovered_materials_sustai,
        file_model.recovered_materials_s_desc,
        file_model.domestic_or_foreign_entity,
        file_model.domestic_or_foreign_e_desc,
        file_model.program_system_or_equipmen,
        file_model.program_system_or_equ_desc,
        file_model.information_technology_com,
        file_model.information_technolog_desc,
        file_model.epa_designated_product,
        file_model.epa_designated_produc_desc,
        file_model.country_of_product_or_serv,
        file_model.country_of_product_or_desc,
        file_model.place_of_manufacture,
        file_model.place_of_manufacture_desc,
        file_model.subcontracting_plan,
        file_model.subcontracting_plan_desc,
        file_model.extent_competed,
        file_model.extent_compete_description,
        file_model.solicitation_procedures,
        file_model.solicitation_procedur_desc,
        file_model.type_set_aside,
        file_model.type_set_aside_description,
        file_model.evaluated_preference,
        file_model.evaluated_preference_desc,
        file_model.research,
        file_model.research_description,
        file_model.fair_opportunity_limited_s,
        file_model.fair_opportunity_limi_desc,
        file_model.other_than_full_and_open_c,
        file_model.other_than_full_and_o_desc,
        file_model.number_of_offers_received,
        file_model.commercial_item_acquisitio,
        file_model.commercial_item_acqui_desc,
        file_model.small_business_competitive,
        file_model.commercial_item_test_progr,
        file_model.commercial_item_test_desc,
        file_model.a_76_fair_act_action,
        file_model.a_76_fair_act_action_desc,
        file_model.fed_biz_opps,
        file_model.fed_biz_opps_description,
        file_model.local_area_set_aside,
        file_model.local_area_set_aside_desc,
        file_model.price_evaluation_adjustmen,
        file_model.clinger_cohen_act_planning,
        file_model.clinger_cohen_act_pla_desc,
        file_model.materials_supplies_article,
        file_model.materials_supplies_descrip,
        file_model.labor_standards,
        file_model.labor_standards_descrip,
        file_model.construction_wage_rate_req,
        file_model.construction_wage_rat_desc,
        file_model.interagency_contracting_au,
        file_model.interagency_contract_desc,
        file_model.other_statutory_authority,
        file_model.additional_reporting,
        file_model.program_acronym,
        file_model.referenced_idv_type,
        file_model.referenced_idv_type_desc,
        file_model.referenced_mult_or_single,
        file_model.referenced_mult_or_si_desc,
        file_model.major_program,
        file_model.national_interest_action,
        file_model.national_interest_desc,
        file_model.cost_or_pricing_data,
        file_model.cost_or_pricing_data_desc,
        file_model.cost_accounting_standards,
        file_model.cost_accounting_stand_desc,
        file_model.government_furnished_prope,
        file_model.government_furnished_desc,
        file_model.sea_transportation,
        file_model.sea_transportation_desc,
        file_model.undefinitized_action,
        file_model.undefinitized_action_desc,
        file_model.consolidated_contract,
        file_model.consolidated_contract_desc,
        file_model.performance_based_service,
        file_model.performance_based_se_desc,
        file_model.multi_year_contract,
        file_model.multi_year_contract_desc,
        file_model.contract_financing,
        file_model.contract_financing_descrip,
        file_model.purchase_card_as_payment_m,
        file_model.purchase_card_as_paym_desc,
        file_model.contingency_humanitarian_o,
        file_model.contingency_humanitar_desc,
        file_model.alaskan_native_owned_corpo,
        file_model.american_indian_owned_busi,
        file_model.indian_tribe_federally_rec,
        file_model.native_hawaiian_owned_busi,
        file_model.tribally_owned_business,
        file_model.veteran_owned_business,
        file_model.service_disabled_veteran_o,
        file_model.woman_owned_business,
        file_model.women_owned_small_business,
        file_model.economically_disadvantaged,
        file_model.joint_venture_women_owned,
        file_model.joint_venture_economically,
        file_model.minority_owned_business,
        file_model.subcontinent_asian_asian_i,
        file_model.asian_pacific_american_own,
        file_model.black_american_owned_busin,
        file_model.hispanic_american_owned_bu,
        file_model.native_american_owned_busi,
        file_model.other_minority_owned_busin,
        file_model.contracting_officers_deter,
        file_model.contracting_officers_desc,
        file_model.emerging_small_business,
        file_model.community_developed_corpor,
        file_model.labor_surplus_area_firm,
        file_model.us_federal_government,
        file_model.federally_funded_research,
        file_model.federal_agency,
        file_model.us_state_government,
        file_model.us_local_government,
        file_model.city_local_government,
        file_model.county_local_government,
        file_model.inter_municipal_local_gove,
        file_model.local_government_owned,
        file_model.municipality_local_governm,
        file_model.school_district_local_gove,
        file_model.township_local_government,
        file_model.us_tribal_government,
        file_model.foreign_government,
        file_model.organizational_type,
        file_model.corporate_entity_not_tax_e,
        file_model.corporate_entity_tax_exemp,
        file_model.partnership_or_limited_lia,
        file_model.sole_proprietorship,
        file_model.small_agricultural_coopera,
        file_model.international_organization,
        file_model.us_government_entity,
        file_model.community_development_corp,
        file_model.domestic_shelter,
        file_model.educational_institution,
        file_model.foundation,
        file_model.hospital_flag,
        file_model.manufacturer_of_goods,
        file_model.veterinary_hospital,
        file_model.hispanic_servicing_institu,
        file_model.contracts,
        file_model.grants,
        file_model.receives_contracts_and_gra,
        file_model.airport_authority,
        file_model.council_of_governments,
        file_model.housing_authorities_public,
        file_model.interstate_entity,
        file_model.planning_commission,
        file_model.port_authority,
        file_model.transit_authority,
        file_model.subchapter_s_corporation,
        file_model.limited_liability_corporat,
        file_model.foreign_owned_and_located,
        file_model.for_profit_organization,
        file_model.nonprofit_organization,
        file_model.other_not_for_profit_organ,
        file_model.the_ability_one_program,
        file_model.private_university_or_coll,
        file_model.state_controlled_instituti,
        file_model.c1862_land_grant_college,
        file_model.c1890_land_grant_college,
        file_model.c1994_land_grant_college,
        file_model.minority_institution,
        file_model.historically_black_college,
        file_model.tribal_college,
        file_model.alaskan_native_servicing_i,
        file_model.native_hawaiian_servicing,
        file_model.school_of_forestry,
        file_model.veterinary_college,
        file_model.dot_certified_disadvantage,
        file_model.self_certified_small_disad,
        file_model.small_disadvantaged_busine,
        file_model.c8a_program_participant,
        file_model.historically_underutilized,
        file_model.sba_certified_8_a_joint_ve,
        func.to_char(cast(file_model.last_modified, Date), 'YYYYMMDD')])
