name: Code Style Checks

on:
  workflow_call:

jobs:
  Run:
    # These checks are not broken out into multiple jobs because the steps to prepare the environment
    # take the bulk of the time. Running them in parallel saves minimal time at the cost of using more
    # runners than needed.
    name: Run
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Run Flake8
        run: flake8

      - name: Run Black
        run: black --check --diff .
